import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{resolve}from"node:path";import test from"node:test";import{NOVA_BOUNDARY_NOTICE,createNovaRequest,parseNovaResponse,verifiedRulesAnswer}from"@/lib/nova/openai-request";
const actions=readFileSync(resolve(process.cwd(),"app/actions/nova.ts"),"utf8"),advisor=readFileSync(resolve(process.cwd(),"lib/nova/advisor.ts"),"utf8"),page=readFileSync(resolve(process.cwd(),"app/nova/page.tsx"),"utf8");
const context={summary:{activeLoads:2,exceptionLoads:1},alerts:["1 verified load exception requires human review."],priorityLoads:[]};
test("Nova request is private structured and grounded",()=>{const request=createNovaRequest("What needs review?",context,"test-model")as Record<string,unknown>;assert.equal(request.store,false);assert.match(JSON.stringify(request),/VERIFIED_CONTEXT/);assert.match(JSON.stringify(request),/Never invent a load/);assert.match(JSON.stringify(request),/human_approval_required/)});
test("Nova parser requires the fixed human-control boundary",()=>{const body={output_text:JSON.stringify({answer:"Review the recorded exception.",verified_facts:["One exception is recorded."],suggested_reviews:["Open Dispatch."],human_approval_required:true,boundary_notice:NOVA_BOUNDARY_NOTICE})};const result=parseNovaResponse(body);assert.equal(result.source,"openai");assert.equal(result.humanApprovalRequired,true);assert.throws(()=>parseNovaResponse({output_text:JSON.stringify({...JSON.parse(body.output_text),boundary_notice:"Nova may dispatch."})}))});
test("rules fallback uses only verified context and stays assistive",()=>{const result=verifiedRulesAnswer(context);assert.equal(result.source,"verified_rules");assert.match(result.answer,/2 active loads/);assert.equal(result.boundaryNotice,NOVA_BOUNDARY_NOTICE)});
test("server action re-authenticates and preserves role-scoped finance",()=>{assert.match(actions,/requireDocumentAuth\(\)/);assert.match(actions,/FINANCE\.has\(auth\.businessRole\)\?load\.rateCents:undefined/);assert.match(actions,/question\.trim\(\)[\s\S]*slice\(0,800\)/)});
test("Nova path has no database mutation or conversation persistence",()=>{assert.doesNotMatch(actions,/\.insert\(|\.update\(|\.delete\(|\.upsert\(|revalidatePath/);assert.doesNotMatch(advisor,/console\.|store:true/);assert.match(page,/No conversation is written to the database/)});
test("UI and prompt retain dispatch safety and money boundaries",()=>{assert.match(page,/Nova cannot dispatch, direct movement, determine equipment safety, change records, approve documents, set payroll, issue invoices, or mark payments/);assert.match(JSON.stringify(createNovaRequest("x",context,"m")),/Never dispatch a load/)});
