import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{resolve}from"node:path";import test from"node:test";const migration=readFileSync(resolve(process.cwd(),"supabase/migrations/20260822110000_verified_fuel_ifta_ledger.sql"),"utf8"),rollback=readFileSync(resolve(process.cwd(),"supabase/rollback/20260822110000_verified_fuel_ifta_ledger_rollback.sql"),"utf8"),actions=readFileSync(resolve(process.cwd(),"app/actions/ifta.ts"),"utf8"),page=readFileSync(resolve(process.cwd(),"app/ifta/page.tsx"),"utf8");
test("fuel and mileage records are company-linked to verified trucks",()=>{assert.match(migration,/fuel_asset_company_fk/);assert.match(migration,/ifta_mileage_asset_company_fk/);assert.match(migration,/references public\.fleet_assets\(company_id,id\)/);assert.match(migration,/a\.asset_type='truck'/)});
test("IFTA summary preserves missing mileage or gallons",()=>{assert.match(migration,/left join m using\(asset_id,jurisdiction\)left join f/);assert.doesNotMatch(migration,/coalesce\(m\.miles|coalesce\(f\.gallons/);assert.match(page,/Missing evidence stays missing/)});
test("only current member jurisdictions are accepted",()=>{assert.match(migration,/48 contiguous States/);assert.match(migration,/is_ifta_member_jurisdiction/);assert.doesNotMatch(migration,/['\"]AK['\"]|['\"]HI['\"]|['\"]DC['\"]/)});
test("receipt-backed fuel requires a current approved receipt",()=>{assert.match(migration,/p_source='receipt'/);assert.match(migration,/public\.is_current_approved_document\(p_receipt_document_id,'fuel_receipt'\)/)});
test("writes are finance scoped idempotent and append audited",()=>{assert.match(migration,/v_role not in\('super_admin','owner','accounting'\)/);assert.match(migration,/unique\(company_id,request_id\)/);assert.match(migration,/create table public\.ifta_record_events/);assert.doesNotMatch(migration,/grant (?:insert|update|delete).*fuel_purchase_records.*authenticated/i)});
test("corrections void but never delete evidence",()=>{assert.match(migration,/void_verified_ifta_record/);assert.match(migration,/status='voided'/);assert.doesNotMatch(migration,/delete from public\.(fuel_purchase_records|ifta_mileage_records)/)});
test("server actions authenticate validate and use atomic RPCs",()=>{assert.match(actions,/requireDocumentAuth\(\)/);assert.match(actions,/record_verified_fuel_purchase/);assert.match(actions,/record_verified_ifta_mileage/);assert.match(page,/Excel-ready CSV/);assert.match(page,/Print \/ PDF/)});
test("rollback preserves fuel mileage void and audit history",()=>{assert.match(rollback,/preserves every record and audit event/);assert.doesNotMatch(rollback,/delete from|truncate|drop table/i)});
