export {
  ALPH_YOU_DECIDE_NOTICE,
  ENGINEERING_CONSTITUTION_GOVERNED_BY,
  ENGINEERING_CONSTITUTION_HREF,
  ENGINEERING_CONSTITUTION_MISSION,
  ENGINEERING_CONSTITUTION_PRINCIPLE_IDS,
  ENGINEERING_CONSTITUTION_PRINCIPLES,
  ENGINEERING_CONSTITUTION_TAGLINE,
  ENGINEERING_CONSTITUTION_TITLE,
  getConstitutionPrinciple,
  type EngineeringConstitutionPrinciple,
  type EngineeringConstitutionPrincipleId,
} from "@/lib/engineering-constitution/principles";
