import type { AlphIntentDefinition, AlphIntentId } from "@/lib/alph/types";

export const ALPH_DEMO_TODAY = "2026-07-17";

export const ALPH_SUGGESTION_COMMANDS = [
  "Show today's loads",
  "Find Truck 105",
  "Find available drivers near Dallas",
  "Generate payroll",
  "Generate IFTA",
  "Create invoice",
  "Show unpaid invoices",
  "Show loads in Texas",
  "Replay Truck 102",
  "Show trucks needing maintenance",
  "Who is my best broker?",
  "Open John Smith",
  "Morning briefing",
  "Is my ELD supported?",
  "Which ELDs support IFTA mileage?",
  "Help me finish company setup",
  "Why is my ELD disconnected?",
  "Has my issue been resolved?",
  "Show workforce",
  "Find reefer drivers to hire",
  "Open AI recruiting",
  "Open Verified Network",
  "Find reefer mechanics nearby",
  "Open my Transpo ID",
  "Open Platform",
  "Open App Store",
  "Create a load",
  "Pay invoice",
  "Schedule maintenance",
  "Open Command Center",
  "Open Transpo Exchange",
  "Best reefer under $45k",
  "Used Cascadias within 300 miles",
  "Compare three fuel cards",
  "Open Alph Copilot",
  "Open Driver Alph",
  "Open Dispatcher Alph",
  "Open Owner Alph",
  "Assign best driver",
  "Find reload",
  "Handle payroll",
  "Show today's profit",
  "Find nearest truck wash",
] as const;

export const ALPH_INTENT_CATALOG: AlphIntentDefinition[] = [
  {
    id: "show_loads",
    label: "Show loads",
    examples: ["Show today's loads", "Show loads", "List active loads"],
    keywords: ["load", "loads", "dispatch", "shipments"],
  },
  {
    id: "find_drivers",
    label: "Find drivers",
    examples: ["Find available drivers near Dallas", "Show available drivers"],
    keywords: ["driver", "drivers", "available", "near"],
  },
  {
    id: "generate_payroll",
    label: "Generate payroll",
    examples: ["Generate payroll", "Run payroll", "Open payroll"],
    keywords: ["payroll", "pay drivers", "settlements"],
  },
  {
    id: "generate_ifta",
    label: "Generate IFTA",
    examples: ["Generate IFTA", "Open IFTA", "Fuel tax"],
    keywords: ["ifta", "fuel tax", "quarterly fuel"],
  },
  {
    id: "create_invoice",
    label: "Create invoice",
    examples: ["Create invoice", "Generate invoice", "New invoice"],
    keywords: ["invoice", "invoices", "bill"],
  },
  {
    id: "replay_truck",
    label: "Replay truck tracking",
    examples: ["Replay Truck 102", "Replay Truck 23"],
    keywords: ["replay", "tracking replay", "trip replay"],
  },
  {
    id: "show_maintenance",
    label: "Maintenance needed",
    examples: ["Show trucks needing maintenance", "Open maintenance"],
    keywords: ["maintenance", "repair", "pm", "service"],
  },
  {
    id: "find_unpaid_invoices",
    label: "Unpaid invoices",
    examples: ["Find unpaid invoices over 30 days", "Show overdue invoices"],
    keywords: ["unpaid", "overdue", "outstanding"],
  },
  {
    id: "best_broker",
    label: "Best broker",
    examples: ["Who is my best broker?", "Top broker"],
    keywords: ["best broker", "top broker", "favorite broker"],
  },
  {
    id: "top_profit_truck",
    label: "Top profit truck",
    examples: ["Which truck made the most profit?", "Most profitable truck"],
    keywords: ["profit", "profitable", "made the most"],
  },
  {
    id: "loads_missing_pod",
    label: "Loads missing POD",
    examples: ["Show loads missing POD", "Missing proof of delivery"],
    keywords: ["pod", "proof of delivery", "missing pod"],
  },
  {
    id: "open_driver",
    label: "Open driver",
    examples: ["Open John Smith", "Open Driver Onkar Singh"],
    keywords: ["open driver", "show driver", "driver profile"],
  },
  {
    id: "open_load",
    label: "Open load",
    examples: ["Open load 24019", "Show load LD-24010"],
    keywords: ["open load", "show load", "load detail"],
  },
  {
    id: "open_broker",
    label: "Open broker",
    examples: ["Open broker ABC", "Find broker TQL"],
    keywords: ["open broker", "show broker", "broker profile"],
  },
  {
    id: "show_compliance",
    label: "Compliance",
    examples: ["Show compliance", "Open safety"],
    keywords: ["compliance", "safety", "dot"],
  },
  {
    id: "open_settings",
    label: "Settings",
    examples: ["Open settings", "Show company settings"],
    keywords: ["settings", "preferences", "configuration"],
  },
  {
    id: "show_fleet",
    label: "Fleet",
    examples: ["Show fleet", "Show trucks"],
    keywords: ["fleet", "trucks", "trailers"],
  },
  {
    id: "show_workforce",
    label: "Workforce",
    examples: ["Show workforce", "Open hiring", "Open recruiting"],
    keywords: ["workforce", "hiring", "recruiting", "recruitment"],
  },
  {
    id: "find_candidates",
    label: "Find candidates",
    examples: [
      "Find reefer drivers to hire",
      "Find flatbed candidates",
      "Find bilingual dispatchers",
    ],
    keywords: ["candidate", "candidates", "hire", "hiring", "talent"],
  },
  {
    id: "open_workforce_ai",
    label: "AI Recruiting",
    examples: ["Open AI recruiting", "Alph recruiter", "Rank applicants"],
    keywords: ["ai recruiting", "alph recruiter", "rank applicants"],
  },
  {
    id: "show_workforce_jobs",
    label: "Workforce jobs",
    examples: ["Show open jobs", "Show job postings", "Open hiring jobs"],
    keywords: ["job posting", "job postings", "open jobs", "workforce jobs"],
  },
  {
    id: "show_wallet",
    label: "Digital Professional Wallet",
    examples: ["Open wallet", "Show career passport", "Open professional wallet"],
    keywords: ["wallet", "career passport", "professional wallet", "digital wallet"],
  },
  {
    id: "open_wallet_passport",
    label: "Career Passport",
    examples: ["Open career passport", "Show passport timeline"],
    keywords: ["career passport", "passport timeline"],
  },
  {
    id: "open_wallet_ai",
    label: "Wallet AI Assistant",
    examples: ["Wallet AI", "Career coach", "Scan my CDL"],
    keywords: ["wallet ai", "career coach", "scan cdl", "replace medical"],
  },
  {
    id: "wallet_share",
    label: "Wallet sharing",
    examples: ["Share my CDL", "Create wallet share link", "Revoke wallet share"],
    keywords: ["share cdl", "wallet share", "share medical"],
  },
  {
    id: "show_network",
    label: "Verified Network",
    examples: ["Open Verified Network", "Show network", "Open Transpo Network"],
    keywords: ["network", "verified network", "transpo network"],
  },
  {
    id: "open_network_directory",
    label: "Network directory",
    examples: ["Open network directory", "Search verified mechanics"],
    keywords: ["network directory", "verified directory"],
  },
  {
    id: "open_network_ai",
    label: "AI Networking",
    examples: [
      "Find reefer mechanics nearby",
      "Find bilingual safety consultants",
      "Hazmat drivers available now",
    ],
    keywords: ["ai networking", "reefer mechanic", "safety consultant", "network alph"],
  },
  {
    id: "open_network_identity",
    label: "My Transpo ID",
    examples: ["Open my Transpo ID", "Show my network identity"],
    keywords: ["transpo id", "network identity", "verified id"],
  },
  {
    id: "open_platform",
    label: "Transpo Platform™",
    examples: ["Open Platform", "Show Transpo Platform", "Open the platform hub"],
    keywords: ["platform", "transpo platform", "ecosystem", "operating system"],
  },
  {
    id: "open_migration",
    label: "AI Migration Center",
    examples: ["Open Migration Center", "Show data migration", "Import my old TMS"],
    keywords: ["migration", "migrate", "import data", "migration center", "ai migration"],
  },
  {
    id: "start_import",
    label: "Start import",
    examples: ["Start import", "Start a migration", "Upload CSV to import"],
    keywords: ["start import", "start migration", "upload csv", "new import"],
  },
  {
    id: "open_app_store",
    label: "Transpo App Store™",
    examples: ["Open App Store", "Show partner apps", "Install an app"],
    keywords: ["app store", "apps", "partner apps", "install app"],
  },
  {
    id: "open_command_center",
    label: "Command Center",
    examples: ["Open Command Center", "Show executive board", "Business health"],
    keywords: ["command center", "executive", "business health"],
  },
  {
    id: "create_load",
    label: "Create a load",
    examples: ["Create a load", "New load", "Add a load"],
    keywords: ["create load", "new load", "add load"],
  },
  {
    id: "pay_invoice",
    label: "Pay invoice",
    examples: ["Pay invoice", "Pay an invoice", "Record payment"],
    keywords: ["pay invoice", "record payment", "pay bill"],
  },
  {
    id: "schedule_maintenance",
    label: "Schedule maintenance",
    examples: ["Schedule maintenance", "Book a service"],
    keywords: ["schedule maintenance", "book service"],
  },
  {
    id: "open_translation",
    label: "Global Translation",
    examples: ["Translate to Spanish", "Open translation", "Change language"],
    keywords: ["translate", "translation", "language", "spanish"],
  },
  {
    id: "open_security",
    label: "Enterprise Security",
    examples: ["Show security", "Open MFA settings", "Open audit log"],
    keywords: ["security", "mfa", "sso", "audit log"],
  },
  {
    id: "open_automation",
    label: "AI Automation",
    examples: ["Open automation", "Show recipes", "Automation center"],
    keywords: ["automation", "recipes", "automation center"],
  },
  {
    id: "open_exchange",
    label: "Transpo Exchange™",
    examples: ["Open Transpo Exchange", "Show exchange", "Freight exchange"],
    keywords: ["exchange", "transpo exchange", "freight exchange", "marketplace"],
  },
  {
    id: "open_exchange_ai",
    label: "AI Shopping",
    examples: ["Open AI Shopping", "Alph purchasing", "Exchange AI"],
    keywords: ["ai shopping", "alph purchasing", "exchange ai", "shopping assistant"],
  },
  {
    id: "exchange_shop",
    label: "Shop on Exchange",
    examples: [
      "Best reefer under $45k",
      "Used Cascadias within 300 miles",
      "OEM turbochargers",
      "Emergency tires nearby",
      "Recommend insurance",
      "Compare maintenance providers",
      "Compare three fuel cards",
    ],
    keywords: [
      "reefer",
      "cascadia",
      "fuel card",
      "turbo",
      "emergency tires",
      "insurance",
      "maintenance providers",
    ],
  },
  {
    id: "show_brokers",
    label: "Brokers",
    examples: ["Show brokers", "Open brokers"],
    keywords: ["brokers", "broker list"],
  },
  {
    id: "show_documents",
    label: "Documents",
    examples: ["Show documents", "Open document center"],
    keywords: ["documents", "document center", "files"],
  },
  {
    id: "show_finance",
    label: "Finance",
    examples: ["Show finance", "Open cash flow"],
    keywords: ["finance", "cash flow", "revenue"],
  },
  {
    id: "show_analytics",
    label: "Reports",
    examples: ["Show reports", "Open analytics"],
    keywords: ["analytics", "reports", "report"],
  },
  {
    id: "open_truck",
    label: "Open truck",
    examples: ["Find Truck 105", "Open truck 102", "Show truck 104"],
    keywords: ["open truck", "find truck", "show truck", "truck unit"],
  },
  {
    id: "morning_briefing",
    label: "Morning briefing",
    examples: ["Morning briefing", "What needs attention?"],
    keywords: ["briefing", "what needs attention", "priorities", "summary"],
  },
  {
    id: "eld_is_supported",
    label: "Is my ELD supported?",
    examples: ["Is my ELD supported?", "Is Samsara supported?", "Is Motive supported?"],
    keywords: ["eld supported", "is my eld", "eld support"],
  },
  {
    id: "eld_why_not_connected",
    label: "Why is my ELD not connected?",
    examples: [
      "Why is my ELD not connected?",
      "Why is Omnitracs not connected?",
    ],
    keywords: ["eld not connected", "why not connected", "eld disconnected"],
  },
  {
    id: "eld_what_to_ask",
    label: "What should I ask my ELD provider?",
    examples: [
      "What should I ask my ELD provider?",
      "What should I ask Verizon Connect?",
    ],
    keywords: ["ask my eld", "ask eld provider", "eld email"],
  },
  {
    id: "eld_request_reviewed",
    label: "Has my ELD request been reviewed?",
    examples: [
      "Has my connection request been reviewed?",
      "ELD request status",
    ],
    keywords: ["eld request", "connection request reviewed", "eld reviewed"],
  },
  {
    id: "eld_which_support_data",
    label: "Which ELDs support GPS / IFTA?",
    examples: [
      "Which ELDs support live GPS?",
      "Which ELDs support IFTA mileage?",
    ],
    keywords: ["eld support gps", "eld ifta", "which elds support"],
  },
  {
    id: "eld_when_available",
    label: "When will my ELD be available?",
    examples: [
      "When will my ELD be available?",
      "When will ABC ELD be available?",
    ],
    keywords: ["eld available", "when will my eld", "eld availability"],
  },
  {
    id: "support_help",
    label: "Support help",
    examples: [
      "Why is this not working?",
      "Fix this problem",
      "Why did my invoice fail?",
      "Why can’t I upload this document?",
      "What information is missing?",
    ],
    keywords: [
      "not working",
      "fix this",
      "invoice fail",
      "upload",
      "missing",
      "why is",
      "what information",
    ],
  },
  {
    id: "support_setup",
    label: "Company setup help",
    examples: ["Help me finish company setup", "Open company setup"],
    keywords: ["company setup", "finish setup", "onboarding", "setup progress"],
  },
  {
    id: "support_issue_status",
    label: "Issue status",
    examples: [
      "Has my issue been resolved?",
      "What did CarrierOS change?",
      "Can I reopen my issue?",
    ],
    keywords: ["issue resolved", "reopen", "what did carrieros change", "ticket"],
  },
  {
    id: "open_dispatch",
    label: "Open Dispatch",
    examples: ["Open Dispatch", "Show dispatch board"],
    keywords: ["dispatch", "dispatch board", "open dispatch"],
  },
  {
    id: "assign_driver",
    label: "Assign driver",
    examples: ["Assign Driver John", "Assign a driver"],
    keywords: ["assign driver", "assign john"],
  },
  {
    id: "show_cash_flow",
    label: "Cash flow",
    examples: ["Show My Cash Flow", "Cash flow"],
    keywords: ["cash flow", "cashflow"],
  },
  {
    id: "who_owes_money",
    label: "Who owes money",
    examples: ["Who Owes Me Money", "Who owes me"],
    keywords: ["owes me", "who owes", "receivables"],
  },
  {
    id: "show_expiring",
    label: "Expiring docs",
    examples: [
      "Show Expiring Permits",
      "Show Expiring Insurance",
      "Show expiring medical",
    ],
    keywords: ["expiring", "expire", "permits", "insurance"],
  },
  {
    id: "why_profit_down",
    label: "Why is profit down",
    examples: ["Why Is Profit Down", "Why is profit low"],
    keywords: ["profit down", "why profit", "profit low"],
  },
  {
    id: "why_fleet_health",
    label: "Why is fleet health low",
    examples: ["Why is Fleet Health Low?", "Fleet health"],
    keywords: ["fleet health", "why is fleet"],
  },
  {
    id: "driver_performance",
    label: "Driver performance",
    examples: ["Show Driver Performance", "Driver performance"],
    keywords: ["driver performance", "performance"],
  },
  {
    id: "show_maintenance_due",
    label: "Maintenance due",
    examples: ["Show Maintenance Due", "Create Maintenance Ticket"],
    keywords: ["maintenance due", "maintenance ticket", "pm due"],
  },
  {
    id: "upload_pod",
    label: "Upload POD",
    examples: ["Upload POD", "Upload proof of delivery"],
    keywords: ["upload pod", "proof of delivery"],
  },
  {
    id: "open_alph_copilot",
    label: "Alph Copilot™",
    examples: ["Open Alph Copilot", "Open Copilot", "Show Alph Copilot"],
    keywords: ["alph copilot", "copilot", "ai employee"],
  },
  {
    id: "open_driver_alph",
    label: "Driver Alph",
    examples: ["Open Driver Alph", "Driver Copilot"],
    keywords: ["driver alph", "driver copilot"],
  },
  {
    id: "open_dispatcher_alph",
    label: "Dispatcher Alph",
    examples: ["Open Dispatcher Alph", "Dispatcher Copilot"],
    keywords: ["dispatcher alph", "dispatcher copilot"],
  },
  {
    id: "open_safety_alph",
    label: "Safety Alph",
    examples: ["Open Safety Alph", "Safety Copilot"],
    keywords: ["safety alph", "safety copilot"],
  },
  {
    id: "open_maintenance_alph",
    label: "Maintenance Alph",
    examples: ["Open Maintenance Alph", "Maintenance Copilot"],
    keywords: ["maintenance alph", "maintenance copilot"],
  },
  {
    id: "open_accounting_alph",
    label: "Accounting Alph",
    examples: ["Open Accounting Alph", "Accounting Copilot"],
    keywords: ["accounting alph", "accounting copilot"],
  },
  {
    id: "open_owner_alph",
    label: "Owner Alph",
    examples: ["Open Owner Alph", "Owner Copilot"],
    keywords: ["owner alph", "owner copilot"],
  },
  {
    id: "assign_best_driver",
    label: "Assign best driver",
    examples: ["Assign best driver", "Suggest best driver"],
    keywords: ["assign best", "best driver", "suggest driver"],
  },
  {
    id: "find_reload",
    label: "Find reload",
    examples: ["Find reload", "Find backhaul"],
    keywords: ["reload", "backhaul", "return load"],
  },
  {
    id: "handle_payroll",
    label: "Handle payroll",
    examples: ["Handle payroll", "Prepare payroll"],
    keywords: ["handle payroll", "prepare payroll"],
  },
  {
    id: "show_todays_profit",
    label: "Today's profit",
    examples: ["Show today's profit", "Today's profit"],
    keywords: ["today's profit", "todays profit", "show profit"],
  },
  {
    id: "find_truck_wash",
    label: "Find truck wash",
    examples: ["Find nearest truck wash", "Truck wash nearby"],
    keywords: ["truck wash", "nearest wash", "wash"],
  },
];

export function getIntentDefinition(
  id: AlphIntentId,
): AlphIntentDefinition | undefined {
  return ALPH_INTENT_CATALOG.find((intent) => intent.id === id);
}
