import { DEFAULT_NOTIFICATION_PREFERENCES } from "@/lib/types/notifications";
import { activeCompany } from "@/lib/data/tenant";
import type { CarrierSettingsState } from "@/lib/settings/types";

const now = "2026-07-17T12:00:00.000Z";

export function createDefaultSettings(): CarrierSettingsState {
  return {
    company: {
      name: activeCompany.name,
      mcNumber: activeCompany.mcNumber ?? "MC-927451",
      dotNumber: activeCompany.dotNumber ?? "USDOT-3482910",
      addressLine1: "1840 Commerce Center Blvd",
      addressLine2: "Suite 200",
      city: "San Antonio",
      state: "TX",
      postalCode: "78218",
      country: "US",
      logoDataUrl: null,
      timezone: activeCompany.timezone ?? "America/Chicago",
      distanceUnit: "miles",
      temperatureUnit: "f",
      weightUnit: "lb",
    },
    users: [
      {
        id: "alpha-owner",
        name: "Alpha Owner",
        email: "owner@lonestar-alpha.com",
        title: "Owner",
        roleId: "owner",
        status: "active",
        lastActiveAt: "2026-07-17T11:40:00.000Z",
      },
      {
        id: "user-dispatch-1",
        name: "Jordan Lee",
        email: "jordan@lonestar-alpha.com",
        title: "Lead Dispatcher",
        roleId: "dispatcher",
        status: "active",
        lastActiveAt: "2026-07-17T10:15:00.000Z",
      },
      {
        id: "user-acct-1",
        name: "Priya Shah",
        email: "priya@lonestar-alpha.com",
        title: "Controller",
        roleId: "accounting",
        status: "active",
        lastActiveAt: "2026-07-16T16:20:00.000Z",
      },
      {
        id: "user-safety-1",
        name: "Marcus Reed",
        email: "marcus@lonestar-alpha.com",
        title: "Safety Manager",
        roleId: "safety",
        status: "invited",
        invitedAt: "2026-07-15T14:00:00.000Z",
      },
    ],
    billing: {
      billingEmail: "billing@lonestar-alpha.com",
      cardBrand: "Visa",
      cardLast4: "4242",
      cardExpMonth: 9,
      cardExpYear: 2028,
      invoices: [
        {
          id: "inv-cos-2026-07",
          date: "2026-07-01",
          amount: 499,
          status: "paid",
          description: "Growth plan — July 2026",
        },
        {
          id: "inv-cos-2026-06",
          date: "2026-06-01",
          amount: 499,
          status: "paid",
          description: "Growth plan — June 2026",
        },
        {
          id: "inv-cos-2026-05",
          date: "2026-05-01",
          amount: 299,
          status: "paid",
          description: "Starter plan — May 2026",
        },
      ],
    },
    subscription: {
      plan: "growth",
      seats: 15,
      seatsUsed: 8,
      renewsAt: "2026-08-01",
      features: [
        "Live dispatch board",
        "Document center + OCR",
        "Finance & factoring",
        "Compliance tracking",
        "Workflows automation",
        "Customer portal",
      ],
    },
    notifications: { ...DEFAULT_NOTIFICATION_PREFERENCES },
    branding: {
      logoDataUrl: null,
      primaryColor: "#2563EB",
      emailFooter:
        "Lone Star Alpha Carrier · MC-927451 · Questions? reply to this email or call (210) 555-0180.",
    },
    emailTemplates: [
      {
        id: "invoice",
        name: "Invoice",
        subject: "Invoice {{invoice_number}} from {{company_name}}",
        body: "Hi {{broker_name}},\n\nPlease find invoice {{invoice_number}} for load {{load_ref}} totaling {{amount}}.\n\nPayment is due by {{due_date}}.\n\nThank you,\n{{company_name}}",
        updatedAt: now,
      },
      {
        id: "rate_con",
        name: "Rate confirmation",
        subject: "Rate confirmation — {{load_ref}}",
        body: "Hi {{broker_name}},\n\nAttached is the signed rate confirmation for {{origin}} → {{destination}} at {{rate}}.\n\nDriver: {{driver_name}}\nPickup: {{pickup_window}}\n\n{{company_name}}",
        updatedAt: now,
      },
      {
        id: "pod_request",
        name: "POD request",
        subject: "POD needed for {{load_ref}}",
        body: "Hi {{driver_name}},\n\nPlease upload proof of delivery for load {{load_ref}} as soon as possible so we can invoice.\n\nThanks,\nDispatch",
        updatedAt: now,
      },
      {
        id: "payment_reminder",
        name: "Payment reminder",
        subject: "Reminder: Invoice {{invoice_number}} is due",
        body: "Hi {{broker_name}},\n\nThis is a friendly reminder that invoice {{invoice_number}} for {{amount}} is due on {{due_date}}.\n\nReply if you need a copy resent.\n\n{{company_name}} Accounting",
        updatedAt: now,
      },
    ],
    smsTemplates: [
      {
        id: "check_call",
        name: "Check call",
        body: "Transpo.ai check call: Where are you on load {{load_ref}}? Reply with city/state and ETA.",
        updatedAt: now,
      },
      {
        id: "pod_request",
        name: "POD request",
        body: "Please upload POD for {{load_ref}} in the driver app when empty. Thanks — {{company_name}}",
        updatedAt: now,
      },
      {
        id: "appointment_reminder",
        name: "Appointment reminder",
        body: "Reminder: {{stop_type}} appointment at {{facility}} on {{appointment_time}}. Load {{load_ref}}.",
        updatedAt: now,
      },
    ],
    invoiceTemplate: {
      showLogo: true,
      showCompanyAddress: true,
      showPaymentTerms: true,
      showBankDetails: false,
      terms: "Net 30. Late payments may incur 1.5% monthly interest.",
      footerNote: "Thank you for your business.",
      layout: "modern",
    },
    documentTemplates: {
      defaultNamingPattern: "{{load_ref}}_{{doc_type}}_{{date}}",
      packets: [
        {
          id: "pkt-delivery",
          name: "Delivery packet",
          items: ["Rate confirmation", "BOL", "POD", "Lumper receipt"],
          namingPattern: "{{load_ref}}_delivery_{{date}}",
        },
        {
          id: "pkt-invoice",
          name: "Invoice packet",
          items: ["Invoice", "Rate confirmation", "POD", "Accessorials"],
          namingPattern: "{{invoice_number}}_packet",
        },
        {
          id: "pkt-onboarding",
          name: "Driver onboarding",
          items: ["CDL", "Medical card", "MVR", "Application"],
          namingPattern: "{{driver_name}}_onboarding",
        },
      ],
    },
    apiKeys: [
      {
        id: "key-1",
        name: "Dispatch integrations",
        prefix: "cos",
        lastFour: "a91c",
        createdAt: "2026-06-12T10:00:00.000Z",
        lastUsedAt: "2026-07-16T22:10:00.000Z",
        revokedAt: null,
      },
      {
        id: "key-2",
        name: "Accounting sync",
        prefix: "cos",
        lastFour: "7f2e",
        createdAt: "2026-05-01T09:00:00.000Z",
        lastUsedAt: null,
        revokedAt: null,
      },
    ],
    integrations: [
      { providerId: "quickbooks", status: "disconnected" },
      { providerId: "xero", status: "disconnected" },
      {
        providerId: "stripe",
        status: "connected",
        connectedAt: "2026-04-10T12:00:00.000Z",
        lastSyncAt: "2026-07-17T08:00:00.000Z",
      },
      { providerId: "plaid", status: "disconnected" },
      {
        providerId: "twilio",
        status: "connected",
        connectedAt: "2026-03-01T12:00:00.000Z",
        lastSyncAt: "2026-07-17T11:00:00.000Z",
      },
      { providerId: "samsara", status: "disconnected" },
      { providerId: "motive", status: "disconnected" },
      { providerId: "geotab", status: "disconnected" },
      {
        providerId: "fmcsa",
        status: "error",
        note: "Credentials not configured for live pull.",
      },
    ],
    backup: {
      lastBackupAt: "2026-07-16T03:00:00.000Z",
      schedule: "daily",
      includeDocuments: false,
    },
    security: {
      require2fa: true,
      sessionTimeoutMinutes: 60,
      minPasswordLength: 12,
      requireSpecialChar: true,
      requireNumber: true,
      ipAllowlistEnabled: false,
      ipAllowlist: [],
    },
    auditLog: [
      {
        id: "aud-1",
        timestamp: "2026-07-17T11:05:00.000Z",
        actorName: "Alpha Owner",
        action: "updated",
        resource: "company",
        details: "Updated company timezone to America/Chicago",
        ip: "198.51.100.24",
      },
      {
        id: "aud-2",
        timestamp: "2026-07-16T15:40:00.000Z",
        actorName: "Alpha Owner",
        action: "invited",
        resource: "users",
        details: "Invited Marcus Reed as Safety",
        ip: "198.51.100.24",
      },
      {
        id: "aud-3",
        timestamp: "2026-07-15T09:12:00.000Z",
        actorName: "Priya Shah",
        action: "updated",
        resource: "billing",
        details: "Changed billing email",
        ip: "203.0.113.10",
      },
      {
        id: "aud-4",
        timestamp: "2026-07-14T18:22:00.000Z",
        actorName: "Alpha Owner",
        action: "created",
        resource: "api-keys",
        details: "Created API key “Dispatch integrations”",
        ip: "198.51.100.24",
      },
      {
        id: "aud-5",
        timestamp: "2026-07-12T11:00:00.000Z",
        actorName: "Jordan Lee",
        action: "updated",
        resource: "notifications",
        details: "Disabled SMS channel",
        ip: "198.51.100.40",
      },
    ],
    workflowSummaries: [
      {
        id: "wf-pod-invoice",
        name: "POD → create invoice",
        enabled: true,
        triggerLabel: "POD uploaded",
        lastRunAt: "2026-07-17T09:40:00.000Z",
      },
      {
        id: "wf-delivery-notify",
        name: "Delivery → notify accounting",
        enabled: true,
        triggerLabel: "Delivery completed",
        lastRunAt: "2026-07-16T21:10:00.000Z",
      },
      {
        id: "wf-medical",
        name: "Medical expiring → notify safety",
        enabled: false,
        triggerLabel: "Driver medical expiring",
      },
      {
        id: "wf-overdue",
        name: "Overdue invoice reminder",
        enabled: true,
        triggerLabel: "Invoice overdue",
        lastRunAt: "2026-07-15T08:00:00.000Z",
      },
    ],
    updatedAt: now,
  };
}
