import type {
  PortalCompany,
  PortalDocument,
  PortalLoadRequest,
  PortalMessageThread,
  PortalNotification,
  PortalUser,
} from "@/lib/portal/types";

export const DEMO_PORTAL_PASSWORD = "demo1234";
export const DEMO_2FA_CODE = "123456";

export const portalCompanies: PortalCompany[] = [
  {
    id: "portal-co-freightline",
    name: "FreightLine Logistics",
    type: "broker",
    linkedBrokerId: "broker-freightline",
    directoryCompanyId: "company-freightline",
    email: "ops@freightline.com",
    phone: "(713) 555-0144",
    website: "https://freightline.com",
    billingAddress: {
      street: "1200 Commerce St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    preferredRequirements: [
      "Dry van preferred",
      "GPS tracking required",
      "POD within 2 hours of delivery",
    ],
  },
  {
    id: "portal-co-retailhub",
    name: "Retail Distribution Hub",
    type: "shipper",
    linkedCustomerId: "customer-retail-hub",
    directoryCompanyId: "company-retail-hub",
    email: "shipping@retaildistro.com",
    phone: "(832) 555-0410",
    website: "https://retaildistro.com",
    billingAddress: {
      street: "8800 Westpark Dr",
      city: "Houston",
      state: "TX",
      zip: "77063",
    },
    preferredRequirements: [
      "Appointment required at dock",
      "Liftgate preferred on LTL",
      "Temp control on produce lanes",
    ],
  },
];

export const portalUsers: PortalUser[] = [
  {
    id: "portal-user-fl-admin",
    companyId: "portal-co-freightline",
    email: "broker@freightline.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Alex Rivera",
    role: "company_admin",
    phone: "(713) 555-0140",
    title: "Operations Director",
    active: true,
  },
  {
    id: "portal-user-fl-dispatch",
    companyId: "portal-co-freightline",
    email: "dispatch@freightline.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "James Kline",
    role: "dispatcher",
    phone: "(713) 555-0144",
    title: "Senior Dispatcher",
    active: true,
  },
  {
    id: "portal-user-fl-accounting",
    companyId: "portal-co-freightline",
    email: "ap@freightline.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Priya Patel",
    role: "accounting",
    phone: "(713) 555-0155",
    title: "AP Manager",
    active: true,
  },
  {
    id: "portal-user-fl-readonly",
    companyId: "portal-co-freightline",
    email: "viewer@freightline.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Sam Chen",
    role: "read_only",
    title: "Compliance Viewer",
    active: true,
  },
  {
    id: "portal-user-rh-shipping",
    companyId: "portal-co-retailhub",
    email: "shipping@retailhub.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Amanda Cole",
    role: "dispatcher",
    phone: "(832) 555-0410",
    title: "Shipping Manager",
    active: true,
  },
  {
    id: "portal-user-rh-admin",
    companyId: "portal-co-retailhub",
    email: "admin@retailhub.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Sarah Nguyen",
    role: "company_admin",
    phone: "(832) 555-0412",
    title: "Operations Manager",
    active: true,
  },
  {
    id: "portal-user-rh-receiving",
    companyId: "portal-co-retailhub",
    email: "receiving@retailhub.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Luis Mendez",
    role: "receiving",
    phone: "(832) 555-0411",
    title: "Dock Lead",
    active: true,
  },
  {
    id: "portal-user-rh-readonly",
    companyId: "portal-co-retailhub",
    email: "viewer@retailhub.com",
    password: DEMO_PORTAL_PASSWORD,
    name: "Jordan Lee",
    role: "read_only",
    title: "Read Only",
    active: true,
  },
];

export const portalLoadRequestsSeed: PortalLoadRequest[] = [
  {
    id: "plr-001",
    companyId: "portal-co-freightline",
    createdByUserId: "portal-user-fl-dispatch",
    reference: "REQ-8841",
    status: "submitted",
    originCity: "Houston",
    originState: "TX",
    destinationCity: "Atlanta",
    destinationState: "GA",
    pickupDate: "2026-07-20",
    deliveryDate: "2026-07-22",
    commodity: "Retail freight",
    equipmentType: "Dry Van",
    weight: 42000,
    pieces: 24,
    notes: "Need team driver preferred on this lane.",
    createdAt: "2026-07-16T14:20:00.000Z",
    updatedAt: "2026-07-16T14:20:00.000Z",
  },
  {
    id: "plr-002",
    companyId: "portal-co-retailhub",
    createdByUserId: "portal-user-rh-shipping",
    reference: "REQ-2207",
    status: "accepted",
    originCity: "Houston",
    originState: "TX",
    destinationCity: "Dallas",
    destinationState: "TX",
    pickupDate: "2026-07-18",
    deliveryDate: "2026-07-18",
    commodity: "Dry goods",
    equipmentType: "Dry Van",
    weight: 28000,
    linkedLoadId: "load-24001",
    rate: 950,
    createdAt: "2026-07-15T09:00:00.000Z",
    updatedAt: "2026-07-15T11:30:00.000Z",
  },
];

export const portalDocumentsSeed: PortalDocument[] = [
  {
    id: "pdoc-001",
    companyId: "portal-co-freightline",
    loadReference: "LD-24001",
    kind: "rate_con",
    name: "Rate Confirmation LD-24001.pdf",
    status: "available",
    uploadedAt: "2026-07-02T14:10:00.000Z",
    sizeLabel: "184 KB",
  },
  {
    id: "pdoc-002",
    companyId: "portal-co-freightline",
    loadReference: "LD-24005",
    kind: "pod",
    name: "POD LD-24005.pdf",
    status: "available",
    uploadedAt: "2026-07-10T18:40:00.000Z",
    sizeLabel: "312 KB",
  },
  {
    id: "pdoc-003",
    companyId: "portal-co-freightline",
    loadReference: "LD-24005",
    kind: "invoice",
    name: "Invoice INV-24005.pdf",
    status: "awaiting_review",
    uploadedAt: "2026-07-11T09:00:00.000Z",
    sizeLabel: "96 KB",
  },
  {
    id: "pdoc-004",
    companyId: "portal-co-retailhub",
    loadReference: "LD-24001",
    kind: "bol",
    name: "BOL LD-24001.pdf",
    status: "available",
    uploadedAt: "2026-07-03T08:30:00.000Z",
    sizeLabel: "220 KB",
  },
  {
    id: "pdoc-005",
    companyId: "portal-co-retailhub",
    loadReference: "LD-24001",
    kind: "photo",
    name: "Pickup photos LD-24001.zip",
    status: "uploaded",
    uploadedAt: "2026-07-03T09:15:00.000Z",
    sizeLabel: "4.2 MB",
  },
];

export const portalNotificationsSeed: PortalNotification[] = [
  {
    id: "pnotif-001",
    companyId: "portal-co-freightline",
    kind: "driver_assigned",
    title: "Driver assigned",
    body: "Onkar Singh was assigned to LD-24002.",
    loadReference: "LD-24002",
    createdAt: "2026-07-16T16:00:00.000Z",
    read: false,
  },
  {
    id: "pnotif-002",
    companyId: "portal-co-freightline",
    kind: "invoice_ready",
    title: "Invoice ready",
    body: "Invoice for LD-24005 is ready to download.",
    loadReference: "LD-24005",
    createdAt: "2026-07-15T11:20:00.000Z",
    read: false,
  },
  {
    id: "pnotif-003",
    companyId: "portal-co-freightline",
    kind: "payment_received",
    title: "Payment received",
    body: "$2,850 payment posted for INV-FIN-001.",
    createdAt: "2026-07-14T14:00:00.000Z",
    read: true,
  },
  {
    id: "pnotif-004",
    companyId: "portal-co-retailhub",
    kind: "pickup_complete",
    title: "Pickup complete",
    body: "LD-24001 was picked up in Dallas, TX.",
    loadReference: "LD-24001",
    createdAt: "2026-07-16T10:30:00.000Z",
    read: false,
  },
  {
    id: "pnotif-005",
    companyId: "portal-co-retailhub",
    kind: "pod_uploaded",
    title: "POD uploaded",
    body: "Proof of delivery is available for review.",
    loadReference: "LD-24005",
    createdAt: "2026-07-15T19:00:00.000Z",
    read: true,
  },
];

export const portalThreadsSeed: PortalMessageThread[] = [
  {
    id: "pthread-fl-dispatch",
    companyId: "portal-co-freightline",
    department: "dispatch",
    subject: "LD-24001 assignment update",
    unread: 1,
    updatedAt: "2026-07-16T15:40:00.000Z",
    messages: [
      {
        id: "pmsg-1",
        threadId: "pthread-fl-dispatch",
        sender: "portal",
        senderName: "James Kline",
        body: "Can we get an ETA update on LD-24001?",
        sentAt: "2026-07-16T14:00:00.000Z",
      },
      {
        id: "pmsg-2",
        threadId: "pthread-fl-dispatch",
        sender: "carrier",
        senderName: "Lone Star Dispatch",
        body: "Driver is 42 miles out. ETA 4:15 PM local.",
        sentAt: "2026-07-16T15:40:00.000Z",
      },
    ],
  },
  {
    id: "pthread-fl-billing",
    companyId: "portal-co-freightline",
    department: "billing",
    subject: "Invoice INV-FIN-002 clarification",
    unread: 0,
    updatedAt: "2026-07-14T12:00:00.000Z",
    messages: [
      {
        id: "pmsg-3",
        threadId: "pthread-fl-billing",
        sender: "portal",
        senderName: "Priya Patel",
        body: "Please confirm detention line item on INV-FIN-002.",
        sentAt: "2026-07-14T11:00:00.000Z",
      },
      {
        id: "pmsg-4",
        threadId: "pthread-fl-billing",
        sender: "carrier",
        senderName: "Lone Star Billing",
        body: "Confirmed — 2.5 hours detention at $75/hr. Revised PDF attached.",
        sentAt: "2026-07-14T12:00:00.000Z",
      },
    ],
  },
  {
    id: "pthread-rh-dispatch",
    companyId: "portal-co-retailhub",
    department: "dispatch",
    subject: "Tomorrow pickup appointment",
    unread: 2,
    updatedAt: "2026-07-16T17:10:00.000Z",
    messages: [
      {
        id: "pmsg-5",
        threadId: "pthread-rh-dispatch",
        sender: "carrier",
        senderName: "Lone Star Dispatch",
        body: "Can we move pickup to 10:00 AM tomorrow?",
        sentAt: "2026-07-16T16:50:00.000Z",
      },
      {
        id: "pmsg-6",
        threadId: "pthread-rh-dispatch",
        sender: "carrier",
        senderName: "Lone Star Dispatch",
        body: "Dock 4 is available if that works.",
        sentAt: "2026-07-16T17:10:00.000Z",
      },
    ],
  },
  {
    id: "pthread-rh-safety",
    companyId: "portal-co-retailhub",
    department: "safety",
    subject: "Seal verification on outbound",
    unread: 0,
    updatedAt: "2026-07-12T09:30:00.000Z",
    messages: [
      {
        id: "pmsg-7",
        threadId: "pthread-rh-safety",
        sender: "portal",
        senderName: "Amanda Cole",
        body: "Please verify seal number before departure.",
        sentAt: "2026-07-12T09:00:00.000Z",
      },
      {
        id: "pmsg-8",
        threadId: "pthread-rh-safety",
        sender: "carrier",
        senderName: "Lone Star Safety",
        body: "Seal FL-99201 verified and photographed.",
        sentAt: "2026-07-12T09:30:00.000Z",
      },
    ],
  },
];

export function getPortalCompanyById(id: string): PortalCompany | undefined {
  return portalCompanies.find((c) => c.id === id);
}

export function getPortalUserByEmail(email: string): PortalUser | undefined {
  return portalUsers.find(
    (u) => u.email.toLowerCase() === email.trim().toLowerCase() && u.active,
  );
}

export function getPortalUsersForCompany(companyId: string): PortalUser[] {
  return portalUsers.filter((u) => u.companyId === companyId && u.active);
}
