import "server-only";
import { getSupabaseAuthenticatedUserClient } from "@/lib/supabase/server";
export type PayRate={id:string;driverUserId:string;displayName:string;centsPerMile:number;effectiveOn:string;endedOn?:string;verifiedAt:string};
export type PayrollCandidate={loadId:string;loadNumber:string;driverUserId:string;displayName:string;verifiedMiles:number;centsPerMile:number;mileagePayCents:number;closedAt:string};
export type DriverSettlement={id:string;driverUserId:string;displayName:string;periodStart:string;periodEnd:string;totalMiles:number;mileagePayCents:number;extrasCents:number;deductionsCents:number;netPayCents:number;status:"approved"|"paid";approvedAt:string;paidAt?:string;paymentReference?:string;loadCount:number};
export type PayrollWorkspace={rates:PayRate[];candidates:PayrollCandidate[];settlements:DriverSettlement[]};
type Row=Record<string,unknown>;const text=(v:unknown)=>typeof v==="string"?v:"";const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
export class PayrollRepository{async workspace(accessToken:string):Promise<PayrollWorkspace>{const db=getSupabaseAuthenticatedUserClient(accessToken);const[ratesResult,candidatesResult,settlementsResult]=await Promise.all([db.rpc("list_verified_driver_pay_rates"),db.rpc("list_unsettled_payroll_loads"),db.rpc("list_verified_driver_settlements")]);if(settlementsResult.error)throw new Error("Authorized payroll records are unavailable.");const rows=(value:unknown)=>Array.isArray(value)?value:[];
  const rates=ratesResult.error?[]:rows(ratesResult.data).flatMap((v):PayRate[]=>{if(!v||typeof v!=="object")return[];const r=v as Row,id=text(r.rate_id);return id?[{id,driverUserId:text(r.driver_user_id),displayName:text(r.display_name)||"Verified driver",centsPerMile:num(r.cents_per_mile),effectiveOn:text(r.effective_on),endedOn:text(r.ended_on)||undefined,verifiedAt:text(r.verified_at)}]:[]});
  const candidates=candidatesResult.error?[]:rows(candidatesResult.data).flatMap((v):PayrollCandidate[]=>{if(!v||typeof v!=="object")return[];const r=v as Row,id=text(r.load_id);return id?[{loadId:id,loadNumber:text(r.load_number),driverUserId:text(r.driver_user_id),displayName:text(r.display_name)||"Verified driver",verifiedMiles:num(r.verified_miles),centsPerMile:num(r.cents_per_mile),mileagePayCents:num(r.mileage_pay_cents),closedAt:text(r.closed_at)}]:[]});
  const settlements=rows(settlementsResult.data).flatMap((v):DriverSettlement[]=>{if(!v||typeof v!=="object")return[];const r=v as Row,id=text(r.settlement_id),status=text(r.status);if(!id||(status!=="approved"&&status!=="paid"))return[];return[{id,driverUserId:text(r.driver_user_id),displayName:text(r.display_name)||"Verified driver",periodStart:text(r.period_start),periodEnd:text(r.period_end),totalMiles:num(r.total_miles),mileagePayCents:num(r.mileage_pay_cents),extrasCents:num(r.extras_cents),deductionsCents:num(r.deductions_cents),netPayCents:num(r.net_pay_cents),status,approvedAt:text(r.approved_at),paidAt:text(r.paid_at)||undefined,paymentReference:text(r.payment_reference)||undefined,loadCount:num(r.load_count)}]});return{rates,candidates,settlements};}}
