import type { CorePlatformModule, EcosystemNode } from "@/lib/platform/types";

/**
 * Core ops map — deep-links to existing modules when live.
 * "coming" entries stay calm with a CTA; never invent broken rebuilds.
 */
export const CORE_PLATFORM_MODULES: CorePlatformModule[] = [
  {
    id: "fleet",
    title: "Fleet",
    description: "Trucks, trailers, and utilization.",
    href: "/fleet",
    status: "live",
    group: "ops",
  },
  {
    id: "dispatch",
    title: "Dispatch",
    description: "Loads, assignment, and tracking.",
    href: "/loads",
    status: "live",
    group: "ops",
  },
  {
    id: "brokers",
    title: "Brokers",
    description: "Broker roster and performance.",
    href: "/brokers",
    status: "live",
    group: "ops",
  },
  {
    id: "portal",
    title: "Shipper Portal",
    description: "Customer self-serve loads and invoices.",
    href: "/portal",
    status: "live",
    group: "ops",
  },
  {
    id: "driver",
    title: "Driver Mobile",
    description: "Driver app for assigned loads.",
    href: "/driver",
    status: "live",
    group: "people",
  },
  {
    id: "finance",
    title: "Accounting / Finance",
    description: "Revenue, invoices, and cash flow.",
    href: "/finance",
    status: "live",
    group: "money",
  },
  {
    id: "payroll",
    title: "Payroll",
    description: "Driver settlements and pay runs.",
    href: "/payroll",
    status: "live",
    group: "money",
  },
  {
    id: "fuel",
    title: "Fuel / IFTA",
    description: "Fuel tax and mileage imports.",
    href: "/ifta",
    status: "live",
    group: "money",
  },
  {
    id: "maintenance",
    title: "Maintenance",
    description: "PM schedules and work orders.",
    href: "/fleet/maintenance",
    status: "live",
    group: "ops",
  },
  {
    id: "safety",
    title: "Safety",
    description: "Safety and compliance attention.",
    href: "/compliance",
    status: "live",
    group: "safety",
  },
  {
    id: "compliance",
    title: "Compliance",
    description: "CDL, medical, insurance, and audits.",
    href: "/compliance",
    status: "live",
    group: "safety",
  },
  {
    id: "eld",
    title: "ELD",
    description: "ELD directory and connection health.",
    href: "/integrations/eld",
    status: "live",
    group: "ops",
  },
  {
    id: "alph",
    title: "Alph",
    description: "AI command center for the operation.",
    href: "/alph",
    status: "live",
    group: "intelligence",
  },
  {
    id: "documents",
    title: "Documents",
    description: "PODs, rate cons, and packets.",
    href: "/documents",
    status: "live",
    group: "ops",
  },
  {
    id: "reporting",
    title: "Reporting",
    description: "Analytics and executive reports.",
    href: "/analytics",
    status: "live",
    group: "intelligence",
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "Trends across fleet and finance.",
    href: "/analytics",
    status: "live",
    group: "intelligence",
  },
  {
    id: "workforce",
    title: "Transpo Workforce™",
    description: "Hiring, onboarding, and talent.",
    href: "/workforce",
    status: "live",
    group: "people",
  },
  {
    id: "wallet",
    title: "Digital Wallet",
    description: "Identity, documents, and sharing.",
    href: "/wallet",
    status: "live",
    group: "people",
  },
  {
    id: "network",
    title: "Transpo Verified Network™",
    description: "Professionals, trust, and connections.",
    href: "/network",
    status: "live",
    group: "people",
  },
  {
    id: "exchange",
    title: "Transpo Exchange™",
    description: "B2B trucking commerce — buy, sell, rent, hire.",
    href: "/exchange",
    status: "live",
    group: "ops",
  },
];

export const ECOSYSTEM_NODES: EcosystemNode[] = [
  {
    id: "core",
    title: "Core operations",
    description: "Fleet, dispatch, finance, compliance, documents.",
    href: "/platform",
    status: "live",
  },
  {
    id: "exchange",
    title: "Transpo Exchange™",
    description: "Equipment, parts, services, freight, and more.",
    href: "/exchange",
    status: "live",
    brand: "Transpo Exchange™",
  },
  {
    id: "network",
    title: "Transpo Verified Network™",
    description: "Trusted people and companies.",
    href: "/network",
    status: "live",
    brand: "Transpo Verified Network™",
  },
  {
    id: "workforce",
    title: "Transpo Workforce™",
    description: "Hiring command center.",
    href: "/workforce",
    status: "live",
    brand: "Transpo Workforce™",
  },
  {
    id: "apps",
    title: "Transpo App Store™",
    description: "Partner apps with scoped permissions.",
    href: "/platform/apps",
    status: "live",
    brand: "Transpo App Store™",
  },
  {
    id: "partners",
    title: "Partner Center",
    description: "Levels, leads, and certification.",
    href: "/platform/partners",
    status: "live",
  },
  {
    id: "developers",
    title: "Developer Platform",
    description: "API keys, webhooks, sandbox.",
    href: "/platform/developers",
    status: "live",
  },
  {
    id: "automation",
    title: "AI Automation",
    description: "Triggers, actions, and recipes.",
    href: "/platform/automation",
    status: "live",
  },
  {
    id: "wallet",
    title: "Wallet & Trust",
    description: "Identity passport and trust score.",
    href: "/wallet",
    status: "live",
  },
  {
    id: "command",
    title: "Command Center",
    description: "Executive one-screen view.",
    href: "/platform/command",
    status: "live",
  },
  {
    id: "security",
    title: "Enterprise Security",
    description: "SSO, MFA, audit, recovery.",
    href: "/platform/security",
    status: "live",
  },
];

export const PLATFORM_HUB_TILES = [
  {
    id: "core",
    title: "Core ops",
    description: "Fleet, dispatch, finance, safety.",
    href: "/platform#core-map",
  },
  {
    id: "exchange",
    title: "Transpo Exchange™",
    description: "Freight and capacity marketplace.",
    href: "/exchange",
  },
  {
    id: "network",
    title: "Verified Network™",
    description: "People and company trust graph.",
    href: "/network",
  },
  {
    id: "workforce",
    title: "Transpo Workforce™",
    description: "Hire and onboard talent.",
    href: "/workforce",
  },
  {
    id: "apps",
    title: "Transpo App Store™",
    description: "Install partner apps securely.",
    href: "/platform/apps",
  },
  {
    id: "partners",
    title: "Partners",
    description: "Partner levels and leads.",
    href: "/platform/partners",
  },
  {
    id: "developers",
    title: "Developers",
    description: "API, SDK, sandbox keys.",
    href: "/platform/developers",
  },
  {
    id: "automation",
    title: "Automation",
    description: "No-code AI workflows.",
    href: "/platform/automation",
  },
  {
    id: "command",
    title: "Command Center",
    description: "Live executive board.",
    href: "/platform/command",
  },
  {
    id: "migration",
    title: "AI Migration Center",
    description: "Import years of data safely with Alph.",
    href: "/platform/migration",
  },
  {
    id: "security",
    title: "Security",
    description: "SSO, MFA, audit, recovery.",
    href: "/platform/security",
  },
  {
    id: "governance",
    title: "Master Constitution",
    description:
      "Version 1.0 — highest authority; /constitution overrides feature requests.",
    href: "/platform/governance",
  },
  {
    id: "foundation",
    title: "Transpo.ai Foundation",
    description: "Operating mandate — architecture, quality, decades of trust.",
    href: "/platform/foundation",
  },
  {
    id: "trust-charter",
    title: "Trust & Safety Charter",
    description: "Trust & safety — implements the Master Constitution.",
    href: "/platform/trust-charter",
  },
  {
    id: "constitution",
    title: "Engineering Constitution",
    description: "How Alph and automation stay under human control.",
    href: "/platform/constitution",
  },
  {
    id: "ai-policy",
    title: "AI Safety Policy",
    description: "Confirmations, automation levels, Alph rules.",
    href: "/platform/ai-policy",
  },
] as const;

/** Destinations for command palette / smart search */
export const PLATFORM_SEARCH_DESTINATIONS = [
  {
    id: "platform-home",
    title: "Transpo Platform™",
    subtitle: "Run your entire operation here",
    href: "/platform",
    keywords: ["platform", "hub", "ecosystem", "operating system"],
  },
  {
    id: "platform-apps",
    title: "Transpo App Store™",
    subtitle: "Partner apps and permissions",
    href: "/platform/apps",
    keywords: ["app store", "apps", "install", "integrations", "eld", "ocr"],
  },
  {
    id: "platform-partners",
    title: "Partner Center",
    subtitle: "Verified, Gold, Platinum partners",
    href: "/platform/partners",
    keywords: ["partners", "partner center", "certification"],
  },
  {
    id: "platform-developers",
    title: "Developer Platform",
    subtitle: "API keys, webhooks, sandbox",
    href: "/platform/developers",
    keywords: ["developers", "api", "sdk", "webhooks", "sandbox", "api keys"],
  },
  {
    id: "platform-automation",
    title: "AI Automation Center",
    subtitle: "Triggers and recipes",
    href: "/platform/automation",
    keywords: ["automation", "workflows", "recipes", "no-code"],
  },
  {
    id: "platform-command",
    title: "Command Center",
    subtitle: "Executive live board",
    href: "/platform/command",
    keywords: ["command center", "executive", "business health"],
  },
  {
    id: "platform-migration",
    title: "AI Migration Center",
    subtitle: "Import CSV and historical data safely",
    href: "/platform/migration",
    keywords: [
      "migration",
      "import",
      "csv",
      "excel",
      "migrate data",
      "ai migration",
      "start import",
      "historical data",
    ],
  },
  {
    id: "platform-migration-new",
    title: "Start migration",
    subtitle: "New import wizard",
    href: "/platform/migration/new",
    keywords: ["start import", "new migration", "upload csv", "import wizard"],
  },
  {
    id: "platform-ecosystem",
    title: "Ecosystem map",
    subtitle: "Entire operation at a glance",
    href: "/platform/ecosystem",
    keywords: ["ecosystem", "map", "exchange", "network"],
  },
  {
    id: "platform-translation",
    title: "Global Translation",
    subtitle: "Language preference and Alph translate",
    href: "/platform/translation",
    keywords: ["translation", "language", "i18n", "spanish", "translate"],
  },
  {
    id: "platform-security",
    title: "Enterprise Security",
    subtitle: "SSO, MFA, audit, DR",
    href: "/platform/security",
    keywords: ["security", "sso", "mfa", "rbac", "audit", "backup"],
  },
  {
    id: "platform-governance",
    title: "Master Constitution",
    subtitle: "Version 1.0 — highest authority — /constitution",
    href: "/platform/governance",
    keywords: [
      "master constitution",
      "permanent constitution",
      "constitution folder",
      "governance",
      "highest authority",
      "conflict protocol",
      "override",
      "version 1.0",
      "alph",
    ],
  },
  {
    id: "platform-foundation",
    title: "Transpo.ai Foundation",
    subtitle: "Operating mandate — trust for decades",
    href: "/platform/foundation",
    keywords: [
      "foundation",
      "transpo foundation",
      "operating mandate",
      "architecture",
      "long term",
      "engineering tradeoffs",
      "built on foundation",
      "governance",
      "alph",
    ],
  },
  {
    id: "platform-trust-charter",
    title: "Transpo.ai Trust & Safety Charter",
    subtitle: "Implements the Master Constitution",
    href: "/platform/trust-charter",
    keywords: [
      "trust charter",
      "trust and safety",
      "safety charter",
      "no decision policy",
      "ai principles",
      "human in control",
      "governance",
      "alph",
      "charter",
    ],
  },
  {
    id: "platform-constitution",
    title: "Transpo.ai Engineering Constitution",
    subtitle: "Implements the Trust & Safety Charter",
    href: "/platform/constitution",
    keywords: [
      "constitution",
      "engineering constitution",
      "ai principles",
      "safety",
      "approvals",
      "human in control",
      "alph policy",
      "governance",
    ],
  },
  {
    id: "platform-ai-policy",
    title: "AI Safety Policy",
    subtitle: "Alph assists. You decide.",
    href: "/platform/ai-policy",
    keywords: [
      "ai policy",
      "ai safety",
      "alph",
      "automation policy",
      "confirmation",
      "governed by constitution",
      "trust charter",
      "governed by trust",
      "foundation",
    ],
  },

  {
    id: "wallet-home",
    title: "Digital Wallet",
    subtitle: "Identity and document sharing",
    href: "/wallet",
    keywords: ["wallet", "passport", "identity", "trust score"],
  },
  {
    id: "wallet-trust",
    title: "Trust score",
    subtitle: "Wallet trust and badges",
    href: "/wallet/trust",
    keywords: ["trust", "verified", "badges"],
  },
  {
    id: "workforce-home",
    title: "Transpo Workforce™",
    subtitle: "Hiring command center",
    href: "/workforce",
    keywords: ["workforce", "hiring", "recruiting", "jobs", "candidates"],
  },
  {
    id: "exchange-home",
    title: "Transpo Exchange™",
    subtitle: "Buy, sell, rent, hire — trucking commerce",
    href: "/exchange",
    keywords: [
      "exchange",
      "marketplace",
      "freight board",
      "capacity",
      "equipment",
      "parts",
      "ai shopping",
    ],
  },
  {
    id: "network-home",
    title: "Transpo Verified Network™",
    subtitle: "Trusted professionals and companies",
    href: "/network",
    keywords: ["network", "verified network", "connections", "professionals"],
  },
] as const;
