import type {
  ApiKeyRecord,
  DeveloperDocSection,
  FraudFlag,
  PlatformApp,
  PlatformAuditEntry,
  PlatformAutomationRecipe,
  PlatformPartner,
  SandboxRequestLog,
} from "@/lib/platform/types";

export const SEED_APPS: PlatformApp[] = [
  {
    id: "app-samsara",
    name: "Samsara ELD",
    developer: "Samsara",
    category: "eld",
    tagline: "ELD, GPS, and safety cameras in one feed.",
    description:
      "Connect hours of service, vehicle location, and safety events into Transpo Platform™ dispatch and compliance views.",
    permissions: ["fleet.read", "drivers.read", "location.read", "compliance.read"],
    revenueShareNote: "Partner revenue share applies on new Transpo-referred seats.",
    rating: 4.8,
    installsLabel: "12.4k fleets",
    featured: true,
  },
  {
    id: "app-motive",
    name: "Motive Fleet",
    developer: "Motive",
    category: "eld",
    tagline: "ELD + fleet camera suite.",
    description:
      "Sync HOS, DVIR, and camera events. Alph can surface Hos risk without leaving Platform.",
    permissions: ["fleet.read", "drivers.read", "location.read", "compliance.read"],
    revenueShareNote: "Standard App Store revenue share with Motive attribution.",
    rating: 4.6,
    installsLabel: "9.1k fleets",
    featured: true,
  },
  {
    id: "app-comdata",
    name: "Comdata Fuel",
    developer: "Corpay",
    category: "fuel",
    tagline: "Fuel cards and IFTA-ready transactions.",
    description:
      "Import fuel purchases for IFTA and exception review. Does not process card payments inside Transpo.",
    permissions: ["finance.read", "fleet.read"],
    revenueShareNote: "Interchange and partner incentives billed by Corpay.",
    rating: 4.4,
    installsLabel: "6.8k fleets",
  },
  {
    id: "app-progressive",
    name: "Progressive Commercial",
    developer: "Progressive",
    category: "insurance",
    tagline: "Policy status and COI requests.",
    description:
      "Track coverage windows and request certificates. Claims filing remains with the carrier.",
    permissions: ["documents.read", "compliance.read", "fleet.read"],
    revenueShareNote: "Lead referral fees when a quote is requested through Platform.",
    rating: 4.2,
    installsLabel: "3.2k fleets",
  },
  {
    id: "app-quickbooks",
    name: "QuickBooks Online",
    developer: "Intuit",
    category: "accounting",
    tagline: "Sync invoices and payments.",
    description:
      "Push approved invoices and pull payment status. Requires OAuth in Settings → Integrations.",
    permissions: ["finance.read", "finance.write", "documents.read"],
    revenueShareNote: "No Transpo cut on accounting sync — partner billing is direct.",
    rating: 4.5,
    installsLabel: "8.7k fleets",
    featured: true,
  },
  {
    id: "app-veryfi",
    name: "Veryfi OCR",
    developer: "Veryfi",
    category: "ocr",
    tagline: "Extract PODs, BOLs, and rate cons.",
    description:
      "Send scanned docs for field extraction into Document Center. Results stay in your tenant store.",
    permissions: ["documents.read", "documents.write", "loads.read"],
    revenueShareNote: "Per-page usage billed by Veryfi; Transpo App Store™ attribution retained.",
    rating: 4.7,
    installsLabel: "4.1k fleets",
  },
  {
    id: "app-alph-assist",
    name: "Alph Ops Copilot",
    developer: "Transpo.ai",
    category: "ai",
    tagline: "Voice and NL for the whole operation.",
    description:
      "Built-in Alph intents for loads, drivers, invoices, maintenance, and Platform destinations.",
    permissions: [
      "loads.read",
      "loads.write",
      "drivers.read",
      "fleet.read",
      "finance.read",
      "documents.read",
    ],
    revenueShareNote: "Included with Transpo Platform™ — no third-party share.",
    rating: 4.9,
    installsLabel: "All tenants",
    featured: true,
  },
  {
    id: "app-bentley",
    name: "Bentley Systems PM",
    developer: "Bentley",
    category: "maintenance",
    tagline: "Predictive maintenance schedules.",
    description:
      "Pull PM due dates into Fleet Maintenance and suggest work orders when thresholds hit.",
    permissions: ["fleet.read", "documents.write"],
    revenueShareNote: "Enterprise contract with optional Platform referral credit.",
    rating: 4.3,
    installsLabel: "1.9k fleets",
  },
  {
    id: "app-samsara-cam",
    name: "Samsara Cameras",
    developer: "Samsara",
    category: "cameras",
    tagline: "Safety event review links.",
    description:
      "Deep-link camera events into Safety & Compliance for coaching workflows.",
    permissions: ["drivers.read", "fleet.read", "compliance.read"],
    revenueShareNote: "Bundled with Samsara ELD partner terms.",
    rating: 4.6,
    installsLabel: "5.5k fleets",
  },
  {
    id: "app-geotab",
    name: "Geotab",
    developer: "Geotab",
    category: "gps",
    tagline: "Telematics and engine diagnostics.",
    description:
      "Location and fault codes for dispatch and maintenance. Install grants read scopes only.",
    permissions: ["fleet.read", "location.read"],
    revenueShareNote: "Marketplace listing fee + partner attribution.",
    rating: 4.5,
    installsLabel: "7.2k fleets",
  },
  {
    id: "app-gusto",
    name: "Gusto Payroll",
    developer: "Gusto",
    category: "payroll",
    tagline: "Export settlements for payroll runs.",
    description:
      "Export approved driver pay summaries. Actual ACH runs happen in Gusto — not inside Transpo.",
    permissions: ["finance.read", "drivers.read"],
    revenueShareNote: "Partner referral on new Gusto payroll accounts.",
    rating: 4.4,
    installsLabel: "2.6k fleets",
  },
  {
    id: "app-bamboo",
    name: "BambooHR",
    developer: "BambooHR",
    category: "hr",
    tagline: "HRIS sync for office staff.",
    description:
      "Optional sync of office employee roster into Workforce hiring companies.",
    permissions: ["drivers.read", "documents.read"],
    revenueShareNote: "Standard App Store revenue share.",
    rating: 4.1,
    installsLabel: "980 fleets",
  },
  {
    id: "app-jjkeller",
    name: "J. J. Keller Compliance",
    developer: "J. J. Keller",
    category: "compliance",
    tagline: "Audit prep and policy libraries.",
    description:
      "Surface checklist items alongside Transpo compliance scores. Advisory only.",
    permissions: ["compliance.read", "documents.read"],
    revenueShareNote: "Content licensing billed by J. J. Keller.",
    rating: 4.3,
    installsLabel: "3.8k fleets",
  },
  {
    id: "app-omnitracs",
    name: "Omnitracs Telematics",
    developer: "Omnitracs",
    category: "telematics",
    tagline: "Legacy fleet telematics bridge.",
    description:
      "Bridge older Omnitracs feeds into Platform location and HOS views where supported.",
    permissions: ["fleet.read", "location.read", "drivers.read"],
    revenueShareNote: "Technology partner agreement.",
    rating: 4.0,
    installsLabel: "2.1k fleets",
  },
  {
    id: "app-transpo-api",
    name: "Transpo Public API",
    developer: "Transpo.ai",
    category: "apis",
    tagline: "REST + webhooks for your stack.",
    description:
      "Generate sandbox keys, explore rate limits, and monitor sample traffic from Developer Platform.",
    permissions: ["webhooks.write", "loads.read", "fleet.read", "finance.read"],
    revenueShareNote: "First-party — usage counted toward your plan.",
    rating: 4.8,
    installsLabel: "Developer default",
    featured: true,
  },
  {
    id: "app-custom-enterprise",
    name: "Custom Enterprise Connector",
    developer: "Your team",
    category: "enterprise",
    tagline: "Private integration with scoped access.",
    description:
      "Template for private connectors. Permissions are reviewed before production keys are issued.",
    permissions: ["loads.read", "documents.read", "finance.read", "webhooks.write"],
    revenueShareNote: "Negotiated enterprise terms — no public catalog cut.",
    rating: 4.7,
    installsLabel: "Private",
  },
];

export const SEED_PARTNERS: PlatformPartner[] = [
  {
    id: "partner-samsara",
    name: "Samsara",
    level: "platinum",
    category: "ELD & Cameras",
    description: "Technology partner for ELD, cameras, and safety events.",
    region: "North America",
    contactEmail: "partners@samsara.com",
    apiAccess: "production",
    integrationStatus: "certified",
    leadsOpen: 14,
    certification: "Transpo Verified Integration™",
    marketingAssets: ["Co-branded one-pager", "Webinar deck", "Case study"],
    analytics: { impressions: 48200, leads: 126, conversions: 38, apiCalls30d: 1_240_000 },
  },
  {
    id: "partner-intuit",
    name: "Intuit QuickBooks",
    level: "gold",
    category: "Accounting",
    description: "Accounting sync for invoices and payments.",
    region: "Global",
    contactEmail: "alliances@intuit.com",
    apiAccess: "production",
    integrationStatus: "live",
    leadsOpen: 9,
    certification: "Gold Integration Partner",
    marketingAssets: ["Integration badge", "Help center article"],
    analytics: { impressions: 22100, leads: 64, conversions: 22, apiCalls30d: 410_000 },
  },
  {
    id: "partner-corpay",
    name: "Corpay / Comdata",
    level: "verified",
    category: "Fuel",
    description: "Fuel card transaction import for IFTA and expense review.",
    region: "United States",
    contactEmail: "fleet-partners@corpay.com",
    apiAccess: "sandbox",
    integrationStatus: "in_progress",
    leadsOpen: 5,
    certification: "Verified Partner",
    marketingAssets: ["Fuel program flyer"],
    analytics: { impressions: 9800, leads: 21, conversions: 6, apiCalls30d: 88_000 },
  },
  {
    id: "partner-geotab",
    name: "Geotab",
    level: "technology",
    category: "Telematics",
    description: "OEM-agnostic telematics and engine data.",
    region: "Global",
    contactEmail: "marketplace@geotab.com",
    apiAccess: "production",
    integrationStatus: "live",
    leadsOpen: 11,
    certification: "Technology Partner",
    marketingAssets: ["SDK overview", "Partner logo pack"],
    analytics: { impressions: 15600, leads: 43, conversions: 15, apiCalls30d: 620_000 },
  },
  {
    id: "partner-freightliner",
    name: "Freightliner",
    level: "manufacturer",
    category: "OEM",
    description: "Manufacturer program for connected truck readiness.",
    region: "North America",
    contactEmail: "connected@freightliner.com",
    apiAccess: "sandbox",
    integrationStatus: "in_progress",
    leadsOpen: 3,
    certification: "Manufacturer Alliance",
    marketingAssets: ["Dealer briefing"],
    analytics: { impressions: 4200, leads: 8, conversions: 2, apiCalls30d: 12_000 },
  },
  {
    id: "partner-fmcsa-lab",
    name: "FMCSA Innovation Lab",
    level: "government",
    category: "Compliance research",
    description: "Government technology pilot for safety data exchange (non-production).",
    region: "United States",
    contactEmail: "innovation@example.gov",
    apiAccess: "sandbox",
    integrationStatus: "not_started",
    leadsOpen: 0,
    certification: "Government Pilot",
    marketingAssets: ["Pilot brief"],
    analytics: { impressions: 1100, leads: 0, conversions: 0, apiCalls30d: 0 },
  },
  {
    id: "partner-local-broker",
    name: "Heartland Freight Partners",
    level: "registered",
    category: "Brokerage",
    description: "Regional broker exploring Exchange listing and API access.",
    region: "Midwest",
    contactEmail: "ops@heartlandfreight.example",
    apiAccess: "none",
    integrationStatus: "not_started",
    leadsOpen: 2,
    certification: "Registered",
    marketingAssets: ["Profile draft"],
    analytics: { impressions: 640, leads: 2, conversions: 0, apiCalls30d: 0 },
  },
  {
    id: "partner-enterprise-logistics",
    name: "Northstar Logistics",
    level: "enterprise",
    category: "3PL",
    description: "Enterprise 3PL with private connector and dedicated support lane.",
    region: "North America",
    contactEmail: "platform@northstar.example",
    apiAccess: "production",
    integrationStatus: "certified",
    leadsOpen: 7,
    certification: "Enterprise Certified",
    marketingAssets: ["Executive overview", "Security questionnaire", "SLA summary"],
    analytics: { impressions: 8900, leads: 31, conversions: 12, apiCalls30d: 245_000 },
  },
];

export const SEED_AUTOMATION_RECIPES: PlatformAutomationRecipe[] = [
  {
    id: "recipe-pod-invoice",
    name: "POD → Invoice",
    description: "When proof of delivery lands, draft an invoice for accounting.",
    trigger: "pod_uploaded",
    action: "create_invoice",
    enabled: true,
    createdAt: "2026-07-01T12:00:00.000Z",
    updatedAt: "2026-07-14T09:00:00.000Z",
    linkedWorkflowHref: "/workflows",
  },
  {
    id: "recipe-maint-schedule",
    name: "Maintenance due → Schedule",
    description: "When a PM window opens, create a maintenance schedule item.",
    trigger: "maintenance_due",
    action: "schedule_maintenance",
    enabled: true,
    createdAt: "2026-07-02T12:00:00.000Z",
    updatedAt: "2026-07-12T15:20:00.000Z",
    linkedWorkflowHref: "/fleet/maintenance",
  },
  {
    id: "recipe-insurance-notify",
    name: "Insurance expires → Notify",
    description: "Warn safety and ownership before coverage lapses.",
    trigger: "insurance_expires",
    action: "notify_team",
    enabled: true,
    createdAt: "2026-07-03T12:00:00.000Z",
    updatedAt: "2026-07-10T11:00:00.000Z",
    linkedWorkflowHref: "/compliance",
  },
  {
    id: "recipe-empty-loads",
    name: "Truck empty → Suggest loads",
    description: "When a truck goes empty, suggest nearby freight from dispatch.",
    trigger: "truck_empty",
    action: "suggest_loads",
    enabled: false,
    createdAt: "2026-07-04T12:00:00.000Z",
    updatedAt: "2026-07-11T08:30:00.000Z",
    linkedWorkflowHref: "/loads",
  },
  {
    id: "recipe-driver-freight",
    name: "Driver available → Match freight",
    description: "Match available drivers to open loads with Alph ranking.",
    trigger: "driver_available",
    action: "match_freight",
    enabled: true,
    createdAt: "2026-07-05T12:00:00.000Z",
    updatedAt: "2026-07-15T16:00:00.000Z",
    linkedWorkflowHref: "/loads",
  },
  {
    id: "recipe-payment-accounting",
    name: "Payment → Accounting",
    description: "When a payment is recorded, sync status to accounting.",
    trigger: "payment_received",
    action: "sync_accounting",
    enabled: true,
    createdAt: "2026-07-06T12:00:00.000Z",
    updatedAt: "2026-07-16T10:10:00.000Z",
    linkedWorkflowHref: "/finance",
  },
];

export const SEED_API_KEYS: ApiKeyRecord[] = [
  {
    id: "key-sandbox-demo",
    name: "Sandbox default",
    prefix: "tp_test_",
    secretHint: "tp_test_••••••••7a2c",
    createdAt: "2026-07-08T10:00:00.000Z",
    lastUsedAt: "2026-07-17T08:12:00.000Z",
    environment: "sandbox",
  },
];

export const SEED_SANDBOX_LOGS: SandboxRequestLog[] = [
  {
    id: "slog-1",
    at: "2026-07-17T08:12:00.000Z",
    method: "GET",
    path: "/v1/loads",
    status: 200,
    latencyMs: 42,
    note: "List active loads",
  },
  {
    id: "slog-2",
    at: "2026-07-17T08:05:00.000Z",
    method: "POST",
    path: "/v1/webhooks/test",
    status: 202,
    latencyMs: 18,
    note: "Webhook ping accepted",
  },
  {
    id: "slog-3",
    at: "2026-07-16T19:40:00.000Z",
    method: "GET",
    path: "/v1/fleet/trucks",
    status: 200,
    latencyMs: 55,
    note: "Fleet snapshot",
  },
];

export const SEED_DEV_DOCS: DeveloperDocSection[] = [
  {
    id: "auth",
    title: "Authentication",
    body: `Use Bearer API keys from this Developer Platform.

\`\`\`
Authorization: Bearer tp_test_...
\`\`\`

Sandbox keys never touch production data. Rotate keys from the Keys panel — revoked keys stop working immediately in this local store.`,
  },
  {
    id: "webhooks",
    title: "Webhooks",
    body: `Subscribe to events such as \`load.delivered\`, \`pod.uploaded\`, and \`invoice.paid\`.

Delivery is signed with a shared secret. This demo logs sample deliveries in the Sandbox console — it does not send live HTTP callbacks.`,
  },
  {
    id: "sdk",
    title: "SDK",
    body: `Install the TypeScript SDK when published:

\`\`\`
npm install @transpo/sdk
\`\`\`

Until then, call REST from your stack. Rate limits and monitoring below reflect sandbox policy for demos.`,
  },
  {
    id: "rate-limits",
    title: "Rate limits",
    body: `Sandbox: **120 requests / minute** per key
Production (plan-based): starts at **600 requests / minute**

Burst above the limit returns \`429\` with \`Retry-After\`. Monitoring charts on this page are local aggregates.`,
  },
];

export const SEED_PLATFORM_AUDIT: PlatformAuditEntry[] = [
  {
    id: "pa-1",
    at: "2026-07-17T09:00:00.000Z",
    actor: "Jordan Reyes",
    action: "app.install",
    resource: "app-quickbooks",
    details: "Installed QuickBooks Online with finance scopes",
  },
  {
    id: "pa-2",
    at: "2026-07-16T16:22:00.000Z",
    actor: "Jordan Reyes",
    action: "apikey.create",
    resource: "key-sandbox-demo",
    details: "Created sandbox API key",
  },
  {
    id: "pa-3",
    at: "2026-07-15T11:05:00.000Z",
    actor: "System",
    action: "automation.enable",
    resource: "recipe-pod-invoice",
    details: "Enabled POD → Invoice recipe",
  },
  {
    id: "pa-4",
    at: "2026-07-14T08:40:00.000Z",
    actor: "Jordan Reyes",
    action: "security.mfa_review",
    resource: "settings",
    details: "Reviewed MFA settings (linked to Settings)",
  },
];

export const SEED_FRAUD_FLAGS: FraudFlag[] = [
  {
    id: "ff-1",
    severity: "warning",
    title: "Unusual invoice edit pattern",
    detail:
      "Alph flagged three rate changes on the same load within 10 minutes. Review before sending.",
    href: "/finance",
  },
  {
    id: "ff-2",
    severity: "info",
    title: "New API key in sandbox",
    detail: "A sandbox key was generated this week. Production keys require owner approval.",
    href: "/platform/developers",
  },
  {
    id: "ff-3",
    severity: "critical",
    title: "Document share outside verified network",
    detail:
      "A wallet share link was opened from an unrecognized domain. Revoke if unexpected.",
    href: "/wallet/sharing",
  },
];

export const PLATFORM_VOICE_COMMANDS = [
  "Open Platform",
  "Open App Store",
  "Create a load",
  "Find available drivers",
  "Pay invoice",
  "Schedule maintenance",
  "Open Command Center",
  "Show security",
  "Translate to Spanish",
  "Open Transpo Exchange",
  "Open Workforce",
  "Open Wallet",
] as const;
