import type {
  AdCampaign,
  AuditEntry,
  ExchangeInsight,
  ExchangeListing,
  ExchangeMessage,
  ExchangeOffer,
  ExchangeOrder,
  ExchangeReview,
  ExchangeSeller,
  FinancingApplication,
  SavedSearch,
} from "@/lib/exchange/types";

export const EXCHANGE_TENANT_ID = "tenant-demo";

export const seedSellers: ExchangeSeller[] = [
  {
    id: "sel-midwest-truck",
    name: "Midwest Truck Center",
    kind: "dealer",
    city: "Chicago",
    state: "IL",
    rating: 4.8,
    reviewCount: 214,
    verified: true,
    verificationLevel: "premium",
    networkMemberId: "net-midwest-truck",
    trustScore: 92,
    responseHours: 2,
    memberSince: "2019-03-12",
    bio: "Authorized Cascadia and Freightliner dealer serving the Midwest corridor.",
    specialties: ["Trucks", "Reefers", "Trade-ins"],
  },
  {
    id: "sel-sunbelt-parts",
    name: "Sunbelt OEM Parts",
    kind: "oem",
    city: "Dallas",
    state: "TX",
    rating: 4.6,
    reviewCount: 891,
    verified: true,
    verificationLevel: "verified",
    networkMemberId: "net-sunbelt-parts",
    trustScore: 88,
    responseHours: 4,
    memberSince: "2018-06-01",
    bio: "OEM and aftermarket heavy-duty parts with same-day shipping on core SKUs.",
    specialties: ["Engines", "Transmissions", "Brakes"],
  },
  {
    id: "sel-roadside-pro",
    name: "Roadside Pro Mobile",
    kind: "shop",
    city: "Atlanta",
    state: "GA",
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    verificationLevel: "verified",
    trustScore: 85,
    responseHours: 1,
    memberSince: "2021-01-20",
    bio: "24/7 mobile mechanics and roadside across the Southeast.",
    specialties: ["Roadside", "PM", "Tires"],
  },
  {
    id: "sel-cold-chain",
    name: "ColdChain Warehousing",
    kind: "carrier",
    city: "Memphis",
    state: "TN",
    rating: 4.5,
    reviewCount: 67,
    verified: true,
    verificationLevel: "verified",
    trustScore: 81,
    responseHours: 6,
    memberSince: "2020-09-08",
    bio: "Temperature-controlled warehouse and cross-dock capacity.",
    specialties: ["Cold storage", "Cross dock"],
  },
  {
    id: "sel-factor-first",
    name: "FactorFirst Capital",
    kind: "broker",
    city: "Phoenix",
    state: "AZ",
    rating: 4.4,
    reviewCount: 320,
    verified: true,
    verificationLevel: "premium",
    networkMemberId: "net-factor-first",
    trustScore: 90,
    responseHours: 3,
    memberSince: "2017-11-15",
    bio: "Factoring, fuel advances, and working capital for carriers.",
    specialties: ["Factoring", "Fuel cards", "Financing"],
  },
  {
    id: "sel-gov-surplus",
    name: "Federal Fleet Surplus",
    kind: "government",
    city: "Washington",
    state: "DC",
    rating: 4.2,
    reviewCount: 48,
    verified: true,
    verificationLevel: "verified",
    trustScore: 94,
    responseHours: 24,
    memberSince: "2015-04-01",
    bio: "Government surplus auctions and sealed-bid fleet disposals.",
    specialties: ["Auctions", "Government surplus"],
  },
  {
    id: "sel-enterprise-fleet",
    name: "NorthStar Logistics Co.",
    kind: "enterprise",
    city: "Columbus",
    state: "OH",
    rating: 4.9,
    reviewCount: 112,
    verified: true,
    verificationLevel: "premium",
    trustScore: 96,
    responseHours: 8,
    memberSince: "2016-02-14",
    bio: "Enterprise fleet procurement, RFQs, and multi-year service contracts.",
    specialties: ["Enterprise RFQ", "Fleet deals"],
  },
  {
    id: "sel-heartland-carrier",
    name: "Heartland Express Sales",
    kind: "carrier",
    city: "Des Moines",
    state: "IA",
    rating: 4.3,
    reviewCount: 39,
    verified: false,
    verificationLevel: "basic",
    trustScore: 62,
    responseHours: 12,
    memberSince: "2023-05-22",
    bio: "Owner-operator selling excess trailers and parking capacity.",
    specialties: ["Trailers", "Parking"],
  },
  {
    id: "sel-pacific-rentals",
    name: "Pacific Heavy Rentals",
    kind: "dealer",
    city: "Los Angeles",
    state: "CA",
    rating: 4.6,
    reviewCount: 203,
    verified: true,
    verificationLevel: "verified",
    trustScore: 87,
    responseHours: 3,
    memberSince: "2019-08-30",
    bio: "Short and long-term truck, trailer, and forklift rentals.",
    specialties: ["Rentals", "Forklifts"],
  },
  {
    id: "sel-insurance-lane",
    name: "LaneGuard Insurance",
    kind: "broker",
    city: "Indianapolis",
    state: "IN",
    rating: 4.5,
    reviewCount: 410,
    verified: true,
    verificationLevel: "premium",
    trustScore: 91,
    responseHours: 5,
    memberSince: "2018-01-09",
    bio: "Commercial auto, cargo, and occupancy insurance for fleets.",
    specialties: ["Insurance", "Compliance"],
  },
];

function L(
  partial: Omit<ExchangeListing, "tenantId" | "currency" | "status" | "updatedAt"> & {
    status?: ExchangeListing["status"];
  },
): ExchangeListing {
  return {
    tenantId: EXCHANGE_TENANT_ID,
    currency: "USD",
    status: partial.status ?? "active",
    updatedAt: partial.createdAt,
    ...partial,
  };
}

export const seedListings: ExchangeListing[] = [
  L({
    id: "lst-cascadia-21",
    sellerId: "sel-midwest-truck",
    category: "equipment",
    subcategory: "trucks",
    title: "2021 Freightliner Cascadia 126",
    summary: "Detroit DD15, 12-spd, clean CARB, 412k miles",
    description:
      "Well-maintained Cascadia with Detroit DD15, DT12 automated, dual bunk, APU, and recent DPF service. Ideal linehaul tractor.",
    price: 78500,
    compareAtPrice: 84900,
    condition: "used_excellent",
    year: 2021,
    make: "Freightliner",
    model: "Cascadia",
    mileage: 412000,
    locationCity: "Joliet",
    locationState: "IL",
    distanceMiles: 48,
    shippingAvailable: true,
    shippingEstimate: 2400,
    deliveryDays: 7,
    warrantyMonths: 3,
    availability: "available",
    tags: ["cascadia", "sleeper", "detroit"],
    featured: true,
    sponsored: true,
    boosted: true,
    imageHue: 210,
    createdAt: "2026-07-01T10:00:00.000Z",
    aiScore: 94,
    fraudFlags: [],
    specs: { Engine: "DD15", Transmission: "DT12", Sleepers: "Dual bunk", APU: "Yes" },
  }),
  L({
    id: "lst-reefer-45k",
    sellerId: "sel-midwest-truck",
    category: "equipment",
    subcategory: "reefers",
    title: "2018 Utility 3000R Reefer Trailer",
    summary: "Carrier unit, 53', under $45k — AI pick",
    description:
      "53' Utility reefer with Carrier X4, recent evaporator service, and solid floors. Priced for quick sale under $45k.",
    price: 42900,
    condition: "used_good",
    year: 2018,
    make: "Utility",
    model: "3000R",
    mileage: 0,
    locationCity: "Gary",
    locationState: "IN",
    distanceMiles: 62,
    shippingAvailable: true,
    shippingEstimate: 1800,
    deliveryDays: 10,
    warrantyMonths: 1,
    availability: "available",
    tags: ["reefer", "under45k", "carrier"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 195,
    createdAt: "2026-07-03T14:20:00.000Z",
    aiScore: 97,
    fraudFlags: [],
    specs: { Length: "53 ft", Unit: "Carrier X4", Temp: "-20 to 80°F" },
  }),
  L({
    id: "lst-flatbed-19",
    sellerId: "sel-heartland-carrier",
    category: "equipment",
    subcategory: "flatbeds",
    title: "2019 Fontaine Infinity Flatbed",
    summary: "48' aluminum, winches, spreads axle",
    description: "Lightweight Fontaine flatbed with winch package and air ride.",
    price: 28500,
    condition: "used_good",
    year: 2019,
    make: "Fontaine",
    model: "Infinity",
    locationCity: "Des Moines",
    locationState: "IA",
    distanceMiles: 310,
    shippingAvailable: true,
    shippingEstimate: 2100,
    deliveryDays: 12,
    availability: "available",
    tags: ["flatbed", "aluminum"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 30,
    createdAt: "2026-06-28T09:00:00.000Z",
    aiScore: 78,
    fraudFlags: [
      {
        id: "ff-1",
        code: "new_seller",
        label: "Newer seller",
        severity: "info",
        detail: "Seller account under 3 years — verify Network identity before large wire.",
      },
    ],
    specs: { Length: "48 ft", Material: "Aluminum", Axles: "Spread" },
  }),
  L({
    id: "lst-dryvan-20",
    sellerId: "sel-midwest-truck",
    category: "equipment",
    subcategory: "dry_vans",
    title: "2020 Great Dane Dry Van",
    summary: "53' swing door, logistics posts",
    description: "Clean dry van with logistics posts and recent tires.",
    price: 24500,
    condition: "used_excellent",
    year: 2020,
    make: "Great Dane",
    model: "Champion",
    locationCity: "Chicago",
    locationState: "IL",
    distanceMiles: 12,
    shippingAvailable: true,
    shippingEstimate: 1200,
    deliveryDays: 5,
    warrantyMonths: 1,
    availability: "in_stock",
    tags: ["dry van", "53"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 220,
    createdAt: "2026-07-05T11:00:00.000Z",
    aiScore: 86,
    fraudFlags: [],
    specs: { Length: "53 ft", Doors: "Swing", Posts: "Logistics" },
  }),
  L({
    id: "lst-container-40",
    sellerId: "sel-cold-chain",
    category: "equipment",
    subcategory: "containers",
    title: "40' High Cube Storage Container",
    summary: "Wind & water tight, wind-rated",
    description: "One-trip high cube container for yard storage.",
    price: 4200,
    condition: "used_good",
    locationCity: "Memphis",
    locationState: "TN",
    distanceMiles: 420,
    shippingAvailable: true,
    shippingEstimate: 900,
    deliveryDays: 14,
    availability: "in_stock",
    quantity: 6,
    tags: ["container", "storage"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 160,
    createdAt: "2026-07-02T08:00:00.000Z",
    fraudFlags: [],
    specs: { Size: "40 HC", Condition: "WWT" },
  }),
  L({
    id: "lst-liftgate",
    sellerId: "sel-sunbelt-parts",
    category: "equipment",
    subcategory: "lift_gates",
    title: "Waltco 3,500 lb Rail Lift Gate",
    summary: "Remanufactured, install available",
    description: "Reman Waltco rail lift with new cylinders. Install quote available.",
    price: 3850,
    condition: "refurbished",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 280,
    deliveryDays: 4,
    warrantyMonths: 6,
    availability: "in_stock",
    tags: ["lift gate", "waltco"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 45,
    createdAt: "2026-07-06T15:00:00.000Z",
    fraudFlags: [],
    specs: { Capacity: "3,500 lb", Type: "Rail" },
  }),
  L({
    id: "lst-forklift",
    sellerId: "sel-pacific-rentals",
    category: "equipment",
    subcategory: "forklifts",
    title: "Toyota 8FGU25 Forklift",
    summary: "5,000 lb, propane, 1,800 hours",
    description: "Warehouse forklift with side shift and new tires.",
    price: 18900,
    condition: "used_excellent",
    year: 2019,
    make: "Toyota",
    model: "8FGU25",
    hours: 1800,
    locationCity: "Los Angeles",
    locationState: "CA",
    distanceMiles: 1750,
    shippingAvailable: true,
    shippingEstimate: 1600,
    deliveryDays: 10,
    warrantyMonths: 3,
    availability: "available",
    tags: ["forklift", "toyota"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 10,
    createdAt: "2026-07-04T12:00:00.000Z",
    aiScore: 88,
    fraudFlags: [],
    specs: { Capacity: "5,000 lb", Fuel: "LPG" },
  }),
  L({
    id: "lst-generator",
    sellerId: "sel-sunbelt-parts",
    category: "equipment",
    subcategory: "generators",
    title: "Cummins 70 kW Mobile Generator",
    summary: "Trailer-mounted, low hours",
    description: "Quiet Cummins genset for yard and jobsite power.",
    price: 24500,
    condition: "used_good",
    hours: 920,
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 1100,
    deliveryDays: 8,
    warrantyMonths: 6,
    availability: "available",
    tags: ["generator", "cummins"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 55,
    createdAt: "2026-06-30T10:00:00.000Z",
    fraudFlags: [],
    specs: { Output: "70 kW", Mount: "Trailer" },
  }),
  L({
    id: "lst-office-mod",
    sellerId: "sel-cold-chain",
    category: "equipment",
    subcategory: "office_warehouse",
    title: "Modular Yard Office 12×40",
    summary: "HVAC, restroom, turnkey",
    description: "Relocatable modular office for terminal ops.",
    price: 32000,
    condition: "like_new",
    locationCity: "Memphis",
    locationState: "TN",
    distanceMiles: 420,
    shippingAvailable: true,
    shippingEstimate: 3500,
    deliveryDays: 21,
    availability: "lead_time",
    tags: ["office", "modular"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 180,
    createdAt: "2026-07-07T09:00:00.000Z",
    fraudFlags: [],
    specs: { Size: "12×40", HVAC: "Yes" },
  }),
  L({
    id: "lst-turbo-oem",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "engines",
    title: "OEM Holset HE400VG Turbocharger",
    summary: "New OEM for ISX / DD13 applications",
    description: "Genuine Holset turbo with gasket kit. Core return available.",
    price: 1895,
    compareAtPrice: 2295,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 45,
    deliveryDays: 2,
    warrantyMonths: 12,
    availability: "in_stock",
    quantity: 14,
    tags: ["oem", "turbo", "holset"],
    featured: true,
    sponsored: true,
    boosted: false,
    imageHue: 250,
    createdAt: "2026-07-08T08:00:00.000Z",
    aiScore: 91,
    fraudFlags: [],
    specs: { Brand: "Holset", Type: "OEM new", Core: "Returnable" },
  }),
  L({
    id: "lst-trans-eaton",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "transmissions",
    title: "Eaton Fuller UltraShift Reman",
    summary: "Reman transmission, 12-speed",
    description: "Factory reman UltraShift with 1-year warranty.",
    price: 6200,
    condition: "refurbished",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 220,
    deliveryDays: 5,
    warrantyMonths: 12,
    availability: "in_stock",
    tags: ["transmission", "eaton", "reman"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 260,
    createdAt: "2026-07-01T16:00:00.000Z",
    fraudFlags: [],
    specs: { Speeds: "12", Warranty: "12 months" },
  }),
  L({
    id: "lst-tires-emergency",
    sellerId: "sel-roadside-pro",
    category: "parts",
    subcategory: "tires",
    title: "Emergency Drive Tire Set (4)",
    summary: "295/75R22.5 — nearby install",
    description: "Four new drive tires with mobile mount within 50 miles of Atlanta.",
    price: 1680,
    condition: "new",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 35,
    shippingAvailable: false,
    deliveryDays: 0,
    warrantyMonths: 0,
    availability: "in_stock",
    quantity: 8,
    tags: ["tires", "emergency", "nearby"],
    featured: true,
    sponsored: false,
    boosted: true,
    imageHue: 5,
    createdAt: "2026-07-10T06:00:00.000Z",
    aiScore: 95,
    fraudFlags: [],
    specs: { Size: "295/75R22.5", Mount: "Mobile" },
  }),
  L({
    id: "lst-brakes-kit",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "brakes",
    title: "Meritor Q+ Brake Kit Axle Set",
    summary: "Shoes, hardware, cams — aftermarket",
    description: "Complete axle brake kit for tandem trailers.",
    price: 420,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 28,
    deliveryDays: 3,
    warrantyMonths: 6,
    availability: "in_stock",
    tags: ["brakes", "meritor", "aftermarket"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 0,
    createdAt: "2026-07-09T10:00:00.000Z",
    fraudFlags: [],
    specs: { Fit: "Trailer tandem", Brand: "Meritor Q+" },
  }),
  L({
    id: "lst-suspension",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "suspension",
    title: "Hendrickson Air Spring Pair",
    summary: "OEM air bags for HT250U",
    description: "Matched pair air springs with mounting hardware.",
    price: 310,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 22,
    deliveryDays: 2,
    warrantyMonths: 12,
    availability: "in_stock",
    tags: ["suspension", "hendrickson"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 270,
    createdAt: "2026-07-05T13:00:00.000Z",
    fraudFlags: [],
    specs: { Fit: "HT250U", Qty: "Pair" },
  }),
  L({
    id: "lst-electrical",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "electrical",
    title: "7-Way ABS Harness Kit",
    summary: "Trailer electrical — sealed connectors",
    description: "Complete 7-way with ABS drop and sealed plugs.",
    price: 89,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 12,
    deliveryDays: 2,
    warrantyMonths: 6,
    availability: "in_stock",
    tags: ["electrical", "abs", "harness"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 200,
    createdAt: "2026-07-08T11:00:00.000Z",
    fraudFlags: [],
    specs: { Length: "48 ft ready", Sealed: "Yes" },
  }),
  L({
    id: "lst-lighting",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "lighting",
    title: "LED Marker & Tail Light Bundle",
    summary: "DOT sealed LED pack",
    description: "Twenty-piece LED lighting kit for trailers.",
    price: 145,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 15,
    deliveryDays: 2,
    warrantyMonths: 24,
    availability: "in_stock",
    tags: ["lighting", "led"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 50,
    createdAt: "2026-07-07T14:00:00.000Z",
    fraudFlags: [],
    specs: { Pieces: "20", DOT: "Yes" },
  }),
  L({
    id: "lst-reefer-parts",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "reefer",
    title: "Carrier X4 Condenser Coil",
    summary: "OEM condenser for X4 7500",
    description: "OEM condenser coil with install gasket set.",
    price: 980,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 65,
    deliveryDays: 4,
    warrantyMonths: 12,
    availability: "in_stock",
    tags: ["reefer", "carrier", "oem"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 190,
    createdAt: "2026-07-03T09:30:00.000Z",
    fraudFlags: [],
    specs: { Unit: "X4 7500", Brand: "Carrier OEM" },
  }),
  L({
    id: "lst-body-panel",
    sellerId: "sel-roadside-pro",
    category: "parts",
    subcategory: "body",
    title: "Cascadia Hood Assembly (Used)",
    summary: "Paint-match ready, no cracks",
    description: "Used Cascadia hood, inspected, ready to ship.",
    price: 1450,
    condition: "used_good",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 35,
    shippingAvailable: true,
    shippingEstimate: 180,
    deliveryDays: 5,
    availability: "available",
    tags: ["body", "hood", "used"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 215,
    createdAt: "2026-06-29T12:00:00.000Z",
    fraudFlags: [],
    specs: { Fit: "Cascadia 2018+", Paint: "White" },
  }),
  L({
    id: "lst-accessories",
    sellerId: "sel-sunbelt-parts",
    category: "parts",
    subcategory: "accessories",
    title: "Aluminum Side Fairing Kit",
    summary: "Aero kit — fuel savings",
    description: "Complete side fairing kit for late Cascadias.",
    price: 2100,
    condition: "new",
    locationCity: "Dallas",
    locationState: "TX",
    distanceMiles: 780,
    shippingAvailable: true,
    shippingEstimate: 150,
    deliveryDays: 6,
    warrantyMonths: 12,
    availability: "lead_time",
    tags: ["aero", "fairings"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 225,
    createdAt: "2026-07-02T15:00:00.000Z",
    fraudFlags: [],
    specs: { Material: "Aluminum", Fit: "Cascadia" },
  }),
  L({
    id: "lst-mobile-mech",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "mobile",
    title: "Mobile Mechanic — Atlanta Metro",
    summary: "Diagnostics, PM, after-hours",
    description:
      "ASE-certified mobile techs for on-site diagnostics, filters, and minor repairs. After-hours surcharge disclosed upfront.",
    price: 185,
    priceLabel: "From $185 / callout",
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 18,
    shippingAvailable: false,
    availability: "available",
    tags: ["mechanic", "mobile", "pm"],
    featured: true,
    sponsored: true,
    boosted: false,
    imageHue: 140,
    createdAt: "2026-07-01T07:00:00.000Z",
    aiScore: 93,
    fraudFlags: [],
    specs: { Coverage: "50 mi radius", Hours: "24/7" },
  }),
  L({
    id: "lst-roadside",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "roadside",
    title: "Interstate Roadside Assist",
    summary: "Jump, tire, lockout, light repair",
    description: "Network roadside with 90-minute average ETA on I-75 / I-85.",
    price: 150,
    priceLabel: "From $150",
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 22,
    shippingAvailable: false,
    availability: "available",
    tags: ["roadside", "emergency"],
    featured: true,
    sponsored: false,
    boosted: true,
    imageHue: 12,
    createdAt: "2026-07-09T05:00:00.000Z",
    aiScore: 90,
    fraudFlags: [],
    specs: { ETA: "~90 min", Network: "SE corridor" },
  }),
  L({
    id: "lst-wash",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "wash",
    title: "Tractor & Trailer Wash Membership",
    summary: "Unlimited exterior / 8 detail visits",
    description: "Monthly wash plan for Atlanta terminal fleets.",
    price: 299,
    priceLabel: "$299 / truck / mo",
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 28,
    shippingAvailable: false,
    availability: "available",
    tags: ["wash", "membership"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 185,
    createdAt: "2026-07-04T08:00:00.000Z",
    fraudFlags: [],
    specs: { Exterior: "Unlimited", Detail: "8 / mo" },
  }),
  L({
    id: "lst-towing",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "towing",
    title: "Heavy Wrecker Tow — Southeast",
    summary: "Class 8 recovery, rotators available",
    description: "Heavy tow and recovery with transparent per-mile rates.",
    price: 450,
    priceLabel: "From $450 + mileage",
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 40,
    shippingAvailable: false,
    availability: "available",
    tags: ["towing", "recovery"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 355,
    createdAt: "2026-07-06T18:00:00.000Z",
    fraudFlags: [],
    specs: { Class: "8", Rotator: "On request" },
  }),
  L({
    id: "lst-inspection",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "inspection",
    title: "DOT Annual Inspection",
    summary: "Shop or mobile — same-day cert",
    description: "CVSA-level annual inspection with digital packet to Wallet.",
    price: 175,
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 25,
    shippingAvailable: false,
    availability: "available",
    tags: ["inspection", "dot", "pm"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 170,
    createdAt: "2026-07-08T09:00:00.000Z",
    fraudFlags: [],
    specs: { Delivery: "Digital cert", Mobile: "Yes" },
  }),
  L({
    id: "lst-fleet-truck",
    sellerId: "sel-enterprise-fleet",
    category: "fleet",
    subcategory: "trucks",
    title: "List your truck on Fleet Marketplace",
    summary: "Connect idle power to regional freight",
    description:
      "Publish available trucks to Transpo Fleet Marketplace. Soft-links to Fleet inventory when present.",
    price: 0,
    priceLabel: "Free to list",
    condition: "n_a",
    locationCity: "Columbus",
    locationState: "OH",
    distanceMiles: 280,
    shippingAvailable: false,
    availability: "available",
    tags: ["fleet", "list truck"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 230,
    createdAt: "2026-07-01T12:00:00.000Z",
    fraudFlags: [],
    specs: { Integration: "Fleet module", Mode: "Capacity listing" },
    channel: "enterprise",
  }),
  L({
    id: "lst-freight-lane",
    sellerId: "sel-enterprise-fleet",
    category: "freight",
    subcategory: "lanes",
    title: "CHI → ATL Dry Van Lane (RFQ)",
    summary: "Weekly volume — soft-link Dispatch",
    description:
      "Standing RFQ for dry van CHI–ATL. Can hand off awards into Dispatch / Loads when connected.",
    price: 1850,
    priceLabel: "Target $1,850 / load",
    condition: "n_a",
    locationCity: "Chicago",
    locationState: "IL",
    distanceMiles: 15,
    shippingAvailable: false,
    availability: "available",
    tags: ["freight", "rfq", "dry van"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 205,
    createdAt: "2026-07-09T11:00:00.000Z",
    fraudFlags: [],
    specs: { Frequency: "Weekly", Equipment: "53' dry van" },
  }),
  L({
    id: "lst-insurance",
    sellerId: "sel-insurance-lane",
    category: "business_services",
    subcategory: "insurance",
    title: "Fleet Liability & Cargo Package",
    summary: "Alph-recommended for mid-size fleets",
    description: "Bundled liability, physical damage, and cargo with claims portal.",
    price: 12500,
    priceLabel: "From $12.5k / unit / yr est.",
    condition: "n_a",
    locationCity: "Indianapolis",
    locationState: "IN",
    distanceMiles: 190,
    shippingAvailable: false,
    availability: "available",
    tags: ["insurance", "fleet", "cargo"],
    featured: true,
    sponsored: true,
    boosted: true,
    imageHue: 240,
    createdAt: "2026-07-02T10:00:00.000Z",
    aiScore: 96,
    fraudFlags: [],
    specs: { Lines: "AL + PD + Cargo", Portal: "Yes" },
  }),
  L({
    id: "lst-factoring",
    sellerId: "sel-factor-first",
    category: "business_services",
    subcategory: "factoring",
    title: "Non-Recourse Factoring",
    summary: "1.9% starting — same-day funding demo",
    description: "Invoice factoring with broker credit checks and fuel card bundle option.",
    price: 1.9,
    priceLabel: "From 1.9%",
    condition: "n_a",
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: false,
    availability: "available",
    tags: ["factoring", "cash flow"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 155,
    createdAt: "2026-07-03T11:00:00.000Z",
    aiScore: 89,
    fraudFlags: [],
    specs: { Rate: "From 1.9%", Funding: "Same-day (demo)" },
  }),
  L({
    id: "lst-fuel-a",
    sellerId: "sel-factor-first",
    category: "business_services",
    subcategory: "fuel_cards",
    title: "FuelLink Pro Card",
    summary: "Avg 42¢/gal savings — compare pick",
    description: "National fuel card with IFTA-ready reports and idle alerts.",
    price: 0,
    priceLabel: "No monthly fee",
    condition: "n_a",
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: false,
    availability: "available",
    tags: ["fuel card", "compare"],
    featured: true,
    sponsored: true,
    boosted: false,
    imageHue: 25,
    createdAt: "2026-07-05T09:00:00.000Z",
    aiScore: 92,
    fraudFlags: [],
    specs: { Savings: "~42¢/gal", Reports: "IFTA" },
  }),
  L({
    id: "lst-fuel-b",
    sellerId: "sel-factor-first",
    category: "business_services",
    subcategory: "fuel_cards",
    title: "CorridorCash Fuel Card",
    summary: "Avg 38¢/gal + cash advance",
    description: "Fuel card with optional fuel advance against receivables.",
    price: 8,
    priceLabel: "$8 / card / mo",
    condition: "n_a",
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: false,
    availability: "available",
    tags: ["fuel card", "compare", "advance"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 35,
    createdAt: "2026-07-05T09:05:00.000Z",
    aiScore: 84,
    fraudFlags: [],
    specs: { Savings: "~38¢/gal", Advance: "Optional" },
  }),
  L({
    id: "lst-fuel-c",
    sellerId: "sel-insurance-lane",
    category: "business_services",
    subcategory: "fuel_cards",
    title: "BlueHighway Fleet Fuel",
    summary: "Avg 35¢/gal + telematics bundle",
    description: "Fuel + light telematics bundle for fleets under 50 trucks.",
    price: 15,
    priceLabel: "$15 / truck / mo",
    condition: "n_a",
    locationCity: "Indianapolis",
    locationState: "IN",
    distanceMiles: 190,
    shippingAvailable: false,
    availability: "available",
    tags: ["fuel card", "compare", "telematics"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 220,
    createdAt: "2026-07-05T09:10:00.000Z",
    aiScore: 80,
    fraudFlags: [],
    specs: { Savings: "~35¢/gal", Bundle: "Telematics lite" },
  }),
  L({
    id: "lst-payroll",
    sellerId: "sel-factor-first",
    category: "business_services",
    subcategory: "payroll",
    title: "Driver Payroll & Settlements",
    summary: "Owner-op and company driver pay",
    description: "Settlements, deductions, and 1099/W2 support.",
    price: 6,
    priceLabel: "From $6 / driver / pay",
    condition: "n_a",
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: false,
    availability: "available",
    tags: ["payroll", "settlements"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 265,
    createdAt: "2026-07-06T10:00:00.000Z",
    fraudFlags: [],
    specs: { Modes: "W2 + 1099", Integration: "Payroll module" },
  }),
  L({
    id: "lst-accounting",
    sellerId: "sel-factor-first",
    category: "business_services",
    subcategory: "accounting",
    title: "Carrier Accounting Desk",
    summary: "Books, IFTA assist, year-end",
    description: "Outsourced accounting desk familiar with trucking GL.",
    price: 499,
    priceLabel: "From $499 / mo",
    condition: "n_a",
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: false,
    availability: "available",
    tags: ["accounting", "ifta", "taxes"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 175,
    createdAt: "2026-07-07T10:00:00.000Z",
    fraudFlags: [],
    specs: { IFTA: "Assist", Close: "Monthly" },
  }),
  L({
    id: "lst-legal",
    sellerId: "sel-insurance-lane",
    category: "business_services",
    subcategory: "legal",
    title: "Transportation Counsel Retainer",
    summary: "Contracts, FMCSA, claims",
    description: "Monthly retainer for broker contracts and compliance letters.",
    price: 1500,
    priceLabel: "From $1,500 / mo",
    condition: "n_a",
    locationCity: "Indianapolis",
    locationState: "IN",
    distanceMiles: 190,
    shippingAvailable: false,
    availability: "available",
    tags: ["legal", "compliance"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 280,
    createdAt: "2026-07-04T14:00:00.000Z",
    fraudFlags: [],
    specs: { Focus: "FMCSA + contracts", Hours: "6 incl." },
  }),
  L({
    id: "lst-permits",
    sellerId: "sel-insurance-lane",
    category: "business_services",
    subcategory: "permits",
    title: "Oversize / Overweight Permits",
    summary: "Multi-state permit desk",
    description: "Same-day filing for common OSOW corridors.",
    price: 75,
    priceLabel: "From $75 + state fees",
    condition: "n_a",
    locationCity: "Indianapolis",
    locationState: "IN",
    distanceMiles: 190,
    shippingAvailable: false,
    availability: "available",
    tags: ["permits", "osow"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 40,
    createdAt: "2026-07-08T12:00:00.000Z",
    fraudFlags: [],
    specs: { Turnaround: "Same day", States: "48" },
  }),
  L({
    id: "lst-recruiting",
    sellerId: "sel-enterprise-fleet",
    category: "business_services",
    subcategory: "recruiting",
    title: "Driver Recruiting Desk",
    summary: "Hire via Workforce integration",
    description: "Recruiter desk that posts into Transpo Workforce when present.",
    price: 850,
    priceLabel: "From $850 / hire",
    condition: "n_a",
    locationCity: "Columbus",
    locationState: "OH",
    distanceMiles: 280,
    shippingAvailable: false,
    availability: "available",
    tags: ["recruiting", "workforce"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 200,
    createdAt: "2026-07-09T08:00:00.000Z",
    fraudFlags: [],
    specs: { Integration: "Workforce", Roles: "CDL + shop" },
  }),
  L({
    id: "lst-software-ai",
    sellerId: "sel-enterprise-fleet",
    category: "business_services",
    subcategory: "software",
    title: "Alph Ops Copilot Add-on",
    summary: "AI shopping + dispatch assist",
    description: "Enterprise AI add-on for purchasing and ops briefing.",
    price: 299,
    priceLabel: "$299 / mo",
    condition: "n_a",
    locationCity: "Columbus",
    locationState: "OH",
    distanceMiles: 280,
    shippingAvailable: false,
    availability: "available",
    tags: ["software", "ai", "alph"],
    featured: true,
    sponsored: true,
    boosted: false,
    imageHue: 235,
    createdAt: "2026-07-10T08:00:00.000Z",
    aiScore: 98,
    fraudFlags: [],
    specs: { Module: "Alph", Scope: "Purchasing + ops" },
  }),
  L({
    id: "lst-warehouse-cold",
    sellerId: "sel-cold-chain",
    category: "warehouse",
    subcategory: "cold_storage",
    title: "Cold Storage — 20,000 sq ft",
    summary: "Memphis — dock + freezer",
    description: "Temperature zones from -10°F to +38°F with 8 dock doors.",
    price: 1.85,
    priceLabel: "$1.85 / sq ft / mo",
    condition: "n_a",
    locationCity: "Memphis",
    locationState: "TN",
    distanceMiles: 420,
    shippingAvailable: false,
    availability: "available",
    tags: ["cold storage", "warehouse"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 195,
    createdAt: "2026-07-02T13:00:00.000Z",
    aiScore: 87,
    fraudFlags: [],
    specs: { Size: "20,000 sq ft", Docks: "8" },
  }),
  L({
    id: "lst-crossdock",
    sellerId: "sel-cold-chain",
    category: "warehouse",
    subcategory: "cross_dock",
    title: "Cross Dock Slot — Night Sort",
    summary: "4 doors, 10pm–6am",
    description: "Night cross-dock capacity for regional LTL consolidation.",
    price: 1200,
    priceLabel: "$1,200 / night",
    condition: "n_a",
    locationCity: "Memphis",
    locationState: "TN",
    distanceMiles: 420,
    shippingAvailable: false,
    availability: "available",
    tags: ["cross dock"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 185,
    createdAt: "2026-07-06T20:00:00.000Z",
    fraudFlags: [],
    specs: { Doors: "4", Window: "10pm–6am" },
  }),
  L({
    id: "lst-parking",
    sellerId: "sel-heartland-carrier",
    category: "warehouse",
    subcategory: "parking",
    title: "Secure Truck Parking — 40 spots",
    summary: "Fenced, lit, camera",
    description: "Overnight parking with gate code and cameras.",
    price: 25,
    priceLabel: "$25 / night",
    condition: "n_a",
    locationCity: "Des Moines",
    locationState: "IA",
    distanceMiles: 310,
    shippingAvailable: false,
    availability: "available",
    quantity: 40,
    tags: ["parking", "yard"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 90,
    createdAt: "2026-07-07T18:00:00.000Z",
    fraudFlags: [
      {
        id: "ff-2",
        code: "unverified_seller",
        label: "Seller not fully verified",
        severity: "watch",
        detail: "Complete Trust verification before prepaid parking deposits.",
      },
    ],
    specs: { Spots: "40", Security: "Fence + cameras" },
  }),
  L({
    id: "lst-rent-truck",
    sellerId: "sel-pacific-rentals",
    category: "rentals",
    subcategory: "truck",
    title: "Day Cab Rental — Weekly",
    summary: "2022 Cascadia day cab",
    description: "Weekly rental with mileage package. Insurance options available.",
    price: 1450,
    priceLabel: "$1,450 / week",
    condition: "like_new",
    year: 2022,
    make: "Freightliner",
    model: "Cascadia",
    locationCity: "Los Angeles",
    locationState: "CA",
    distanceMiles: 1750,
    shippingAvailable: false,
    availability: "available",
    tags: ["rental", "day cab"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 210,
    createdAt: "2026-07-08T07:00:00.000Z",
    aiScore: 85,
    fraudFlags: [],
    specs: { Term: "Weekly", Miles: "2,500 incl." },
  }),
  L({
    id: "lst-rent-trailer",
    sellerId: "sel-pacific-rentals",
    category: "rentals",
    subcategory: "trailer",
    title: "Reefer Trailer Rental — Monthly",
    summary: "53' with Carrier unit",
    description: "Monthly reefer rental with maintenance included.",
    price: 2200,
    priceLabel: "$2,200 / month",
    condition: "used_excellent",
    locationCity: "Los Angeles",
    locationState: "CA",
    distanceMiles: 1750,
    shippingAvailable: false,
    availability: "available",
    tags: ["rental", "reefer"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 198,
    createdAt: "2026-07-08T07:10:00.000Z",
    fraudFlags: [],
    specs: { Term: "Monthly", Unit: "Carrier" },
  }),
  L({
    id: "lst-rent-forklift",
    sellerId: "sel-pacific-rentals",
    category: "rentals",
    subcategory: "forklift",
    title: "Forklift Rental — Daily",
    summary: "5k lb propane",
    description: "Daily forklift rental with delivery in LA basin.",
    price: 185,
    priceLabel: "$185 / day",
    condition: "used_good",
    locationCity: "Los Angeles",
    locationState: "CA",
    distanceMiles: 1750,
    shippingAvailable: true,
    shippingEstimate: 120,
    deliveryDays: 1,
    availability: "in_stock",
    tags: ["rental", "forklift"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 15,
    createdAt: "2026-07-08T07:20:00.000Z",
    fraudFlags: [],
    specs: { Capacity: "5,000 lb", Delivery: "LA basin" },
  }),
  L({
    id: "lst-auction-fleet",
    sellerId: "sel-gov-surplus",
    category: "auctions",
    subcategory: "fleet",
    title: "Fleet Liquidation Lot — 12 Tractors",
    summary: "Live demo auction ends Jul 22",
    description: "Mixed Cascadia/International lot. Preview available on-site.",
    price: 520000,
    priceLabel: "Current bid $520k",
    condition: "used_fair",
    locationCity: "Columbus",
    locationState: "OH",
    distanceMiles: 280,
    shippingAvailable: false,
    availability: "auction",
    tags: ["auction", "fleet", "liquidation"],
    featured: true,
    sponsored: false,
    boosted: true,
    imageHue: 20,
    createdAt: "2026-07-01T09:00:00.000Z",
    endsAt: "2026-07-22T18:00:00.000Z",
    bidCount: 17,
    aiScore: 76,
    fraudFlags: [],
    specs: { Units: "12", Type: "Tractors" },
  }),
  L({
    id: "lst-auction-gov",
    sellerId: "sel-gov-surplus",
    category: "auctions",
    subcategory: "government",
    title: "GSA Surplus — Service Trucks",
    summary: "Sealed bid · government",
    description: "Government surplus service body trucks. Sealed bid process.",
    price: 18500,
    priceLabel: "Starting $18.5k",
    condition: "used_fair",
    locationCity: "Washington",
    locationState: "DC",
    distanceMiles: 620,
    shippingAvailable: false,
    availability: "auction",
    tags: ["auction", "government", "gsa"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 220,
    createdAt: "2026-07-03T10:00:00.000Z",
    endsAt: "2026-07-25T17:00:00.000Z",
    bidCount: 9,
    channel: "government",
    fraudFlags: [],
    specs: { Process: "Sealed bid", Origin: "GSA" },
  }),
  L({
    id: "lst-auction-repo",
    sellerId: "sel-factor-first",
    category: "auctions",
    subcategory: "bank_repo",
    title: "Bank Repo — 2020 Volvo VNL",
    summary: "As-is · inspected",
    description: "Bank repossession with third-party inspection report attached.",
    price: 41000,
    priceLabel: "Current bid $41k",
    condition: "used_fair",
    year: 2020,
    make: "Volvo",
    model: "VNL",
    mileage: 580000,
    locationCity: "Phoenix",
    locationState: "AZ",
    distanceMiles: 1400,
    shippingAvailable: true,
    shippingEstimate: 2800,
    availability: "auction",
    tags: ["auction", "repo", "volvo"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 250,
    createdAt: "2026-07-05T16:00:00.000Z",
    endsAt: "2026-07-20T16:00:00.000Z",
    bidCount: 11,
    fraudFlags: [
      {
        id: "ff-3",
        code: "as_is",
        label: "As-is sale",
        severity: "info",
        detail: "Repo units sell as-is — review inspection PDF before bidding.",
      },
    ],
    specs: { Sale: "As-is", Inspection: "Attached" },
  }),
  L({
    id: "lst-biz-carrier",
    sellerId: "sel-heartland-carrier",
    category: "businesses",
    subcategory: "carriers",
    title: "Regional Carrier — 18 Power Units",
    summary: "Authority, customers, shop included",
    description: "Turnkey regional dry van carrier with dedicated lanes and leased yard.",
    price: 2750000,
    condition: "n_a",
    locationCity: "Des Moines",
    locationState: "IA",
    distanceMiles: 310,
    shippingAvailable: false,
    availability: "available",
    tags: ["business sale", "carrier"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 160,
    createdAt: "2026-06-20T10:00:00.000Z",
    fraudFlags: [
      {
        id: "ff-4",
        code: "large_transaction",
        label: "Large transaction",
        severity: "watch",
        detail: "Use escrow-ready path and Trust identity verification for business sales.",
      },
    ],
    specs: { Power: "18", Authority: "Active", Shop: "Yes" },
  }),
  L({
    id: "lst-biz-shop",
    sellerId: "sel-roadside-pro",
    category: "businesses",
    subcategory: "shops",
    title: "Heavy Repair Shop — 6 Bays",
    summary: "Atlanta — equipment included",
    description: "Established heavy repair shop with lifts, tooling, and book of business.",
    price: 890000,
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 30,
    shippingAvailable: false,
    availability: "available",
    tags: ["business sale", "shop"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 130,
    createdAt: "2026-06-25T11:00:00.000Z",
    fraudFlags: [],
    specs: { Bays: "6", Lease: "Assignable" },
  }),
  L({
    id: "lst-biz-wash",
    sellerId: "sel-roadside-pro",
    category: "businesses",
    subcategory: "washes",
    title: "Truck Wash — Drive-through",
    summary: "High-volume corridor location",
    description: "Automated + manual wash on I-75 corridor with loyalty program.",
    price: 1250000,
    condition: "n_a",
    locationCity: "Macon",
    locationState: "GA",
    distanceMiles: 85,
    shippingAvailable: false,
    availability: "available",
    tags: ["business sale", "wash"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 180,
    createdAt: "2026-06-27T09:00:00.000Z",
    fraudFlags: [],
    specs: { Type: "Drive-through", Corridor: "I-75" },
  }),
  L({
    id: "lst-gov-rfq",
    sellerId: "sel-gov-surplus",
    category: "government",
    subcategory: "rfq",
    title: "Municipal Plow Truck RFQ",
    summary: "Qty 6 · sealed proposals",
    description: "City fleet RFQ for plow-ready chassis. Government channel listing.",
    price: 0,
    priceLabel: "RFQ — submit proposal",
    condition: "n_a",
    locationCity: "Washington",
    locationState: "DC",
    distanceMiles: 620,
    shippingAvailable: false,
    availability: "available",
    tags: ["government", "rfq"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 222,
    createdAt: "2026-07-04T10:00:00.000Z",
    endsAt: "2026-08-01T17:00:00.000Z",
    channel: "government",
    fraudFlags: [],
    specs: { Qty: "6", Process: "Sealed RFQ" },
  }),
  L({
    id: "lst-ent-rfq",
    sellerId: "sel-enterprise-fleet",
    category: "enterprise",
    subcategory: "rfq",
    title: "Enterprise Tire Contract RFQ",
    summary: "200 units / yr · national",
    description: "Multi-year tire supply RFQ for enterprise fleet. Volume pricing expected.",
    price: 0,
    priceLabel: "RFQ — volume contract",
    condition: "n_a",
    locationCity: "Columbus",
    locationState: "OH",
    distanceMiles: 280,
    shippingAvailable: false,
    availability: "available",
    tags: ["enterprise", "rfq", "tires"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 240,
    createdAt: "2026-07-06T09:00:00.000Z",
    endsAt: "2026-08-15T17:00:00.000Z",
    channel: "enterprise",
    fraudFlags: [],
    specs: { Volume: "200 / yr", Term: "3 years" },
  }),
  L({
    id: "lst-cascadia-20",
    sellerId: "sel-midwest-truck",
    category: "equipment",
    subcategory: "trucks",
    title: "2020 Freightliner Cascadia",
    summary: "Within 300 miles — used Cascadia",
    description: "Another Cascadia in the Midwest search radius for Alph comparisons.",
    price: 69500,
    condition: "used_good",
    year: 2020,
    make: "Freightliner",
    model: "Cascadia",
    mileage: 498000,
    locationCity: "Indianapolis",
    locationState: "IN",
    distanceMiles: 185,
    shippingAvailable: true,
    shippingEstimate: 1600,
    deliveryDays: 6,
    warrantyMonths: 1,
    availability: "available",
    tags: ["cascadia", "within300"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 208,
    createdAt: "2026-07-07T11:00:00.000Z",
    aiScore: 88,
    fraudFlags: [],
    specs: { Engine: "DD15", Miles: "498k" },
  }),
  L({
    id: "lst-cascadia-19",
    sellerId: "sel-midwest-truck",
    category: "equipment",
    subcategory: "trucks",
    title: "2019 Freightliner Cascadia",
    summary: "Within 300 miles — value pick",
    description: "Lower-priced Cascadia for Alph within-300-miles intent.",
    price: 58900,
    condition: "used_good",
    year: 2019,
    make: "Freightliner",
    model: "Cascadia",
    mileage: 612000,
    locationCity: "Fort Wayne",
    locationState: "IN",
    distanceMiles: 160,
    shippingAvailable: true,
    shippingEstimate: 1400,
    deliveryDays: 6,
    availability: "available",
    tags: ["cascadia", "within300"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 212,
    createdAt: "2026-07-07T11:10:00.000Z",
    aiScore: 82,
    fraudFlags: [],
    specs: { Engine: "DD13", Miles: "612k" },
  }),
  L({
    id: "lst-maint-provider",
    sellerId: "sel-roadside-pro",
    category: "services",
    subcategory: "pm",
    title: "Preventive Maintenance Contract",
    summary: "Compare maintenance providers",
    description: "Quarterly PM with parts markup transparency and Alph cost estimate.",
    price: 220,
    priceLabel: "From $220 / unit / visit",
    condition: "n_a",
    locationCity: "Atlanta",
    locationState: "GA",
    distanceMiles: 20,
    shippingAvailable: false,
    availability: "available",
    tags: ["pm", "maintenance", "compare"],
    featured: true,
    sponsored: false,
    boosted: false,
    imageHue: 145,
    createdAt: "2026-07-09T07:00:00.000Z",
    aiScore: 91,
    fraudFlags: [],
    specs: { Cadence: "Quarterly", Parts: "Transparent markup" },
  }),
  L({
    id: "lst-maint-provider-b",
    sellerId: "sel-midwest-truck",
    category: "services",
    subcategory: "pm",
    title: "Dealer PM Program",
    summary: "OEM techs — compare pick",
    description: "Dealer-backed PM with OEM parts preference.",
    price: 265,
    priceLabel: "From $265 / unit / visit",
    condition: "n_a",
    locationCity: "Chicago",
    locationState: "IL",
    distanceMiles: 40,
    shippingAvailable: false,
    availability: "available",
    tags: ["pm", "maintenance", "compare", "oem"],
    featured: false,
    sponsored: false,
    boosted: false,
    imageHue: 215,
    createdAt: "2026-07-09T07:10:00.000Z",
    aiScore: 86,
    fraudFlags: [],
    specs: { Cadence: "Quarterly", Techs: "OEM certified" },
  }),
];

export const seedOffers: ExchangeOffer[] = [
  {
    id: "off-1",
    listingId: "lst-cascadia-21",
    buyerName: "Jordan Reyes",
    sellerId: "sel-midwest-truck",
    amount: 75000,
    quantity: 1,
    message: "Cash close within 10 days if inspection passes.",
    status: "countered",
    kind: "standard",
    aiSuggestedAmount: 76000,
    history: [
      {
        at: "2026-07-12T10:00:00.000Z",
        actor: "buyer",
        action: "offer_sent",
        amount: 75000,
        note: "Initial offer",
      },
      {
        at: "2026-07-12T15:30:00.000Z",
        actor: "seller",
        action: "countered",
        amount: 77000,
        note: "Counter at $77k",
      },
      {
        at: "2026-07-13T09:00:00.000Z",
        actor: "alph",
        action: "ai_suggestion",
        amount: 76000,
        note: "Alph suggests $76k midpoint given comps",
      },
    ],
    createdAt: "2026-07-12T10:00:00.000Z",
    updatedAt: "2026-07-13T09:00:00.000Z",
  },
  {
    id: "off-2",
    listingId: "lst-turbo-oem",
    buyerName: "Jordan Reyes",
    sellerId: "sel-sunbelt-parts",
    amount: 1750,
    quantity: 4,
    message: "Fleet volume — 4 turbos this month.",
    status: "sent",
    kind: "fleet",
    aiSuggestedAmount: 1720,
    history: [
      {
        at: "2026-07-14T11:00:00.000Z",
        actor: "buyer",
        action: "offer_sent",
        amount: 1750,
        note: "Fleet pricing request",
      },
    ],
    createdAt: "2026-07-14T11:00:00.000Z",
    updatedAt: "2026-07-14T11:00:00.000Z",
  },
];

export const seedOrders: ExchangeOrder[] = [
  {
    id: "ord-1001",
    listingId: "lst-tires-emergency",
    sellerId: "sel-roadside-pro",
    buyerName: "Jordan Reyes",
    title: "Emergency Drive Tire Set (4)",
    amount: 1680,
    status: "shipped",
    paymentMode: "demo_card",
    paymentDemoLabel: "Demo card authorized — not charged",
    trackingNumber: "TRX-DEMO-88421",
    shippingCarrier: "Mobile install",
    warrantyMonths: 0,
    returnEligible: false,
    invoiceNumber: "INV-EX-88421",
    poNumber: "PO-4412",
    createdAt: "2026-07-11T08:00:00.000Z",
    updatedAt: "2026-07-15T14:00:00.000Z",
    events: [
      { at: "2026-07-11T08:00:00.000Z", label: "Quote accepted" },
      { at: "2026-07-11T08:05:00.000Z", label: "Demo payment authorized" },
      { at: "2026-07-12T09:00:00.000Z", label: "Tech dispatched" },
      { at: "2026-07-15T14:00:00.000Z", label: "Install scheduled / in transit" },
    ],
  },
  {
    id: "ord-1002",
    listingId: "lst-reefer-45k",
    sellerId: "sel-midwest-truck",
    buyerName: "Jordan Reyes",
    title: "2018 Utility 3000R Reefer Trailer",
    amount: 42900,
    status: "escrow_demo",
    paymentMode: "demo_escrow",
    paymentDemoLabel: "Escrow hold (demo) — verified seller gate passed",
    financingApplicationId: "fin-1",
    warrantyMonths: 1,
    returnEligible: false,
    invoiceNumber: "INV-EX-90012",
    poNumber: "PO-4420",
    createdAt: "2026-07-14T10:00:00.000Z",
    updatedAt: "2026-07-16T09:00:00.000Z",
    events: [
      { at: "2026-07-14T10:00:00.000Z", label: "PO issued" },
      { at: "2026-07-14T10:30:00.000Z", label: "Seller verification checked" },
      { at: "2026-07-15T12:00:00.000Z", label: "Escrow demo hold created" },
      { at: "2026-07-16T09:00:00.000Z", label: "Inspection window open" },
    ],
  },
  {
    id: "ord-1003",
    listingId: "lst-turbo-oem",
    sellerId: "sel-sunbelt-parts",
    buyerName: "Jordan Reyes",
    title: "OEM Holset HE400VG Turbocharger ×2",
    amount: 3790,
    status: "delivered",
    paymentMode: "demo_ach",
    paymentDemoLabel: "Demo ACH settled",
    trackingNumber: "UPS-DEMO-22190",
    shippingCarrier: "UPS",
    warrantyMonths: 12,
    returnEligible: true,
    invoiceNumber: "INV-EX-77110",
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-08T16:00:00.000Z",
    events: [
      { at: "2026-07-01T09:00:00.000Z", label: "Order placed" },
      { at: "2026-07-02T11:00:00.000Z", label: "Shipped" },
      { at: "2026-07-08T16:00:00.000Z", label: "Delivered" },
    ],
  },
];

export const seedFinancing: FinancingApplication[] = [
  {
    id: "fin-1",
    product: "trailer",
    amount: 42900,
    termMonths: 48,
    businessName: "Reyes Logistics LLC",
    contactName: "Jordan Reyes",
    listingId: "lst-reefer-45k",
    status: "under_review",
    createdAt: "2026-07-14T10:15:00.000Z",
    updatedAt: "2026-07-16T08:00:00.000Z",
    notes: "Demo pipeline — underwriter review simulated.",
  },
  {
    id: "fin-2",
    product: "working_capital",
    amount: 75000,
    termMonths: 12,
    businessName: "Reyes Logistics LLC",
    contactName: "Jordan Reyes",
    status: "approved_demo",
    createdAt: "2026-06-20T10:00:00.000Z",
    updatedAt: "2026-06-28T14:00:00.000Z",
    notes: "Approved (demo) — not a live credit decision.",
  },
];

export const seedAds: AdCampaign[] = [
  {
    id: "ad-1",
    listingId: "lst-cascadia-21",
    sellerId: "sel-midwest-truck",
    name: "Cascadia homepage boost",
    placement: "homepage",
    status: "live_demo",
    dailyBudget: 75,
    impressions: 12400,
    clicks: 318,
    spendDemo: 420,
  },
  {
    id: "ad-2",
    listingId: "lst-insurance",
    sellerId: "sel-insurance-lane",
    name: "Insurance category sponsor",
    placement: "category",
    status: "live_demo",
    dailyBudget: 40,
    impressions: 8200,
    clicks: 210,
    spendDemo: 260,
  },
  {
    id: "ad-3",
    sellerId: "sel-factor-first",
    name: "Sponsored business — FactorFirst",
    placement: "sponsored_business",
    status: "paused",
    dailyBudget: 55,
    impressions: 5100,
    clicks: 96,
    spendDemo: 180,
  },
];

export const seedMessages: ExchangeMessage[] = [
  {
    id: "msg-1",
    threadId: "thr-cascadia",
    listingId: "lst-cascadia-21",
    from: "Midwest Truck Center",
    to: "Jordan Reyes",
    body: "Inspection bay open Thursday 10am if you want to walk the Cascadia.",
    at: "2026-07-13T16:00:00.000Z",
    read: false,
  },
  {
    id: "msg-2",
    threadId: "thr-cascadia",
    listingId: "lst-cascadia-21",
    from: "Jordan Reyes",
    to: "Midwest Truck Center",
    body: "Book it — bringing our shop lead.",
    at: "2026-07-13T16:20:00.000Z",
    read: true,
  },
  {
    id: "msg-3",
    threadId: "thr-tires",
    listingId: "lst-tires-emergency",
    from: "Roadside Pro Mobile",
    to: "Jordan Reyes",
    body: "Tech ETA 45 minutes for the drive tire install.",
    at: "2026-07-15T13:40:00.000Z",
    read: true,
  },
];

export const seedReviews: ExchangeReview[] = [
  {
    id: "rev-1",
    sellerId: "sel-midwest-truck",
    listingId: "lst-dryvan-20",
    author: "A. Patel",
    rating: 5,
    body: "Clean paperwork and honest condition report. Would buy again.",
    at: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "rev-2",
    sellerId: "sel-sunbelt-parts",
    listingId: "lst-turbo-oem",
    author: "Jordan Reyes",
    rating: 5,
    body: "OEM turbo arrived fast, core return was painless.",
    at: "2026-07-09T10:00:00.000Z",
  },
  {
    id: "rev-3",
    sellerId: "sel-roadside-pro",
    author: "M. Chen",
    rating: 4,
    body: "Solid mobile tech — clear pricing before work started.",
    at: "2026-07-02T18:00:00.000Z",
  },
];

export const seedFavorites = ["lst-reefer-45k", "lst-cascadia-21", "lst-fuel-a", "lst-insurance"];

export const seedCompareIds = ["lst-fuel-a", "lst-fuel-b", "lst-fuel-c"];

export const seedSavedSearches: SavedSearch[] = [
  {
    id: "ss-1",
    name: "Reefers under $45k",
    query: "reefer",
    category: "equipment",
    maxPrice: 45000,
    verifiedOnly: true,
    createdAt: "2026-07-01T08:00:00.000Z",
  },
  {
    id: "ss-2",
    name: "Cascadias within 300 mi",
    query: "cascadia",
    category: "equipment",
    maxDistance: undefined,
    createdAt: "2026-07-05T08:00:00.000Z",
  },
];

export const seedAudit: AuditEntry[] = [
  {
    id: "aud-1",
    at: "2026-07-15T12:00:00.000Z",
    actor: "system",
    action: "escrow_demo_created",
    summary: "Demo escrow hold created for order ord-1002 (verified seller gate passed).",
    entityType: "order",
    entityId: "ord-1002",
  },
  {
    id: "aud-2",
    at: "2026-07-14T11:00:00.000Z",
    actor: "Jordan Reyes",
    action: "offer_sent",
    summary: "Fleet offer sent on OEM turbo listing.",
    entityType: "offer",
    entityId: "off-2",
  },
  {
    id: "aud-3",
    at: "2026-07-12T10:00:00.000Z",
    actor: "Jordan Reyes",
    action: "offer_sent",
    summary: "Offer sent on 2021 Cascadia.",
    entityType: "offer",
    entityId: "off-1",
  },
  {
    id: "aud-4",
    at: "2026-07-11T08:05:00.000Z",
    actor: "system",
    action: "payment_demo",
    summary: "Demo card authorization recorded — no live processor.",
    entityType: "order",
    entityId: "ord-1001",
  },
];

export const seedInsights: ExchangeInsight[] = [
  {
    id: "ins-1",
    title: "Used Cascadia values",
    summary: "Midwest asking prices softened ~3% vs last quarter.",
    metric: "$68.5k",
    deltaLabel: "−3% QoQ",
    tone: "info",
    series: [74, 72, 71, 70, 69, 68.5],
  },
  {
    id: "ins-2",
    title: "Reefer demand",
    summary: "Search interest for reefers under $50k is elevated heading into produce season.",
    metric: "+18%",
    deltaLabel: "vs 30 days ago",
    tone: "success",
    series: [40, 42, 48, 55, 60, 68],
  },
  {
    id: "ins-3",
    title: "Tire emergency pricing",
    summary: "Mobile install premiums up near major hubs — shop installs still cheaper.",
    metric: "+9%",
    deltaLabel: "mobile premium",
    tone: "warning",
    series: [100, 102, 105, 108, 109, 109],
  },
  {
    id: "ins-4",
    title: "Fuel card savings",
    summary: "Top three cards in seed inventory average 35–42¢/gal advertised savings.",
    metric: "42¢",
    deltaLabel: "best advertised",
    tone: "success",
    series: [32, 34, 36, 38, 40, 42],
  },
  {
    id: "ins-5",
    title: "Recommended purchase",
    summary: "Alph flags Utility reefer under $45k as best near-term equipment ROI.",
    metric: "lst-reefer-45k",
    deltaLabel: "AI confidence 97",
    tone: "info",
    series: [70, 78, 85, 90, 94, 97],
  },
];
