import { DEMO_TENANT_ID } from "@/lib/data/tenant";
import {
  seedBadges,
  seedIdentity,
  seedPassport,
  seedTrustScore,
  WALLET_OWNER_ID,
} from "@/lib/wallet/seed";
import { TRUST_SCORE_DISCLAIMER } from "@/lib/wallet/types";
import type {
  BusinessPassport,
  CommunityPost,
  NetworkAuditEntry,
  NetworkConnection,
  NetworkMember,
  NetworkRecommendation,
  ProfessionalPassport,
  ReputationReview,
  ReputationSummary,
  TrustStatusItem,
  TrustTimelineEvent,
  VerifiedExperience,
} from "@/lib/network/types";
import { REPUTATION_DISCLAIMER } from "@/lib/network/types";

export const NETWORK_TENANT_ID = DEMO_TENANT_ID;
export const NETWORK_OWNER_MEMBER_ID = "nm-jordan-reyes";
export const NETWORK_OWNER_TRANSPO_ID = "TVN-JR-2015-88421";

const NOW = "2026-07-17T12:00:00.000Z";

export const seedMembers: NetworkMember[] = [
  {
    id: NETWORK_OWNER_MEMBER_ID,
    transpoId: NETWORK_OWNER_TRANSPO_ID,
    kind: "person",
    category: "driver",
    displayName: seedIdentity.fullName,
    headline: seedIdentity.headline,
    initials: seedIdentity.photoInitials,
    city: seedIdentity.locationCity,
    state: seedIdentity.locationState,
    country: "US",
    languages: seedIdentity.languages,
    specializations: seedIdentity.specialSkills,
    equipment: seedIdentity.equipmentExperience,
    trailerTypes: seedIdentity.trailerExperience,
    yearsExperience: seedIdentity.yearsExperience,
    verification: "premium",
    trustScore: seedTrustScore.score,
    availability: "available",
    industry: "Trucking",
    services: ["OTR", "Regional", "Hazmat"],
    badges: seedBadges.map((b) => b.id),
    publicProfileConsent: true,
    walletLinked: true,
    createdAt: "2015-06-18T12:00:00.000Z",
  },
  {
    id: "nm-lone-star",
    transpoId: "TVN-CO-LSA-3482910",
    kind: "company",
    category: "carrier",
    displayName: "Lone Star Alpha Carrier",
    headline: "Regional dry van & reefer · San Antonio base",
    initials: "LS",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Reefer", "Dry van", "Dedicated"],
    equipment: ["Sleeper", "Day cab"],
    trailerTypes: ["Dry van", "Reefer"],
    yearsExperience: 14,
    fleetSize: 48,
    verification: "premium",
    trustScore: 91,
    availability: "available",
    industry: "Motor carrier",
    services: ["Asset carriage", "Dedicated lanes"],
    badges: ["company", "elite_carrier"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2012-03-01T12:00:00.000Z",
  },
  {
    id: "nm-maria-owner",
    transpoId: "TVN-OO-MC-77201",
    kind: "person",
    category: "owner_operator",
    displayName: "Maria Castillo",
    headline: "Owner-operator · flatbed specialist",
    initials: "MC",
    city: "Laredo",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Flatbed", "Oversized"],
    equipment: ["Sleeper"],
    trailerTypes: ["Flatbed", "Step deck"],
    yearsExperience: 9,
    fleetSize: 2,
    verification: "verified",
    trustScore: 88,
    availability: "limited",
    industry: "Trucking",
    services: ["Owner-operator capacity"],
    badges: ["owner_operator", "verified_driver"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2018-01-10T12:00:00.000Z",
  },
  {
    id: "nm-horizon-broker",
    transpoId: "TVN-BR-HZN-44102",
    kind: "company",
    category: "broker",
    displayName: "Horizon Freight Brokerage",
    headline: "Asset-light brokerage · South Central lanes",
    initials: "HF",
    city: "Dallas",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Reefer", "Expedite"],
    equipment: [],
    trailerTypes: ["Dry van", "Reefer"],
    yearsExperience: 11,
    verification: "verified",
    trustScore: 86,
    industry: "Brokerage",
    services: ["Spot", "Contract"],
    badges: ["broker", "partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2015-09-01T12:00:00.000Z",
  },
  {
    id: "nm-summit-shipper",
    transpoId: "TVN-SH-SMT-99012",
    kind: "company",
    category: "shipper",
    displayName: "Summit Foods Distribution",
    headline: "Cold-chain shipper · grocery & CPG",
    initials: "SF",
    city: "Houston",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Reefer", "Appointment delivery"],
    equipment: [],
    trailerTypes: ["Reefer"],
    yearsExperience: 22,
    verification: "verified",
    trustScore: 89,
    industry: "Shipper",
    services: ["Outbound freight"],
    badges: ["shipper", "partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2004-04-12T12:00:00.000Z",
  },
  {
    id: "nm-dispatch-pro",
    transpoId: "TVN-DC-DPR-55100",
    kind: "company",
    category: "dispatch_company",
    displayName: "Relay Dispatch Pros",
    headline: "Dispatch for OO & small fleets · reefer experience",
    initials: "RD",
    city: "Austin",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Reefer", "Owner-operator support"],
    equipment: [],
    trailerTypes: ["Reefer", "Dry van"],
    yearsExperience: 7,
    verification: "verified",
    trustScore: 84,
    industry: "Dispatch services",
    services: ["24/7 dispatch", "Load booking"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2019-06-01T12:00:00.000Z",
  },
  {
    id: "nm-forward-logix",
    transpoId: "TVN-FF-FLX-33011",
    kind: "company",
    category: "freight_forwarder",
    displayName: "Forward Logix",
    headline: "Domestic forwarding & intermodal coordination",
    initials: "FL",
    city: "Chicago",
    state: "IL",
    country: "US",
    languages: ["English"],
    specializations: ["Intermodal", "Drayage"],
    equipment: [],
    trailerTypes: ["Dry van"],
    yearsExperience: 16,
    verification: "basic",
    trustScore: 80,
    industry: "Freight forwarding",
    services: ["Door-to-door", "Customs coordination"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2010-02-01T12:00:00.000Z",
  },
  {
    id: "nm-cold-warehouse",
    transpoId: "TVN-WH-CWH-22001",
    kind: "company",
    category: "warehouse",
    displayName: "ColdVault Warehousing",
    headline: "Temperature-controlled warehouse · Houston",
    initials: "CV",
    city: "Houston",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Cold storage", "Cross-dock"],
    equipment: [],
    trailerTypes: ["Reefer"],
    yearsExperience: 12,
    verification: "verified",
    trustScore: 87,
    industry: "Warehousing",
    services: ["Storage", "Transload"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2014-08-01T12:00:00.000Z",
  },
  {
    id: "nm-reece-mech",
    transpoId: "TVN-ME-RM-66110",
    kind: "person",
    category: "mechanic",
    displayName: "Reece Nguyen",
    headline: "ASE master · reefer & heavy truck",
    initials: "RN",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English", "Vietnamese"],
    specializations: ["Reefer units", "Diesel diagnostics"],
    equipment: ["Heavy truck"],
    trailerTypes: ["Reefer"],
    yearsExperience: 13,
    verification: "premium",
    trustScore: 94,
    availability: "available",
    industry: "Maintenance",
    services: ["Shop repair", "PM programs"],
    badges: ["mechanic", "top_rated", "technician"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2013-05-01T12:00:00.000Z",
  },
  {
    id: "nm-mobile-fix",
    transpoId: "TVN-MM-TF-77821",
    kind: "person",
    category: "mobile_mechanic",
    displayName: "Tasha Freeman",
    headline: "Mobile roadside · within 50 mi of SA",
    initials: "TF",
    city: "New Braunfels",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Roadside", "Reefer emergency"],
    equipment: ["Service van"],
    trailerTypes: ["Reefer", "Dry van"],
    yearsExperience: 8,
    verification: "verified",
    trustScore: 90,
    availability: "available",
    industry: "Mobile maintenance",
    services: ["24/7 mobile", "Trailer repair"],
    badges: ["mechanic", "top_rated"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2018-11-01T12:00:00.000Z",
  },
  {
    id: "nm-texas-trucks",
    transpoId: "TVN-TD-TTD-44110",
    kind: "company",
    category: "truck_dealer",
    displayName: "Texas Premier Trucks",
    headline: "New & used Class 8 dealer",
    initials: "TP",
    city: "Fort Worth",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Class 8", "Lease"],
    equipment: ["Sleeper", "Day cab"],
    trailerTypes: [],
    yearsExperience: 20,
    verification: "verified",
    trustScore: 85,
    industry: "Equipment sales",
    services: ["Sales", "Financing desk"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2006-01-01T12:00:00.000Z",
  },
  {
    id: "nm-trailer-hub",
    transpoId: "TVN-TR-THB-55200",
    kind: "company",
    category: "trailer_dealer",
    displayName: "TrailerHub Southwest",
    headline: "Reefer & dry van trailer sales",
    initials: "TH",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Reefer trailers", "Rentals"],
    equipment: [],
    trailerTypes: ["Reefer", "Dry van"],
    yearsExperience: 15,
    verification: "basic",
    trustScore: 81,
    industry: "Equipment sales",
    services: ["Sales", "Rentals"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2011-07-01T12:00:00.000Z",
  },
  {
    id: "nm-parts-direct",
    transpoId: "TVN-PT-PD-66300",
    kind: "company",
    category: "parts",
    displayName: "PartsDirect Fleet",
    headline: "OEM & aftermarket heavy-duty parts",
    initials: "PD",
    city: "Dallas",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Brake", "Reefer parts"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 18,
    verification: "verified",
    trustScore: 83,
    industry: "Parts",
    services: ["Same-day local", "Fleet accounts"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2008-03-01T12:00:00.000Z",
  },
  {
    id: "nm-guard-ins",
    transpoId: "TVN-IN-GI-77400",
    kind: "company",
    category: "insurance",
    displayName: "GuardPath Insurance",
    headline: "Motor carrier liability & cargo · fleets 10–200",
    initials: "GP",
    city: "Austin",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Liability", "Cargo", "Occupational accident"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 25,
    verification: "premium",
    trustScore: 92,
    industry: "Insurance",
    services: ["Quotes", "Claims advocacy"],
    badges: ["partner", "premium_partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2001-05-01T12:00:00.000Z",
  },
  {
    id: "nm-quick-factor",
    transpoId: "TVN-FA-QF-88500",
    kind: "company",
    category: "factoring",
    displayName: "QuickLane Factoring",
    headline: "Non-recourse factoring for carriers",
    initials: "QL",
    city: "Phoenix",
    state: "AZ",
    country: "US",
    languages: ["English"],
    specializations: ["Non-recourse", "Fuel advances"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 10,
    verification: "verified",
    trustScore: 84,
    industry: "Factoring",
    services: ["Invoice funding"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2016-09-01T12:00:00.000Z",
  },
  {
    id: "nm-fuel-plus",
    transpoId: "TVN-FU-FP-99600",
    kind: "company",
    category: "fuel_card",
    displayName: "FuelPlus Network",
    headline: "Fuel cards & IFTA-ready reporting",
    initials: "FP",
    city: "Denver",
    state: "CO",
    country: "US",
    languages: ["English"],
    specializations: ["Retail diesel", "IFTA"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 14,
    verification: "verified",
    trustScore: 86,
    industry: "Fuel",
    services: ["Fuel cards", "Rebates"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2012-11-01T12:00:00.000Z",
  },
  {
    id: "nm-cargo-bank",
    transpoId: "TVN-BK-CB-10700",
    kind: "company",
    category: "bank",
    displayName: "Cargo Capital Bank",
    headline: "Equipment lending & working capital",
    initials: "CC",
    city: "Dallas",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Equipment loans", "Lines of credit"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 30,
    verification: "verified",
    trustScore: 88,
    industry: "Banking",
    services: ["Lending", "Treasury"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "1995-01-01T12:00:00.000Z",
  },
  {
    id: "nm-comply-right",
    transpoId: "TVN-CM-CR-21800",
    kind: "company",
    category: "compliance",
    displayName: "ComplyRight Logistics",
    headline: "DOT compliance programs for fleets",
    initials: "CR",
    city: "Oklahoma City",
    state: "OK",
    country: "US",
    languages: ["English"],
    specializations: ["DOT audit prep", "DQF"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 9,
    verification: "verified",
    trustScore: 87,
    industry: "Compliance",
    services: ["Audit prep", "Policy manuals"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2017-04-01T12:00:00.000Z",
  },
  {
    id: "nm-elena-safety",
    transpoId: "TVN-SC-ES-32900",
    kind: "person",
    category: "safety_consultant",
    displayName: "Elena Vasquez",
    headline: "Bilingual safety consultant · CSA & training",
    initials: "EV",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["CSA", "Driver training", "Accident investigation"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 17,
    verification: "premium",
    trustScore: 93,
    availability: "available",
    industry: "Safety",
    services: ["Consulting", "On-site training"],
    badges: ["safety_manager", "top_rated"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2009-08-01T12:00:00.000Z",
  },
  {
    id: "nm-kai-recruiter",
    transpoId: "TVN-RC-KR-43000",
    kind: "person",
    category: "recruiter",
    displayName: "Kai Morgan",
    headline: "Driver recruiter · hazmat & regional",
    initials: "KM",
    city: "Houston",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["CDL-A", "Hazmat hiring"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 6,
    verification: "verified",
    trustScore: 82,
    availability: "available",
    industry: "Recruiting",
    services: ["Sourcing", "Screening"],
    badges: ["recruiter"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2020-02-01T12:00:00.000Z",
  },
  {
    id: "nm-devon-dispatch",
    transpoId: "TVN-DI-DD-54100",
    kind: "person",
    category: "dispatcher",
    displayName: "Devon Blake",
    headline: "Senior dispatcher · reefer & appointments",
    initials: "DB",
    city: "Austin",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Reefer", "Appointment freight"],
    equipment: [],
    trailerTypes: ["Reefer"],
    yearsExperience: 10,
    verification: "verified",
    trustScore: 89,
    availability: "limited",
    industry: "Dispatch",
    services: ["Fleet dispatch"],
    badges: ["dispatcher", "top_rated"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2016-05-01T12:00:00.000Z",
  },
  {
    id: "nm-alex-fleet",
    transpoId: "TVN-FM-AC-65200",
    kind: "person",
    category: "fleet_manager",
    displayName: "Alex Chen",
    headline: "Fleet manager · 40–80 unit fleets",
    initials: "AC",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Utilization", "Maintenance planning"],
    equipment: ["Sleeper"],
    trailerTypes: ["Dry van", "Reefer"],
    yearsExperience: 12,
    verification: "verified",
    trustScore: 90,
    availability: "unavailable",
    industry: "Fleet operations",
    services: ["Fleet leadership"],
    badges: ["fleet_manager"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2014-01-01T12:00:00.000Z",
  },
  {
    id: "nm-priya-cpa",
    transpoId: "TVN-AC-PP-76300",
    kind: "person",
    category: "accountant",
    displayName: "Priya Patel",
    headline: "Transportation CPA · IFTA & owner-ops",
    initials: "PP",
    city: "Dallas",
    state: "TX",
    country: "US",
    languages: ["English", "Hindi"],
    specializations: ["IFTA", "Owner-operator books"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 11,
    verification: "verified",
    trustScore: 91,
    availability: "available",
    industry: "Accounting",
    services: ["Bookkeeping", "Tax"],
    badges: ["partner", "top_rated"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2015-03-01T12:00:00.000Z",
  },
  {
    id: "nm-paylane",
    transpoId: "TVN-PR-PL-87400",
    kind: "company",
    category: "payroll",
    displayName: "PayLane Driver Payroll",
    headline: "Driver settlement & contractor pay",
    initials: "PL",
    city: "Atlanta",
    state: "GA",
    country: "US",
    languages: ["English"],
    specializations: ["Settlements", "1099"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 8,
    verification: "basic",
    trustScore: 79,
    industry: "Payroll",
    services: ["Payroll", "Settlements"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2018-07-01T12:00:00.000Z",
  },
  {
    id: "nm-lane-law",
    transpoId: "TVN-LW-LL-98500",
    kind: "company",
    category: "law",
    displayName: "Lane & Cargo Law",
    headline: "Transportation counsel · FMCSA & contracts",
    initials: "LC",
    city: "Chicago",
    state: "IL",
    country: "US",
    languages: ["English"],
    specializations: ["FMCSA", "Cargo claims"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 22,
    verification: "verified",
    trustScore: 90,
    industry: "Legal",
    services: ["Counsel", "Litigation support"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2004-09-01T12:00:00.000Z",
  },
  {
    id: "nm-transpo-soft",
    transpoId: "TVN-SW-TS-09600",
    kind: "company",
    category: "software",
    displayName: "Transpo.ai",
    headline: "Operations platform for modern carriers",
    initials: "TA",
    city: "Austin",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["TMS alternative", "Compliance", "Network"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 5,
    verification: "premium",
    trustScore: 95,
    industry: "Software",
    services: ["SaaS platform"],
    badges: ["partner", "premium_partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2021-01-01T12:00:00.000Z",
  },
  {
    id: "nm-eld-sync",
    transpoId: "TVN-EL-ES-10710",
    kind: "company",
    category: "eld",
    displayName: "SyncELD Systems",
    headline: "ELD hardware & compliance logging",
    initials: "SE",
    city: "Kansas City",
    state: "MO",
    country: "US",
    languages: ["English"],
    specializations: ["ELD", "HOS"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 9,
    verification: "verified",
    trustScore: 85,
    industry: "ELD",
    services: ["Devices", "Support"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2017-10-01T12:00:00.000Z",
  },
  {
    id: "nm-telematics-one",
    transpoId: "TVN-TM-TO-21810",
    kind: "company",
    category: "telematics",
    displayName: "Telematics One",
    headline: "GPS, cameras & utilization analytics",
    initials: "T1",
    city: "Phoenix",
    state: "AZ",
    country: "US",
    languages: ["English"],
    specializations: ["Cameras", "Geofencing"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 11,
    verification: "verified",
    trustScore: 86,
    industry: "Telematics",
    services: ["Hardware", "Analytics"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2015-12-01T12:00:00.000Z",
  },
  {
    id: "nm-fmcsa-info",
    transpoId: "TVN-GV-FM-32910",
    kind: "company",
    category: "government",
    displayName: "FMCSA Information Desk (demo)",
    headline: "Public motor carrier information reference",
    initials: "FM",
    city: "Washington",
    state: "DC",
    country: "US",
    languages: ["English"],
    specializations: ["Authority", "Safety data"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 50,
    verification: "basic",
    trustScore: 70,
    industry: "Government",
    services: ["Public records"],
    badges: [],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2000-01-01T12:00:00.000Z",
  },
  {
    id: "nm-cdl-academy",
    transpoId: "TVN-TR-CA-43010",
    kind: "company",
    category: "training_cdl",
    displayName: "Alamo CDL Academy",
    headline: "CDL-A training · hazmat endorsements",
    initials: "AA",
    city: "San Antonio",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["CDL-A", "Hazmat"],
    equipment: ["Sleeper"],
    trailerTypes: ["Dry van"],
    yearsExperience: 13,
    verification: "verified",
    trustScore: 88,
    industry: "Training",
    services: ["CDL school", "Refresher"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2013-02-01T12:00:00.000Z",
  },
  {
    id: "nm-ata-chapter",
    transpoId: "TVN-AS-TX-54110",
    kind: "company",
    category: "association",
    displayName: "Texas Trucking Association (demo)",
    headline: "Industry association · advocacy & education",
    initials: "TT",
    city: "Austin",
    state: "TX",
    country: "US",
    languages: ["English"],
    specializations: ["Advocacy", "Education"],
    equipment: [],
    trailerTypes: [],
    yearsExperience: 40,
    verification: "verified",
    trustScore: 84,
    industry: "Association",
    services: ["Membership", "Events"],
    badges: ["partner"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "1980-01-01T12:00:00.000Z",
  },
  {
    id: "nm-sam-hazmat",
    transpoId: "TVN-DR-SO-65210",
    kind: "person",
    category: "driver",
    displayName: "Sam Ortiz",
    headline: "Hazmat driver · available now · bilingual",
    initials: "SO",
    city: "Houston",
    state: "TX",
    country: "US",
    languages: ["English", "Spanish"],
    specializations: ["Hazmat", "Tanker"],
    equipment: ["Sleeper"],
    trailerTypes: ["Tanker", "Dry van"],
    yearsExperience: 7,
    verification: "verified",
    trustScore: 87,
    availability: "available",
    industry: "Trucking",
    services: ["OTR hazmat"],
    badges: ["verified_driver"],
    publicProfileConsent: true,
    walletLinked: false,
    createdAt: "2019-04-01T12:00:00.000Z",
  },
];

export const seedBusinessPassports: BusinessPassport[] = [
  {
    memberId: "nm-lone-star",
    legalName: "Lone Star Alpha Carrier LLC",
    dba: "Lone Star Alpha",
    dotNumber: "USDOT-3482910",
    mcNumber: "MC-927451",
    fleetSize: 48,
    yearsInBusiness: 14,
    safetyRating: "Satisfactory",
    insuranceSummary: "$1M CSL auto liability · $100k cargo · current COI on file",
    authorityStatus: "Active common & contract authority",
    certifications: ["SmartWay", "CTPAT applicant"],
    licenses: ["TX intrastate", "IFTA"],
    coverageAreas: ["TX", "OK", "LA", "AR", "NM", "AZ"],
    services: ["Dry van", "Reefer", "Dedicated"],
    locations: ["San Antonio, TX (HQ)", "Dallas satellite yard"],
    photoPlaceholders: ["Yard aerial", "Shop bay", "Team photo"],
    videoPlaceholders: ["Safety culture walkthrough"],
    awards: [
      { id: "ba-1", title: "Regional Safe Fleet", year: "2025", issuer: "State trucking association" },
      { id: "ba-2", title: "Broker Preferred Carrier", year: "2024", issuer: "Horizon Freight" },
    ],
    completedProjects: [
      {
        id: "bp-1",
        title: "Summit Foods dedicated reefer",
        year: "2025",
        summary: "12-truck dedicated lane with 98.4% on-time appointments.",
      },
    ],
    timeline: [
      {
        id: "bt-1",
        date: "2012-03-01",
        title: "Authority granted",
        detail: "MC and DOT authority activated.",
        verified: true,
      },
      {
        id: "bt-2",
        date: "2019-06-01",
        title: "Reefer program launch",
        detail: "Added temperature-controlled fleet segment.",
        verified: true,
      },
      {
        id: "bt-3",
        date: "2024-11-01",
        title: "Transpo Verified Network join",
        detail: "Business Passport published with consent.",
        verified: true,
      },
    ],
    trustScore: 91,
    partnerReviewCount: 14,
  },
  {
    memberId: "nm-horizon-broker",
    legalName: "Horizon Freight Brokerage Inc.",
    dotNumber: "USDOT-9912044",
    mcNumber: "MC-441028",
    fleetSize: 0,
    yearsInBusiness: 11,
    safetyRating: "N/A (broker)",
    insuranceSummary: "Broker bond active · cargo contingent coverage",
    authorityStatus: "Active broker authority",
    certifications: ["TIA member"],
    licenses: ["Broker MC"],
    coverageAreas: ["South Central US"],
    services: ["Spot", "Contract", "Reefer"],
    locations: ["Dallas, TX"],
    photoPlaceholders: ["Ops floor"],
    videoPlaceholders: [],
    awards: [{ id: "ba-h1", title: "Carrier Choice Broker", year: "2025", issuer: "Peer survey" }],
    completedProjects: [
      {
        id: "bp-h1",
        title: "Peak produce season coverage",
        year: "2025",
        summary: "Sourced 200+ reefer loads with verified carriers.",
      },
    ],
    timeline: [
      {
        id: "bt-h1",
        date: "2015-09-01",
        title: "Broker authority",
        detail: "MC broker authority granted.",
        verified: true,
      },
    ],
    trustScore: 86,
    partnerReviewCount: 22,
  },
  {
    memberId: "nm-guard-ins",
    legalName: "GuardPath Insurance Agency LLC",
    fleetSize: 0,
    yearsInBusiness: 25,
    insuranceSummary: "Admitted carriers for trucking liability & cargo",
    authorityStatus: "Licensed TX / multi-state surplus lines",
    certifications: ["Licensed agency"],
    licenses: ["TX P&C"],
    coverageAreas: ["TX", "OK", "LA", "NM", "AR"],
    services: ["Liability", "Cargo", "Occupational accident"],
    locations: ["Austin, TX"],
    photoPlaceholders: ["Team"],
    videoPlaceholders: ["Claims process overview"],
    awards: [],
    completedProjects: [
      {
        id: "bp-g1",
        title: "Mid-size fleet renewal program",
        year: "2026",
        summary: "Structured coverage for fleets 10–200 power units.",
      },
    ],
    timeline: [
      {
        id: "bt-g1",
        date: "2001-05-01",
        title: "Agency founded",
        detail: "Specialized in motor carriers from day one.",
        verified: true,
      },
    ],
    trustScore: 92,
    partnerReviewCount: 31,
  },
];

export const seedProfessionalPassports: ProfessionalPassport[] = [
  {
    memberId: NETWORK_OWNER_MEMBER_ID,
    fullName: seedIdentity.fullName,
    headline: seedIdentity.headline,
    yearsExperience: seedIdentity.yearsExperience,
    skills: seedIdentity.specialSkills,
    equipment: seedIdentity.equipmentExperience,
    trailerTypes: seedIdentity.trailerExperience,
    routes: seedIdentity.statesDriven,
    languages: seedIdentity.languages,
    education: ["High school diploma", "CDL-A training — Alamo CDL Academy"],
    training: seedPassport.trainingHighlights,
    certifications: ["CDL-A", "Hazmat", "TWIC", "DOT medical"],
    awards: seedPassport.awards,
    employment: seedPassport.companies.map((c) => ({
      id: c.id,
      company: c.name,
      role: c.role,
      startDate: c.startDate,
      endDate: c.endDate,
      current: c.current,
      verified: c.verified,
    })),
    timeline: seedPassport.timeline.map((t) => ({
      id: t.id,
      date: t.date,
      title: t.title,
      detail: t.detail,
      kind: t.kind,
      verified: t.verified,
    })),
    milestones: seedPassport.achievements,
    trustScore: seedTrustScore.score,
    walletPassportLinked: true,
  },
  {
    memberId: "nm-reece-mech",
    fullName: "Reece Nguyen",
    headline: "ASE master · reefer & heavy truck",
    yearsExperience: 13,
    skills: ["Reefer units", "Diesel diagnostics", "PM programs"],
    equipment: ["Heavy truck", "Service bay"],
    trailerTypes: ["Reefer"],
    routes: ["TX metro service"],
    languages: ["English", "Vietnamese"],
    education: ["ASE Master certification track"],
    training: ["Thermo King", "Carrier Transicold"],
    certifications: ["ASE Master", "EPA 609"],
    awards: [
      { id: "pa-r1", title: "Top shop tech", year: "2024", issuer: "Lone Star Alpha" },
    ],
    employment: [
      {
        id: "pe-r1",
        company: "Lone Star Alpha Carrier",
        role: "Lead diesel technician",
        startDate: "2019-01-01",
        current: true,
        verified: true,
      },
    ],
    timeline: [
      {
        id: "pt-r1",
        date: "2013-05-01",
        title: "Entered heavy diesel",
        detail: "Started as apprentice tech.",
        kind: "employment",
        verified: true,
      },
    ],
    milestones: ["13 years diesel", "Reefer specialist"],
    trustScore: 94,
    walletPassportLinked: false,
  },
  {
    memberId: "nm-elena-safety",
    fullName: "Elena Vasquez",
    headline: "Bilingual safety consultant · CSA & training",
    yearsExperience: 17,
    skills: ["CSA", "Accident investigation", "Driver coaching"],
    equipment: [],
    trailerTypes: [],
    routes: ["TX", "OK", "NM"],
    languages: ["English", "Spanish"],
    education: ["B.S. Occupational Safety"],
    training: ["NSC instructor", "FMCSA auditor workshop"],
    certifications: ["CSP candidate", "NSC instructor"],
    awards: [],
    employment: [
      {
        id: "pe-e1",
        company: "Independent consultant",
        role: "Safety consultant",
        startDate: "2018-01-01",
        current: true,
        verified: true,
      },
    ],
    timeline: [
      {
        id: "pt-e1",
        date: "2009-08-01",
        title: "Safety career start",
        detail: "Began as fleet safety coordinator.",
        kind: "employment",
        verified: true,
      },
    ],
    milestones: ["17 years safety", "Bilingual programs"],
    trustScore: 93,
    walletPassportLinked: false,
  },
  {
    memberId: "nm-sam-hazmat",
    fullName: "Sam Ortiz",
    headline: "Hazmat driver · available now · bilingual",
    yearsExperience: 7,
    skills: ["Hazmat", "Tanker", "Team ready"],
    equipment: ["Sleeper"],
    trailerTypes: ["Tanker", "Dry van"],
    routes: ["TX", "LA", "OK", "AR"],
    languages: ["English", "Spanish"],
    education: ["CDL-A"],
    training: ["Hazmat endorsement course"],
    certifications: ["CDL-A", "Hazmat", "Tanker"],
    awards: [],
    employment: [
      {
        id: "pe-s1",
        company: "Gulf Coast Tank",
        role: "Hazmat driver",
        startDate: "2021-03-01",
        endDate: "2026-05-01",
        verified: true,
      },
    ],
    timeline: [
      {
        id: "pt-s1",
        date: "2019-04-01",
        title: "CDL issued",
        detail: "Class A with hazmat path.",
        kind: "certification",
        verified: true,
      },
    ],
    milestones: ["Available for hire", "Clean MVR signals (consent-gated)"],
    trustScore: 87,
    walletPassportLinked: false,
  },
];

export const seedExperiences: VerifiedExperience[] = [
  {
    id: "ex-1",
    subjectMemberId: NETWORK_OWNER_MEMBER_ID,
    verifierMemberId: "nm-alex-fleet",
    verifierName: "Alex Chen",
    companyName: "Lone Star Alpha Carrier",
    position: "CDL-A Driver",
    startDate: "2022-01-15",
    safetyNotes: "Zero preventable accidents during tenure.",
    equipment: ["Sleeper", "Automatic"],
    miles: 420000,
    training: ["Defensive driving", "Hazmat awareness"],
    projects: ["Summit Foods dedicated reefer support"],
    achievements: ["On-time > 97%"],
    referenceNote: "Would rehire without hesitation.",
    status: "confirmed",
    requestedAt: "2026-06-01T10:00:00.000Z",
    confirmedAt: "2026-06-03T15:00:00.000Z",
  },
  {
    id: "ex-2",
    subjectMemberId: NETWORK_OWNER_MEMBER_ID,
    verifierMemberId: "nm-kai-recruiter",
    verifierName: "Kai Morgan",
    companyName: "Horizon Freight Lines",
    position: "Contract driver (seasonal)",
    startDate: "2020-03-01",
    endDate: "2021-11-30",
    miles: 180000,
    status: "requested",
    requestedAt: "2026-07-10T09:00:00.000Z",
  },
  {
    id: "ex-3",
    subjectMemberId: "nm-reece-mech",
    verifierMemberId: "nm-alex-fleet",
    verifierName: "Alex Chen",
    companyName: "Lone Star Alpha Carrier",
    position: "Lead diesel technician",
    startDate: "2019-01-01",
    safetyNotes: "Shop safety lead; zero lost-time incidents under supervision.",
    equipment: ["Heavy truck", "Reefer units"],
    achievements: ["Reduced roadside failures 18% YoY"],
    status: "confirmed",
    requestedAt: "2026-05-01T10:00:00.000Z",
    confirmedAt: "2026-05-02T11:00:00.000Z",
  },
];

const defaultScores = {
  safety: 0,
  professionalism: 0,
  communication: 0,
  reliability: 0,
  on_time: 0,
  compliance: 0,
  customer_service: 0,
  leadership: 0,
  technical_skills: 0,
  overall: 0,
};

export const seedReviews: ReputationReview[] = [
  {
    id: "rr-1",
    subjectMemberId: NETWORK_OWNER_MEMBER_ID,
    authorMemberId: "nm-alex-fleet",
    authorName: "Alex Chen",
    authorRole: "Fleet Manager",
    verifiedInteractionId: "conn-1",
    scores: {
      ...defaultScores,
      safety: 96,
      professionalism: 94,
      communication: 92,
      reliability: 95,
      on_time: 93,
      compliance: 94,
      customer_service: 90,
      leadership: 85,
      technical_skills: 88,
      overall: 94,
    },
    body: "Jordan communicates early, protects equipment, and hits appointments. Verified from completed employment.",
    createdAt: "2026-01-14T12:00:00.000Z",
  },
  {
    id: "rr-2",
    subjectMemberId: "nm-reece-mech",
    authorMemberId: "nm-lone-star",
    authorName: "Lone Star Alpha Carrier",
    authorRole: "Carrier",
    verifiedInteractionId: "conn-3",
    scores: {
      ...defaultScores,
      safety: 95,
      professionalism: 96,
      communication: 93,
      reliability: 97,
      on_time: 94,
      compliance: 92,
      customer_service: 91,
      leadership: 90,
      technical_skills: 98,
      overall: 96,
    },
    body: "Best reefer tech in our shop network. Diagnoses fast and documents clearly.",
    createdAt: "2026-03-02T12:00:00.000Z",
  },
  {
    id: "rr-3",
    subjectMemberId: "nm-elena-safety",
    authorMemberId: "nm-lone-star",
    authorName: "Lone Star Alpha Carrier",
    authorRole: "Carrier",
    verifiedInteractionId: "conn-4",
    scores: {
      ...defaultScores,
      safety: 98,
      professionalism: 95,
      communication: 96,
      reliability: 94,
      on_time: 90,
      compliance: 97,
      customer_service: 93,
      leadership: 96,
      technical_skills: 92,
      overall: 95,
    },
    body: "Elena rebuilt our bilingual safety onboarding. Clear, practical, audit-ready.",
    createdAt: "2026-04-18T12:00:00.000Z",
  },
];

export const seedReputationSummaries: ReputationSummary[] = [
  {
    memberId: NETWORK_OWNER_MEMBER_ID,
    averages: seedReviews[0].scores,
    reviewCount: 1,
    alphSummary:
      "Alph summary: Jordan shows strong verified safety and reliability signals from completed employment with Lone Star Alpha. Communication and on-time performance are consistently high. Use as decision support alongside interviews and authorized document review — never as an automatic hire/no-hire gate.",
    disclaimer: REPUTATION_DISCLAIMER,
  },
  {
    memberId: "nm-reece-mech",
    averages: seedReviews[1].scores,
    reviewCount: 1,
    alphSummary:
      "Alph summary: Reece ranks among the strongest reefer and diesel technicians in the San Antonio directory, with exceptional technical skills and reliability from a verified carrier relationship.",
    disclaimer: REPUTATION_DISCLAIMER,
  },
  {
    memberId: "nm-elena-safety",
    averages: seedReviews[2].scores,
    reviewCount: 1,
    alphSummary:
      "Alph summary: Elena is a bilingual safety consultant with top compliance and leadership scores from verified carrier engagements. Strong fit for CSA coaching and driver training programs.",
    disclaimer: REPUTATION_DISCLAIMER,
  },
];

export const seedConnections: NetworkConnection[] = [
  {
    id: "conn-1",
    fromMemberId: "nm-lone-star",
    toMemberId: NETWORK_OWNER_MEMBER_ID,
    type: "carrier_driver",
    status: "accepted",
    message: "Employment and operations connection.",
    requestedAt: "2022-01-10T12:00:00.000Z",
    respondedAt: "2022-01-11T12:00:00.000Z",
    consentGranted: true,
  },
  {
    id: "conn-2",
    fromMemberId: "nm-horizon-broker",
    toMemberId: "nm-lone-star",
    type: "broker_carrier",
    status: "accepted",
    requestedAt: "2023-04-01T12:00:00.000Z",
    respondedAt: "2023-04-02T12:00:00.000Z",
    consentGranted: true,
  },
  {
    id: "conn-3",
    fromMemberId: "nm-lone-star",
    toMemberId: "nm-reece-mech",
    type: "carrier_mechanic",
    status: "accepted",
    requestedAt: "2019-02-01T12:00:00.000Z",
    respondedAt: "2019-02-02T12:00:00.000Z",
    consentGranted: true,
  },
  {
    id: "conn-4",
    fromMemberId: "nm-lone-star",
    toMemberId: "nm-elena-safety",
    type: "vendor_client",
    status: "accepted",
    requestedAt: "2024-01-15T12:00:00.000Z",
    respondedAt: "2024-01-16T12:00:00.000Z",
    consentGranted: true,
  },
  {
    id: "conn-5",
    fromMemberId: "nm-guard-ins",
    toMemberId: "nm-lone-star",
    type: "carrier_insurance",
    status: "accepted",
    requestedAt: "2020-06-01T12:00:00.000Z",
    respondedAt: "2020-06-02T12:00:00.000Z",
    consentGranted: true,
  },
  {
    id: "conn-6",
    fromMemberId: "nm-kai-recruiter",
    toMemberId: NETWORK_OWNER_MEMBER_ID,
    type: "recruiter_driver",
    status: "pending",
    message: "Would like to connect for a regional hazmat opportunity.",
    requestedAt: "2026-07-15T10:00:00.000Z",
    consentGranted: false,
  },
  {
    id: "conn-7",
    fromMemberId: "nm-fuel-plus",
    toMemberId: "nm-lone-star",
    type: "carrier_fuel",
    status: "pending",
    message: "Fleet fuel card program intro.",
    requestedAt: "2026-07-16T08:00:00.000Z",
    consentGranted: false,
  },
];

export const seedRecommendations: NetworkRecommendation[] = [
  {
    id: "rec-1",
    subjectMemberId: NETWORK_OWNER_MEMBER_ID,
    authorMemberId: "nm-alex-fleet",
    authorName: "Alex Chen",
    authorRole: "Fleet Manager",
    body: "Jordan is the driver I trust on appointment-sensitive reefer freight. Professional, calm under pressure, and bilingual with customers when needed.",
    attributed: true,
    verified: true,
    createdAt: "2026-01-20T12:00:00.000Z",
  },
  {
    id: "rec-2",
    subjectMemberId: "nm-devon-dispatch",
    authorMemberId: "nm-dispatch-pro",
    authorName: "Relay Dispatch Pros",
    authorRole: "Dispatch Company",
    body: "Devon runs a tight reefer board. Clear ETAs and excellent broker communication.",
    attributed: true,
    verified: true,
    createdAt: "2025-11-02T12:00:00.000Z",
  },
  {
    id: "rec-3",
    subjectMemberId: "nm-reece-mech",
    authorMemberId: "nm-mobile-fix",
    authorName: "Tasha Freeman",
    authorRole: "Mobile Mechanic",
    body: "When I need a second opinion on a reefer unit, Reece is my first call. Thorough and respectful on shared jobs.",
    attributed: true,
    verified: true,
    createdAt: "2026-02-10T12:00:00.000Z",
  },
  {
    id: "rec-4",
    subjectMemberId: "nm-kai-recruiter",
    authorMemberId: "nm-horizon-broker",
    authorName: "Horizon Freight Brokerage",
    authorRole: "Broker",
    body: "Kai sources verified drivers quickly and sets realistic expectations with carriers.",
    attributed: true,
    verified: true,
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    id: "rec-5",
    subjectMemberId: "nm-priya-cpa",
    authorMemberId: "nm-maria-owner",
    authorName: "Maria Castillo",
    authorRole: "Owner Operator",
    body: "Priya made IFTA and quarterly estimates painless. Clear explanations without jargon.",
    attributed: true,
    verified: true,
    createdAt: "2026-03-22T12:00:00.000Z",
  },
];

export const seedCommunityPosts: CommunityPost[] = [
  {
    id: "cp-1",
    authorMemberId: "nm-lone-star",
    authorName: "Lone Star Alpha Carrier",
    authorCategory: "carrier",
    kind: "hiring",
    title: "Hiring CDL-A regional reefer drivers",
    body: "San Antonio base. Prefer hazmat. Apply via Workforce or connect on Verified Network.",
    createdAt: "2026-07-16T14:00:00.000Z",
    followerOnly: false,
    likes: 12,
  },
  {
    id: "cp-2",
    authorMemberId: "nm-cdl-academy",
    authorName: "Alamo CDL Academy",
    authorCategory: "training_cdl",
    kind: "training",
    title: "Hazmat endorsement weekend intensives",
    body: "Next cohort starts Aug 2. Verified graduates receive a Network training badge path.",
    createdAt: "2026-07-15T11:00:00.000Z",
    followerOnly: false,
    likes: 8,
  },
  {
    id: "cp-3",
    authorMemberId: "nm-guard-ins",
    authorName: "GuardPath Insurance",
    authorCategory: "insurance",
    kind: "webinar",
    title: "Webinar: Insurance for fleets 40–80 trucks",
    body: "Covering liability structures, cargo, and occupational accident for mid-size fleets.",
    createdAt: "2026-07-14T16:00:00.000Z",
    followerOnly: false,
    likes: 19,
  },
  {
    id: "cp-4",
    authorMemberId: "nm-elena-safety",
    authorName: "Elena Vasquez",
    authorCategory: "safety_consultant",
    kind: "education",
    title: "Plain-language CSA score refresher",
    body: "A short guide for owners who are not safety specialists — what moves the needle.",
    createdAt: "2026-07-13T09:00:00.000Z",
    followerOnly: false,
    likes: 27,
  },
  {
    id: "cp-5",
    authorMemberId: "nm-trailer-hub",
    authorName: "TrailerHub Southwest",
    authorCategory: "trailer_dealer",
    kind: "promotion",
    title: "Reefer trailer lease specials — Q3",
    body: "Verified Network members: ask about fleet lease packages for 5+ units.",
    createdAt: "2026-07-12T13:00:00.000Z",
    followerOnly: false,
    likes: 5,
  },
];

export const seedTrustStatus: TrustStatusItem[] = [
  {
    id: "ts-identity",
    label: "Identity verification",
    status: "healthy",
    detail: "Government ID and Transpo ID verified.",
    href: "/network/identity",
  },
  {
    id: "ts-insurance",
    label: "Insurance signals",
    status: "attention",
    detail: "Occupational accident renews Aug 15, 2026 (Wallet document).",
  },
  {
    id: "ts-authority",
    label: "Authority (linked company)",
    status: "healthy",
    detail: "Lone Star Alpha — active MC/DOT on Business Passport.",
    href: "/network/business/nm-lone-star",
  },
  {
    id: "ts-documents",
    label: "Document completeness",
    status: "attention",
    detail: "Medical card expiring within 45 days — review in Professional Wallet data.",
  },
  {
    id: "ts-safety",
    label: "Safety & training",
    status: "healthy",
    detail: "Verified safe-driver badges and training highlights on file.",
  },
  {
    id: "ts-compliance",
    label: "Compliance posture",
    status: "healthy",
    detail: "Consent controls active; restricted categories require explicit share approval.",
  },
  {
    id: "ts-access",
    label: "Access control",
    status: "healthy",
    detail: "Sharing is consent-based with audit history. Encryption at rest for sensitive Wallet records.",
  },
];

export const seedTrustTimeline: TrustTimelineEvent[] = [
  {
    id: "tt-1",
    at: "2026-07-12T11:00:00.000Z",
    title: "Enterprise document request received",
    detail: "Horizon requested CDL + medical — pending your consent.",
    kind: "consent",
  },
  {
    id: "tt-2",
    at: "2026-06-03T15:00:00.000Z",
    title: "Employment verified",
    detail: "Alex Chen confirmed tenure at Lone Star Alpha.",
    kind: "verification",
  },
  {
    id: "tt-3",
    at: "2026-05-20T14:00:00.000Z",
    title: "Government ID verified",
    detail: "Identity document marked verified in Wallet.",
    kind: "document",
  },
  {
    id: "tt-4",
    at: "2026-04-01T09:00:00.000Z",
    title: "Audit: share link viewed",
    detail: "Horizon hiring packet viewed (CDL + medical scopes).",
    kind: "audit",
  },
];

export const seedNetworkAudit: NetworkAuditEntry[] = [
  {
    id: "na-1",
    at: "2026-07-16T10:00:00.000Z",
    actor: "Kai Morgan",
    action: "connection_requested",
    summary: "Recruiter connection request to Jordan Reyes.",
  },
  {
    id: "na-2",
    at: "2026-07-12T11:05:00.000Z",
    actor: "System",
    action: "access_control",
    summary: "Denied unrestricted medical share — consent required.",
  },
  {
    id: "na-3",
    at: "2026-06-03T15:00:00.000Z",
    actor: "Alex Chen",
    action: "experience_confirmed",
    summary: "Confirmed verified experience for Jordan Reyes.",
  },
];

export { seedBadges, seedIdentity, seedPassport, seedTrustScore, WALLET_OWNER_ID, TRUST_SCORE_DISCLAIMER };
export { NOW as NETWORK_SEED_NOW };
