-- Human-verified ELD and dashcam connection registry. Never stores credentials, tokens, passwords, location data, or device commands.
-- Review before applying. This file does not run against an environment by itself.
begin;
create table public.telematics_connections(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,vendor_name text not null check(char_length(vendor_name)between 2 and 120),
 connection_type text not null check(connection_type in('eld','dashcam','eld_dashcam')),account_label text not null check(char_length(account_label)between 2 and 120),
 portal_url text check(portal_url is null or portal_url~*'^https://'),support_phone text,status text not null default'planned'check(status in('planned','active','paused','disconnected')),
 verified_at timestamptz not null,factual_note text not null check(char_length(factual_note)between 3 and 2000),verified_by uuid not null,request_id text not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,request_id)
);
create table public.telematics_connection_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,connection_id uuid not null,event_type text not null check(event_type in('created','updated','status_changed')),
 before_state jsonb,after_state jsonb,factual_note text not null,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),
 unique(company_id,request_id),constraint telematics_event_company_fk foreign key(company_id,connection_id)references public.telematics_connections(company_id,id)
);
create index telematics_company_status_idx on public.telematics_connections(company_id,status,connection_type,vendor_name);
alter table public.telematics_connections enable row level security;alter table public.telematics_connection_events enable row level security;
create policy telematics_company_select on public.telematics_connections for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','safety'));
create policy telematics_events_company_select on public.telematics_connection_events for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner'));
revoke all privileges on table public.telematics_connections,public.telematics_connection_events from public,anon,authenticated,service_role;
grant select on table public.telematics_connections to authenticated,service_role;grant select on table public.telematics_connection_events to service_role;grant insert,update on table public.telematics_connections to service_role;grant insert on table public.telematics_connection_events to service_role;
create or replace function public.list_verified_telematics_connections()returns table(id uuid,vendor_name text,connection_type text,account_label text,portal_url text,support_phone text,status text,verified_at timestamptz,factual_note text,updated_at timestamptz)
language sql stable security definer set search_path=public as $$select c.id,c.vendor_name,c.connection_type,c.account_label,c.portal_url,c.support_phone,c.status,c.verified_at,c.factual_note,c.updated_at from public.telematics_connections c where c.company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','safety')order by case c.status when'active'then 0 when'planned'then 1 when'paused'then 2 else 3 end,c.vendor_name$$;
create or replace function public.save_verified_telematics_connection(p_connection_id uuid,p_vendor_name text,p_connection_type text,p_account_label text,p_portal_url text,p_support_phone text,p_status text,p_verified_at timestamptz,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();r text:=public.current_business_role();x uuid;b jsonb;a jsonb;e text;begin if c is null or u is null or r not in('super_admin','owner')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or char_length(trim(p_vendor_name))not between 2 and 120 or p_connection_type not in('eld','dashcam','eld_dashcam')or char_length(trim(p_account_label))not between 2 and 120 or p_status not in('planned','active','paused','disconnected')or p_verified_at is null or char_length(trim(p_note))not between 3 and 2000 or(p_portal_url is not null and trim(p_portal_url)<>''and p_portal_url!~*'^https://')then raise exception'Invalid connection facts';end if;select connection_id into x from public.telematics_connection_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;if p_connection_id is null then insert into public.telematics_connections(company_id,vendor_name,connection_type,account_label,portal_url,support_phone,status,verified_at,factual_note,verified_by,request_id)values(c,trim(p_vendor_name),p_connection_type,trim(p_account_label),nullif(trim(p_portal_url),''),nullif(trim(p_support_phone),''),p_status,p_verified_at,trim(p_note),u,p_request_id)returning id into x;e:='created';else select to_jsonb(v)into b from public.telematics_connections v where v.company_id=c and v.id=p_connection_id for update;if b is null then raise exception'Connection not found';end if;update public.telematics_connections set vendor_name=trim(p_vendor_name),connection_type=p_connection_type,account_label=trim(p_account_label),portal_url=nullif(trim(p_portal_url),''),support_phone=nullif(trim(p_support_phone),''),status=p_status,verified_at=p_verified_at,factual_note=trim(p_note),verified_by=u,request_id=p_request_id,updated_at=now()where company_id=c and id=p_connection_id returning id into x;e:=case when b->>'status'<>p_status then'status_changed'else'updated'end;end if;select to_jsonb(v)into a from public.telematics_connections v where v.company_id=c and v.id=x;insert into public.telematics_connection_events(company_id,connection_id,event_type,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,e,b,a,trim(p_note),u,p_request_id);return x;end$$;
revoke all on function public.list_verified_telematics_connections(),public.save_verified_telematics_connection(uuid,text,text,text,text,text,text,timestamptz,text,text)from public,anon;grant execute on function public.list_verified_telematics_connections()to authenticated;grant execute on function public.save_verified_telematics_connection(uuid,text,text,text,text,text,text,timestamptz,text,text)to authenticated;
commit;
