-- Human-verified customer and shipper relationship directory. No credit, payment reliability, freight availability, or endorsement is inferred.
-- Review before applying. This file does not run against an environment by itself.
begin;
create table public.customer_shipper_profiles(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,legal_name text not null check(char_length(legal_name)between 2 and 200),relationship_type text not null check(relationship_type in('customer','shipper','customer_shipper')),
 contact_name text,contact_email text,contact_phone text,billing_email text,payment_terms_days integer not null default 30 check(payment_terms_days between 0 and 120),
 relationship_status text not null default'prospect'check(relationship_status in('prospect','active','on_hold','do_not_use')),factual_note text not null check(char_length(factual_note)between 3 and 2000),
 verified_by uuid not null,verified_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,legal_name),
 check(contact_email is null or contact_email~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),check(billing_email is null or billing_email~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);
create table public.customer_shipper_profile_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,profile_id uuid not null,event_type text not null check(event_type in('created','updated','status_changed')),before_state jsonb,after_state jsonb not null,
 factual_note text not null,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),unique(company_id,request_id),constraint customer_shipper_event_company_fk foreign key(company_id,profile_id)references public.customer_shipper_profiles(company_id,id)
);
create index customer_shipper_company_status_idx on public.customer_shipper_profiles(company_id,relationship_status,relationship_type,legal_name);
alter table public.customer_shipper_profiles enable row level security;alter table public.customer_shipper_profile_events enable row level security;
create policy customer_shipper_profiles_select on public.customer_shipper_profiles for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting','read_only'));
create policy customer_shipper_events_select on public.customer_shipper_profile_events for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting'));
revoke all privileges on table public.customer_shipper_profiles,public.customer_shipper_profile_events from public,anon,authenticated,service_role;
grant select on table public.customer_shipper_profiles,public.customer_shipper_profile_events to authenticated,service_role;grant insert,update on table public.customer_shipper_profiles to service_role;grant insert on table public.customer_shipper_profile_events to service_role;
create or replace function public.list_verified_customer_shipper_profiles()returns table(id uuid,legal_name text,relationship_type text,contact_name text,contact_email text,contact_phone text,billing_email text,payment_terms_days integer,relationship_status text,factual_note text,verified_at timestamptz)
language sql stable security definer set search_path=public as $$select p.id,p.legal_name,p.relationship_type,p.contact_name,p.contact_email,p.contact_phone,p.billing_email,p.payment_terms_days,p.relationship_status,p.factual_note,p.verified_at from public.customer_shipper_profiles p where p.company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting','read_only')order by case when p.relationship_status='active'then 0 when p.relationship_status='prospect'then 1 else 2 end,p.legal_name$$;
create or replace function public.save_verified_customer_shipper_profile(p_profile_id uuid,p_legal_name text,p_relationship_type text,p_contact_name text,p_contact_email text,p_contact_phone text,p_billing_email text,p_payment_terms_days integer,p_relationship_status text,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();r text:=public.current_business_role();x uuid;b jsonb;a jsonb;e text;begin if c is null or u is null or r not in('super_admin','owner','dispatcher','accounting')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or char_length(trim(p_legal_name))not between 2 and 200 or p_relationship_type not in('customer','shipper','customer_shipper')or p_payment_terms_days not between 0 and 120 or p_relationship_status not in('prospect','active','on_hold','do_not_use')or char_length(trim(p_note))not between 3 and 2000 or(p_contact_email is not null and trim(p_contact_email)<>''and p_contact_email!~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')or(p_billing_email is not null and trim(p_billing_email)<>''and p_billing_email!~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')then raise exception'Invalid customer or shipper facts';end if;select profile_id into x from public.customer_shipper_profile_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;if p_profile_id is null then insert into public.customer_shipper_profiles(company_id,legal_name,relationship_type,contact_name,contact_email,contact_phone,billing_email,payment_terms_days,relationship_status,factual_note,verified_by)values(c,trim(p_legal_name),p_relationship_type,nullif(trim(p_contact_name),''),nullif(lower(trim(p_contact_email)),''),nullif(trim(p_contact_phone),''),nullif(lower(trim(p_billing_email)),''),p_payment_terms_days,p_relationship_status,trim(p_note),u)returning id into x;e:='created';else select to_jsonb(v)into b from public.customer_shipper_profiles v where v.company_id=c and v.id=p_profile_id for update;if b is null then raise exception'Profile not found';end if;update public.customer_shipper_profiles set legal_name=trim(p_legal_name),relationship_type=p_relationship_type,contact_name=nullif(trim(p_contact_name),''),contact_email=nullif(lower(trim(p_contact_email)),''),contact_phone=nullif(trim(p_contact_phone),''),billing_email=nullif(lower(trim(p_billing_email)),''),payment_terms_days=p_payment_terms_days,relationship_status=p_relationship_status,factual_note=trim(p_note),verified_by=u,verified_at=now(),updated_at=now()where company_id=c and id=p_profile_id returning id into x;e:=case when b->>'relationship_status'<>p_relationship_status then'status_changed'else'updated'end;end if;select to_jsonb(v)into a from public.customer_shipper_profiles v where v.company_id=c and v.id=x;insert into public.customer_shipper_profile_events(company_id,profile_id,event_type,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,e,b,a,trim(p_note),u,p_request_id);return x;end$$;
revoke all on function public.list_verified_customer_shipper_profiles(),public.save_verified_customer_shipper_profile(uuid,text,text,text,text,text,text,integer,text,text,text)from public,anon;grant execute on function public.list_verified_customer_shipper_profiles(),public.save_verified_customer_shipper_profile(uuid,text,text,text,text,text,text,integer,text,text,text)to authenticated;
commit;
