-- Human-confirmed broker-to-load link and dispatch release gate. Review before applying.
begin;
alter table public.load_events drop constraint load_events_event_type_check;
alter table public.load_events add constraint load_events_event_type_check check(event_type in('status_changed','location_reported','eta_reported','check_in','check_out','exception_reported','instruction_sent','document_received','approval_recorded','broker_verified'));
alter table public.loads add column broker_profile_id uuid;
alter table public.loads add constraint loads_broker_company_fk foreign key(company_id,broker_profile_id)references public.broker_profiles(company_id,id);
revoke insert,update on table public.loads from authenticated;grant select on table public.loads to authenticated;
create or replace function public.list_linkable_verified_brokers()returns table(id uuid,legal_name text,mc_number text,relationship_status text)language sql stable security definer set search_path=public as $$select b.id,b.legal_name,b.mc_number,b.relationship_status from public.broker_profiles b where b.company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher')order by b.legal_name,b.id$$;
create or replace function public.link_verified_broker_to_load(p_load_id uuid,p_broker_profile_id uuid,p_note text,p_request_id text)returns uuid language plpgsql security definer set search_path=public as $$declare v_company uuid:=public.document_intake_company_id();v_user uuid:=auth.uid();v_role text:=public.current_business_role();v_status text;begin if v_company is null or v_user is null or v_role not in('super_admin','owner','dispatcher')then raise exception 'Not authorized to verify load broker';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or p_note is null or char_length(trim(p_note))not between 3 and 2000 then raise exception 'Factual confirmation note required';end if;if exists(select 1 from public.load_events e where e.company_id=v_company and e.request_id=p_request_id)then return p_load_id;end if;select b.relationship_status into v_status from public.broker_profiles b where b.id=p_broker_profile_id and b.company_id=v_company;if v_status is null then raise exception 'Same-company verified broker not found';end if;update public.loads set broker_profile_id=p_broker_profile_id,updated_at=now()where id=p_load_id and company_id=v_company and status='pending';if not found then raise exception 'Only a pending same-company load can link a broker';end if;insert into public.load_events(company_id,load_id,event_type,status,factual_note,source,actor_user_id,request_id)values(v_company,p_load_id,'broker_verified','pending',trim(p_note)||' Broker status at confirmation: '||v_status||'. No load acceptance or movement was authorized.',case when v_role='dispatcher'then'dispatcher'else'owner'end,v_user,p_request_id);return p_load_id;end$$;
create or replace function public.enforce_verified_dispatch_release()returns trigger language plpgsql security definer set search_path=public as $$begin if old.status='pending'and new.status='dispatched'then if not exists(select 1 from public.broker_profiles b where b.company_id=new.company_id and b.id=new.broker_profile_id and b.relationship_status='active')then raise exception 'Dispatch release requires a linked active verified broker record';end if;if not exists(select 1 from public.load_assignments a join auth.users u on u.id=a.driver_user_id where a.company_id=new.company_id and a.load_id=new.id and a.ended_at is null and a.equipment_fit_verified is true and a.hos_verified is true and a.safety_verified is true and char_length(trim(a.truck_unit))between 1 and 80 and u.raw_app_meta_data->>'company_id'=new.company_id::text and u.raw_app_meta_data->>'business_role'='driver')then raise exception 'Dispatch release requires an active verified same-company driver and all safety confirmations';end if;end if;return new;end$$;
revoke all on function public.list_linkable_verified_brokers(),public.link_verified_broker_to_load(uuid,uuid,text,text)from public,anon;grant execute on function public.list_linkable_verified_brokers(),public.link_verified_broker_to_load(uuid,uuid,text,text)to authenticated;
commit;
