-- Human-recorded factoring tracker. It never submits invoices, contacts factors, transfers funds, or marks invoices paid.
-- Review before applying. This file does not run against an environment by itself.
begin;
create table public.factoring_records(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,load_id uuid not null,provider_name text not null check(char_length(provider_name)between 2 and 200),
 status text not null default'prepared'check(status in('prepared','submitted_by_human','approved','declined','funded','voided')),submission_reference text,
 advance_cents bigint,fee_cents bigint,funded_at timestamptz,factual_note text not null check(char_length(factual_note)between 3 and 2000),verified_by uuid not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,load_id),constraint factoring_load_company_fk foreign key(company_id,load_id)references public.loads(company_id,id),
 check(advance_cents is null or advance_cents>0),check(fee_cents is null or fee_cents>=0)
);
create table public.factoring_record_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,factoring_record_id uuid not null,event_type text not null check(event_type in('prepared','submitted_by_human','approved','declined','funded','voided')),
 before_state jsonb,after_state jsonb not null,factual_note text not null,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),unique(company_id,request_id),constraint factoring_event_company_fk foreign key(company_id,factoring_record_id)references public.factoring_records(company_id,id)
);
alter table public.factoring_records enable row level security;alter table public.factoring_record_events enable row level security;
create policy factoring_finance_select on public.factoring_records for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting'));
create policy factoring_events_finance_select on public.factoring_record_events for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting'));
revoke all privileges on table public.factoring_records,public.factoring_record_events from public,anon,authenticated,service_role;grant select on table public.factoring_records,public.factoring_record_events to authenticated,service_role;grant insert,update on table public.factoring_records to service_role;grant insert on table public.factoring_record_events to service_role;
create or replace function public.list_verified_factoring_workspace()returns table(load_id uuid,load_number text,broker_name text,invoice_number text,invoice_cents bigint,paid_cents bigint,factoring_record_id uuid,provider_name text,factoring_status text,submission_reference text,advance_cents bigint,fee_cents bigint,funded_at timestamptz,factual_note text)
language sql stable security definer set search_path=public as $$select l.id,l.load_number,l.broker_name,f.invoice_number,f.rate_cents,f.paid_cents,r.id,r.provider_name,r.status,r.submission_reference,r.advance_cents,r.fee_cents,r.funded_at,r.factual_note from public.loads l join public.load_financials f on f.company_id=l.company_id and f.load_id=l.id left join public.factoring_records r on r.company_id=l.company_id and r.load_id=l.id where l.company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting')and f.invoice_number is not null and f.rate_cents>f.paid_cents order by case when r.status in('prepared','submitted_by_human','approved')then 0 when r.id is null then 1 else 2 end,f.expected_payment_at,l.updated_at$$;
create or replace function public.prepare_verified_factoring_record(p_load_id uuid,p_provider_name text,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();x uuid;a jsonb;begin if c is null or u is null or public.current_business_role()not in('super_admin','owner','accounting')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or char_length(trim(p_provider_name))not between 2 and 200 or char_length(trim(p_note))not between 3 and 2000 then raise exception'Invalid factoring facts';end if;select factoring_record_id into x from public.factoring_record_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;if not exists(select 1 from public.load_financials f where f.company_id=c and f.load_id=p_load_id and f.invoice_number is not null and f.rate_cents>f.paid_cents)then raise exception'Outstanding verified invoice required';end if;insert into public.factoring_records(company_id,load_id,provider_name,factual_note,verified_by)values(c,p_load_id,trim(p_provider_name),trim(p_note),u)returning id into x;select to_jsonb(r)into a from public.factoring_records r where r.id=x;insert into public.factoring_record_events(company_id,factoring_record_id,event_type,after_state,factual_note,actor_user_id,request_id)values(c,x,'prepared',a,trim(p_note),u,p_request_id);return x;end$$;
create or replace function public.record_verified_factoring_status(p_factoring_record_id uuid,p_next_status text,p_submission_reference text,p_advance_cents bigint,p_fee_cents bigint,p_funded_at timestamptz,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();x uuid;b jsonb;a jsonb;s text;outstanding bigint;begin if c is null or u is null or public.current_business_role()not in('super_admin','owner','accounting')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or p_next_status not in('submitted_by_human','approved','declined','funded','voided')or char_length(trim(p_note))not between 3 and 2000 then raise exception'Invalid factoring status facts';end if;select factoring_record_id into x from public.factoring_record_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;select to_jsonb(r),r.status,f.rate_cents-f.paid_cents into b,s,outstanding from public.factoring_records r join public.load_financials f on f.company_id=r.company_id and f.load_id=r.load_id where r.company_id=c and r.id=p_factoring_record_id for update;if b is null then raise exception'Factoring record not found';end if;if not((s='prepared'and p_next_status in('submitted_by_human','voided'))or(s='submitted_by_human'and p_next_status in('approved','declined','voided'))or(s='approved'and p_next_status in('funded','declined','voided')))then raise exception'Invalid factoring status transition';end if;if p_next_status='submitted_by_human'and coalesce(char_length(trim(p_submission_reference)),0)<2 then raise exception'Human submission reference required';end if;if p_next_status='funded'and(p_advance_cents is null or p_advance_cents<=0 or p_fee_cents is null or p_fee_cents<0 or p_funded_at is null or p_funded_at>now()+interval'1 day'or p_advance_cents+p_fee_cents>outstanding)then raise exception'Invalid funded facts';end if;update public.factoring_records set status=p_next_status,submission_reference=coalesce(nullif(trim(p_submission_reference),''),submission_reference),advance_cents=case when p_next_status='funded'then p_advance_cents else advance_cents end,fee_cents=case when p_next_status='funded'then p_fee_cents else fee_cents end,funded_at=case when p_next_status='funded'then p_funded_at else funded_at end,factual_note=trim(p_note),verified_by=u,updated_at=now()where company_id=c and id=p_factoring_record_id returning id into x;select to_jsonb(r)into a from public.factoring_records r where r.id=x;insert into public.factoring_record_events(company_id,factoring_record_id,event_type,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,p_next_status,b,a,trim(p_note),u,p_request_id);return x;end$$;
revoke all on function public.list_verified_factoring_workspace(),public.prepare_verified_factoring_record(uuid,text,text,text),public.record_verified_factoring_status(uuid,text,text,bigint,bigint,timestamptz,text,text)from public,anon;grant execute on function public.list_verified_factoring_workspace(),public.prepare_verified_factoring_record(uuid,text,text,text),public.record_verified_factoring_status(uuid,text,text,bigint,bigint,timestamptz,text,text)to authenticated;
commit;
