-- Verified fuel and jurisdiction-mile evidence ledger for IFTA preparation.
-- Review before applying. This does not calculate tax liability or file a return.
begin;
create table public.fuel_purchase_records(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,asset_id uuid not null,purchased_at timestamptz not null,
 jurisdiction text not null check(jurisdiction~'^[A-Z]{2}$'),gallons numeric(12,3)not null check(gallons>0 and gallons<=5000),
 total_cost_cents bigint not null check(total_cost_cents>=0),vendor text,odometer_miles integer check(odometer_miles is null or odometer_miles>=0),
 source text not null check(source in('manual','fuel_card','receipt')),receipt_document_id uuid,status text not null default'active'check(status in('active','voided')),
 verified_by uuid not null,verified_at timestamptz not null default now(),voided_by uuid,voided_at timestamptz,void_reason text,request_id text not null,created_at timestamptz not null default now(),
 unique(company_id,id),unique(company_id,request_id),constraint fuel_asset_company_fk foreign key(company_id,asset_id)references public.fleet_assets(company_id,id),
 constraint fuel_receipt_company_fk foreign key(company_id,receipt_document_id)references public.documents(company_id,id)
);
create table public.ifta_mileage_records(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,asset_id uuid not null,trip_date date not null,jurisdiction text not null check(jurisdiction~'^[A-Z]{2}$'),
 total_miles integer not null check(total_miles>=0),taxable_miles integer not null check(taxable_miles>=0 and taxable_miles<=total_miles),
 source text not null check(source in('manual','eld','gps','import')),evidence_document_id uuid,status text not null default'active'check(status in('active','voided')),
 verified_by uuid not null,verified_at timestamptz not null default now(),voided_by uuid,voided_at timestamptz,void_reason text,request_id text not null,created_at timestamptz not null default now(),
 unique(company_id,id),unique(company_id,request_id),constraint ifta_mileage_asset_company_fk foreign key(company_id,asset_id)references public.fleet_assets(company_id,id),
 constraint ifta_mileage_evidence_company_fk foreign key(company_id,evidence_document_id)references public.documents(company_id,id)
);
create table public.ifta_record_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,record_kind text not null check(record_kind in('fuel','mileage')),record_id uuid not null,
 event_type text not null check(event_type in('recorded','voided')),after_state jsonb not null,factual_note text,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),unique(company_id,id),unique(company_id,request_id)
);
create index fuel_purchase_company_quarter_idx on public.fuel_purchase_records(company_id,purchased_at,asset_id,jurisdiction)where status='active';create index ifta_mileage_company_quarter_idx on public.ifta_mileage_records(company_id,trip_date,asset_id,jurisdiction)where status='active';
alter table public.fuel_purchase_records enable row level security;alter table public.ifta_mileage_records enable row level security;alter table public.ifta_record_events enable row level security;
create policy fuel_ifta_finance_select on public.fuel_purchase_records for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting'));
create policy mileage_ifta_finance_select on public.ifta_mileage_records for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting'));
create policy ifta_events_finance_select on public.ifta_record_events for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','accounting'));
revoke all privileges on table public.fuel_purchase_records,public.ifta_mileage_records,public.ifta_record_events from public,anon,authenticated,service_role;grant select on table public.fuel_purchase_records,public.ifta_mileage_records,public.ifta_record_events to authenticated,service_role;grant insert,update on table public.fuel_purchase_records,public.ifta_mileage_records to service_role;grant insert on table public.ifta_record_events to service_role;

-- Official member scope: the 48 contiguous States and 10 Canadian Provinces.
create or replace function public.is_ifta_member_jurisdiction(p_code text)returns boolean language sql immutable as $$select upper(trim(p_code))=any(array['AL','AZ','AR','CA','CO','CT','DE','FL','GA','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','AB','BC','MB','NB','NL','NS','ON','PE','QC','SK'])$$;
create or replace function public.list_ifta_trucks()returns table(asset_id uuid,unit_number text)language sql stable security definer set search_path=public as $$select a.id,a.unit_number from public.fleet_assets a where a.company_id=public.document_intake_company_id()and a.asset_type='truck'and a.status<>'retired'and public.current_business_role()in('super_admin','owner','accounting')order by a.unit_number$$;
create or replace function public.list_verified_fuel_receipts()returns table(document_id uuid,title text)language sql stable security definer set search_path=public as $$select d.id,d.title from public.documents d where d.company_id=public.document_intake_company_id()and d.document_type='fuel_receipt'and public.current_business_role()in('super_admin','owner','accounting')and public.is_current_approved_document(d.id,'fuel_receipt')order by d.created_at desc limit 250$$;
create or replace function public.list_ifta_quarter_summary(p_year integer,p_quarter integer)returns table(asset_id uuid,unit_number text,jurisdiction text,total_miles bigint,taxable_miles bigint,gallons numeric,total_cost_cents bigint)
language plpgsql stable security definer set search_path=public as $$declare v_start date;v_end date;begin if public.current_business_role()not in('super_admin','owner','accounting')or p_year not between 2000 and extract(year from current_date)::integer+1 or p_quarter not between 1 and 4 then raise exception'Not authorized or invalid quarter';end if;v_start:=make_date(p_year,(p_quarter-1)*3+1,1);v_end:=(v_start+interval'3 months')::date;return query with f as(select r.asset_id,r.jurisdiction,sum(r.gallons)gallons,sum(r.total_cost_cents)cost from public.fuel_purchase_records r where r.company_id=public.document_intake_company_id()and r.status='active'and r.purchased_at>=v_start and r.purchased_at<v_end group by r.asset_id,r.jurisdiction),m as(select r.asset_id,r.jurisdiction,sum(r.total_miles)::bigint miles,sum(r.taxable_miles)::bigint taxable from public.ifta_mileage_records r where r.company_id=public.document_intake_company_id()and r.status='active'and r.trip_date>=v_start and r.trip_date<v_end group by r.asset_id,r.jurisdiction),k as(select f.asset_id,f.jurisdiction from f union select m.asset_id,m.jurisdiction from m)select k.asset_id,a.unit_number,k.jurisdiction,m.miles,m.taxable,f.gallons,f.cost from k join public.fleet_assets a on a.company_id=public.document_intake_company_id()and a.id=k.asset_id left join m using(asset_id,jurisdiction)left join f using(asset_id,jurisdiction)order by a.unit_number,k.jurisdiction;end$$;
create or replace function public.list_ifta_quarter_records(p_year integer,p_quarter integer)returns table(record_kind text,record_id uuid,asset_id uuid,unit_number text,recorded_on date,jurisdiction text,miles integer,taxable_miles integer,gallons numeric,total_cost_cents bigint,source text,status text)
language plpgsql stable security definer set search_path=public as $$declare v_start date;v_end date;begin if public.current_business_role()not in('super_admin','owner','accounting')or p_year not between 2000 and extract(year from current_date)::integer+1 or p_quarter not between 1 and 4 then raise exception'Not authorized or invalid quarter';end if;v_start:=make_date(p_year,(p_quarter-1)*3+1,1);v_end:=(v_start+interval'3 months')::date;return query select'fuel',f.id,f.asset_id,a.unit_number,f.purchased_at::date,f.jurisdiction,null::integer,null::integer,f.gallons,f.total_cost_cents,f.source,f.status from public.fuel_purchase_records f join public.fleet_assets a on a.company_id=f.company_id and a.id=f.asset_id where f.company_id=public.document_intake_company_id()and f.purchased_at>=v_start and f.purchased_at<v_end union all select'mileage',m.id,m.asset_id,a.unit_number,m.trip_date,m.jurisdiction,m.total_miles,m.taxable_miles,null::numeric,null::bigint,m.source,m.status from public.ifta_mileage_records m join public.fleet_assets a on a.company_id=m.company_id and a.id=m.asset_id where m.company_id=public.document_intake_company_id()and m.trip_date>=v_start and m.trip_date<v_end order by 5 desc,1;end$$;
create or replace function public.record_verified_fuel_purchase(p_asset_id uuid,p_purchased_at timestamptz,p_jurisdiction text,p_gallons numeric,p_total_cost_cents bigint,p_vendor text,p_odometer_miles integer,p_source text,p_receipt_document_id uuid,p_note text,p_request_id text)returns uuid language plpgsql security definer set search_path=public as $$declare v_company uuid:=public.document_intake_company_id();v_user uuid:=auth.uid();v_role text:=public.current_business_role();v_id uuid;v_after jsonb;begin if v_company is null or v_user is null or v_role not in('super_admin','owner','accounting')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 then raise exception'Invalid request identifier';end if;select record_id into v_id from public.ifta_record_events where company_id=v_company and request_id=p_request_id;if v_id is not null then return v_id;end if;if not public.is_ifta_member_jurisdiction(p_jurisdiction)or p_gallons<=0 or p_gallons>5000 or p_total_cost_cents<0 or p_purchased_at is null or p_purchased_at>now()+interval'1 day'then raise exception'Invalid fuel facts';end if;if not exists(select 1 from public.fleet_assets a where a.company_id=v_company and a.id=p_asset_id and a.asset_type='truck'and a.status<>'retired')then raise exception'Verified truck required';end if;if p_source not in('manual','fuel_card','receipt')then raise exception'Invalid source';end if;if p_source='receipt'and(p_receipt_document_id is null or not public.is_current_approved_document(p_receipt_document_id,'fuel_receipt'))then raise exception'Approved fuel receipt required';end if;insert into public.fuel_purchase_records(company_id,asset_id,purchased_at,jurisdiction,gallons,total_cost_cents,vendor,odometer_miles,source,receipt_document_id,verified_by,request_id)values(v_company,p_asset_id,p_purchased_at,upper(trim(p_jurisdiction)),p_gallons,p_total_cost_cents,nullif(trim(p_vendor),''),p_odometer_miles,p_source,p_receipt_document_id,v_user,p_request_id)returning id into v_id;select to_jsonb(r)into v_after from public.fuel_purchase_records r where r.id=v_id;insert into public.ifta_record_events(company_id,record_kind,record_id,event_type,after_state,factual_note,actor_user_id,request_id)values(v_company,'fuel',v_id,'recorded',v_after,nullif(trim(p_note),''),v_user,p_request_id);return v_id;end$$;
create or replace function public.record_verified_ifta_mileage(p_asset_id uuid,p_trip_date date,p_jurisdiction text,p_total_miles integer,p_taxable_miles integer,p_source text,p_evidence_document_id uuid,p_note text,p_request_id text)returns uuid language plpgsql security definer set search_path=public as $$declare v_company uuid:=public.document_intake_company_id();v_user uuid:=auth.uid();v_role text:=public.current_business_role();v_id uuid;v_after jsonb;begin if v_company is null or v_user is null or v_role not in('super_admin','owner','accounting')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 then raise exception'Invalid request identifier';end if;select record_id into v_id from public.ifta_record_events where company_id=v_company and request_id=p_request_id;if v_id is not null then return v_id;end if;if not public.is_ifta_member_jurisdiction(p_jurisdiction)or p_trip_date is null or p_trip_date>current_date+1 or p_total_miles<0 or p_taxable_miles<0 or p_taxable_miles>p_total_miles or p_source not in('manual','eld','gps','import')then raise exception'Invalid mileage facts';end if;if not exists(select 1 from public.fleet_assets a where a.company_id=v_company and a.id=p_asset_id and a.asset_type='truck'and a.status<>'retired')then raise exception'Verified truck required';end if;insert into public.ifta_mileage_records(company_id,asset_id,trip_date,jurisdiction,total_miles,taxable_miles,source,evidence_document_id,verified_by,request_id)values(v_company,p_asset_id,p_trip_date,upper(trim(p_jurisdiction)),p_total_miles,p_taxable_miles,p_source,p_evidence_document_id,v_user,p_request_id)returning id into v_id;select to_jsonb(r)into v_after from public.ifta_mileage_records r where r.id=v_id;insert into public.ifta_record_events(company_id,record_kind,record_id,event_type,after_state,factual_note,actor_user_id,request_id)values(v_company,'mileage',v_id,'recorded',v_after,nullif(trim(p_note),''),v_user,p_request_id);return v_id;end$$;
create or replace function public.void_verified_ifta_record(p_record_kind text,p_record_id uuid,p_reason text,p_request_id text)returns uuid language plpgsql security definer set search_path=public as $$declare v_company uuid:=public.document_intake_company_id();v_user uuid:=auth.uid();v_role text:=public.current_business_role();v_after jsonb;begin if v_company is null or v_user is null or v_role not in('super_admin','owner','accounting')then raise exception'Not authorized';end if;if p_reason is null or char_length(trim(p_reason))not between 3 and 2000 or p_request_id is null or char_length(p_request_id)not between 8 and 200 then raise exception'Factual void reason required';end if;if exists(select 1 from public.ifta_record_events where company_id=v_company and request_id=p_request_id)then return p_record_id;end if;if p_record_kind='fuel'then update public.fuel_purchase_records set status='voided',voided_by=v_user,voided_at=now(),void_reason=trim(p_reason)where company_id=v_company and id=p_record_id and status='active'returning to_jsonb(fuel_purchase_records.*)into v_after;elsif p_record_kind='mileage'then update public.ifta_mileage_records set status='voided',voided_by=v_user,voided_at=now(),void_reason=trim(p_reason)where company_id=v_company and id=p_record_id and status='active'returning to_jsonb(ifta_mileage_records.*)into v_after;else raise exception'Invalid record kind';end if;if v_after is null then raise exception'Active record not found';end if;insert into public.ifta_record_events(company_id,record_kind,record_id,event_type,after_state,factual_note,actor_user_id,request_id)values(v_company,p_record_kind,p_record_id,'voided',v_after,trim(p_reason),v_user,p_request_id);return p_record_id;end$$;
revoke all on function public.is_ifta_member_jurisdiction(text)from public,anon;revoke all on function public.list_ifta_trucks(),public.list_verified_fuel_receipts(),public.list_ifta_quarter_summary(integer,integer),public.list_ifta_quarter_records(integer,integer)from public,anon;revoke all on function public.record_verified_fuel_purchase(uuid,timestamptz,text,numeric,bigint,text,integer,text,uuid,text,text),public.record_verified_ifta_mileage(uuid,date,text,integer,integer,text,uuid,text,text),public.void_verified_ifta_record(text,uuid,text,text)from public,anon;
grant execute on function public.list_ifta_trucks(),public.list_verified_fuel_receipts(),public.list_ifta_quarter_summary(integer,integer),public.list_ifta_quarter_records(integer,integer)to authenticated;grant execute on function public.record_verified_fuel_purchase(uuid,timestamptz,text,numeric,bigint,text,integer,text,uuid,text,text),public.record_verified_ifta_mileage(uuid,date,text,integer,integer,text,uuid,text,text),public.void_verified_ifta_record(text,uuid,text,text)to authenticated;
commit;
