-- Driver-originated leave, home-time, and load-preference requests. Requests never change driver status, assignments, HOS, payroll, or authorize movement.
-- Review before applying. This file does not run against an environment by itself.
begin;
create table public.driver_operational_requests(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,driver_user_id uuid not null,
 request_type text not null check(request_type in('leave','home_time','load_request')),start_on date,end_on date,preferred_region text,
 status text not null default'pending'check(status in('pending','acknowledged','declined','cancelled')),driver_note text not null check(char_length(driver_note)between 3 and 2000),
 decision_note text,decided_by uuid,decided_at timestamptz,request_id text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(company_id,id),unique(company_id,request_id),check(start_on is null or end_on is null or start_on<=end_on)
);
create table public.driver_operational_request_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,operational_request_id uuid not null,event_type text not null check(event_type in('submitted','acknowledged','declined','cancelled')),
 before_state jsonb,after_state jsonb not null,factual_note text not null,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),unique(company_id,request_id),
 constraint driver_operational_request_event_company_fk foreign key(company_id,operational_request_id)references public.driver_operational_requests(company_id,id)
);
create index driver_operational_requests_company_status_idx on public.driver_operational_requests(company_id,status,created_at desc);
alter table public.driver_operational_requests enable row level security;alter table public.driver_operational_request_events enable row level security;
create policy driver_operational_requests_select on public.driver_operational_requests for select using(company_id=public.document_intake_company_id()and(driver_user_id=auth.uid()or public.current_business_role()in('super_admin','owner','dispatcher')));
create policy driver_operational_request_events_select on public.driver_operational_request_events for select using(company_id=public.document_intake_company_id()and exists(select 1 from public.driver_operational_requests r where r.id=driver_operational_request_events.operational_request_id and r.company_id=driver_operational_request_events.company_id and(r.driver_user_id=auth.uid()or public.current_business_role()in('super_admin','owner','dispatcher'))));
revoke all privileges on table public.driver_operational_requests,public.driver_operational_request_events from public,anon,authenticated,service_role;
grant select on table public.driver_operational_requests,public.driver_operational_request_events to authenticated,service_role;grant insert,update on table public.driver_operational_requests to service_role;grant insert on table public.driver_operational_request_events to service_role;
create or replace function public.list_verified_driver_operational_requests()returns table(id uuid,driver_user_id uuid,driver_name text,request_type text,start_on date,end_on date,preferred_region text,status text,driver_note text,decision_note text,created_at timestamptz,decided_at timestamptz)
language sql stable security definer set search_path=public as $$select r.id,r.driver_user_id,coalesce(nullif(trim(u.raw_user_meta_data->>'full_name'),''),'Verified driver'),r.request_type,r.start_on,r.end_on,r.preferred_region,r.status,r.driver_note,r.decision_note,r.created_at,r.decided_at from public.driver_operational_requests r join auth.users u on u.id=r.driver_user_id where r.company_id=public.document_intake_company_id()and(r.driver_user_id=auth.uid()or public.current_business_role()in('super_admin','owner','dispatcher'))and u.raw_app_meta_data->>'company_id'=r.company_id::text and u.raw_app_meta_data->>'business_role'='driver'order by case when r.status='pending'then 0 else 1 end,r.created_at desc$$;
create or replace function public.submit_verified_driver_operational_request(p_request_type text,p_start_on date,p_end_on date,p_preferred_region text,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();x uuid;a jsonb;begin if c is null or u is null or public.current_business_role()<>'driver'then raise exception'Only a verified driver may submit a request';end if;if not exists(select 1 from public.driver_profiles p where p.company_id=c and p.driver_user_id=u and p.status in('active','leave'))then raise exception'Active verified driver profile required';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or p_request_type not in('leave','home_time','load_request')or char_length(trim(p_note))not between 3 and 2000 or(p_request_type in('leave','home_time')and(p_start_on is null or p_end_on is null or p_start_on>p_end_on or p_end_on>p_start_on+60))or(p_request_type='load_request'and coalesce(char_length(trim(p_preferred_region)),0)<2)then raise exception'Invalid driver request facts';end if;select operational_request_id into x from public.driver_operational_request_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;insert into public.driver_operational_requests(company_id,driver_user_id,request_type,start_on,end_on,preferred_region,driver_note,request_id)values(c,u,p_request_type,p_start_on,p_end_on,nullif(trim(p_preferred_region),''),trim(p_note),p_request_id)returning id into x;select to_jsonb(r)into a from public.driver_operational_requests r where r.id=x;insert into public.driver_operational_request_events(company_id,operational_request_id,event_type,after_state,factual_note,actor_user_id,request_id)values(c,x,'submitted',a,trim(p_note),u,p_request_id);return x;end$$;
create or replace function public.decide_verified_driver_operational_request(p_operational_request_id uuid,p_decision text,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();x uuid;b jsonb;a jsonb;begin if c is null or u is null or public.current_business_role()not in('super_admin','owner','dispatcher')then raise exception'Not authorized to review requests';end if;if p_decision not in('acknowledged','declined')or char_length(trim(p_note))not between 3 and 2000 or p_request_id is null then raise exception'Invalid review';end if;select operational_request_id into x from public.driver_operational_request_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;select to_jsonb(r)into b from public.driver_operational_requests r where r.company_id=c and r.id=p_operational_request_id and r.status='pending'for update;if b is null then raise exception'Pending request not found';end if;update public.driver_operational_requests set status=p_decision,decision_note=trim(p_note),decided_by=u,decided_at=now(),updated_at=now()where company_id=c and id=p_operational_request_id returning id into x;select to_jsonb(r)into a from public.driver_operational_requests r where r.id=x;insert into public.driver_operational_request_events(company_id,operational_request_id,event_type,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,p_decision,b,a,trim(p_note),u,p_request_id);return x;end$$;
create or replace function public.cancel_verified_driver_operational_request(p_operational_request_id uuid,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();x uuid;b jsonb;a jsonb;begin if c is null or u is null or public.current_business_role()<>'driver'or char_length(trim(p_note))not between 3 and 2000 or p_request_id is null then raise exception'Invalid cancellation';end if;select operational_request_id into x from public.driver_operational_request_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;select to_jsonb(r)into b from public.driver_operational_requests r where r.company_id=c and r.id=p_operational_request_id and r.driver_user_id=u and r.status='pending'for update;if b is null then raise exception'Pending request not found';end if;update public.driver_operational_requests set status='cancelled',decision_note=trim(p_note),decided_by=u,decided_at=now(),updated_at=now()where company_id=c and id=p_operational_request_id returning id into x;select to_jsonb(r)into a from public.driver_operational_requests r where r.id=x;insert into public.driver_operational_request_events(company_id,operational_request_id,event_type,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,'cancelled',b,a,trim(p_note),u,p_request_id);return x;end$$;
revoke all on function public.list_verified_driver_operational_requests(),public.submit_verified_driver_operational_request(text,date,date,text,text,text),public.decide_verified_driver_operational_request(uuid,text,text,text),public.cancel_verified_driver_operational_request(uuid,text,text)from public,anon;grant execute on function public.list_verified_driver_operational_requests(),public.submit_verified_driver_operational_request(text,date,date,text,text,text),public.decide_verified_driver_operational_request(uuid,text,text,text),public.cancel_verified_driver_operational_request(uuid,text,text)to authenticated;
commit;
