-- Human-verified parts and supplies inventory. No purchasing or stock count is automated.
-- Review before applying. This file does not run against an environment by itself.
begin;
create table public.inventory_items(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,item_name text not null check(char_length(item_name)between 2 and 200),sku text,
 category text not null check(category in('tire','reefer_part','truck_part','trailer_part','fluid','seal','strap','safety','tool','office','other')),
 unit_of_measure text not null check(unit_of_measure in('piece','gallon','case','box','foot','pound','other')),
 quantity_on_hand integer not null default 0 check(quantity_on_hand>=0),reorder_level integer not null default 0 check(reorder_level>=0),storage_location text,
 status text not null default'active'check(status in('active','inactive')),factual_note text not null check(char_length(factual_note)between 3 and 2000),
 verified_by uuid not null,request_id text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,request_id)
);
create table public.inventory_item_events(
 id uuid primary key default gen_random_uuid(),company_id uuid not null,item_id uuid not null,event_type text not null check(event_type in('created','updated','stock_adjusted')),
 quantity_change integer,before_state jsonb,after_state jsonb,factual_note text not null,actor_user_id uuid not null,request_id text not null,created_at timestamptz not null default now(),
 unique(company_id,request_id),constraint inventory_event_company_fk foreign key(company_id,item_id)references public.inventory_items(company_id,id)
);
create index inventory_company_stock_idx on public.inventory_items(company_id,status,category,quantity_on_hand);
alter table public.inventory_items enable row level security;alter table public.inventory_item_events enable row level security;
create policy inventory_authorized_select on public.inventory_items for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting','safety','maintenance'));
create policy inventory_events_authorized_select on public.inventory_item_events for select using(company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting','safety','maintenance'));
revoke all privileges on table public.inventory_items,public.inventory_item_events from public,anon,authenticated,service_role;grant select on table public.inventory_items,public.inventory_item_events to authenticated,service_role;grant insert,update on table public.inventory_items to service_role;grant insert on table public.inventory_item_events to service_role;
create or replace function public.list_verified_inventory_items()returns table(id uuid,item_name text,sku text,category text,unit_of_measure text,quantity_on_hand integer,reorder_level integer,storage_location text,status text,factual_note text,updated_at timestamptz)
language sql stable security definer set search_path=public as $$select i.id,i.item_name,i.sku,i.category,i.unit_of_measure,i.quantity_on_hand,i.reorder_level,i.storage_location,i.status,i.factual_note,i.updated_at from public.inventory_items i where i.company_id=public.document_intake_company_id()and public.current_business_role()in('super_admin','owner','dispatcher','accounting','safety','maintenance')order by case when i.status='active'and i.quantity_on_hand<=i.reorder_level then 0 else 1 end,i.category,i.item_name$$;
create or replace function public.save_verified_inventory_item(p_item_id uuid,p_item_name text,p_sku text,p_category text,p_unit_of_measure text,p_initial_quantity integer,p_reorder_level integer,p_storage_location text,p_status text,p_note text,p_request_id text)returns uuid
language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();r text:=public.current_business_role();x uuid;b jsonb;a jsonb;e text;begin if c is null or u is null or r not in('super_admin','owner','safety','maintenance')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or char_length(trim(p_item_name))not between 2 and 200 or p_category not in('tire','reefer_part','truck_part','trailer_part','fluid','seal','strap','safety','tool','office','other')or p_unit_of_measure not in('piece','gallon','case','box','foot','pound','other')or p_initial_quantity is null or p_initial_quantity not between 0 and 1000000 or p_reorder_level is null or p_reorder_level not between 0 and 1000000 or p_status not in('active','inactive')or char_length(trim(p_note))not between 3 and 2000 then raise exception'Invalid inventory facts';end if;select item_id into x from public.inventory_item_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;if p_item_id is null then insert into public.inventory_items(company_id,item_name,sku,category,unit_of_measure,quantity_on_hand,reorder_level,storage_location,status,factual_note,verified_by,request_id)values(c,trim(p_item_name),nullif(trim(p_sku),''),p_category,p_unit_of_measure,p_initial_quantity,p_reorder_level,nullif(trim(p_storage_location),''),p_status,trim(p_note),u,p_request_id)returning id into x;e:='created';else select to_jsonb(v)into b from public.inventory_items v where v.company_id=c and v.id=p_item_id for update;if b is null then raise exception'Inventory item not found';end if;update public.inventory_items set item_name=trim(p_item_name),sku=nullif(trim(p_sku),''),category=p_category,unit_of_measure=p_unit_of_measure,reorder_level=p_reorder_level,storage_location=nullif(trim(p_storage_location),''),status=p_status,factual_note=trim(p_note),verified_by=u,request_id=p_request_id,updated_at=now()where company_id=c and id=p_item_id returning id into x;e:='updated';end if;select to_jsonb(v)into a from public.inventory_items v where v.company_id=c and v.id=x;insert into public.inventory_item_events(company_id,item_id,event_type,quantity_change,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,e,case when e='created'then p_initial_quantity else null end,b,a,trim(p_note),u,p_request_id);return x;end$$;
create or replace function public.adjust_verified_inventory_stock(p_item_id uuid,p_quantity_change integer,p_note text,p_request_id text)returns uuid language plpgsql security definer set search_path=public as $$declare c uuid:=public.document_intake_company_id();u uuid:=auth.uid();r text:=public.current_business_role();x uuid;b jsonb;a jsonb;q integer;begin if c is null or u is null or r not in('super_admin','owner','safety','maintenance')then raise exception'Not authorized';end if;if p_request_id is null or char_length(p_request_id)not between 8 and 200 or p_quantity_change is null or p_quantity_change=0 or abs(p_quantity_change)>1000000 or char_length(trim(p_note))not between 3 and 2000 then raise exception'Invalid stock adjustment';end if;select item_id into x from public.inventory_item_events where company_id=c and request_id=p_request_id;if x is not null then return x;end if;select to_jsonb(v),v.quantity_on_hand into b,q from public.inventory_items v where v.company_id=c and v.id=p_item_id and v.status='active'for update;if b is null then raise exception'Active inventory item not found';end if;if q+p_quantity_change<0 then raise exception'Adjustment exceeds recorded stock';end if;update public.inventory_items set quantity_on_hand=q+p_quantity_change,updated_at=now(),verified_by=u where company_id=c and id=p_item_id returning id into x;select to_jsonb(v)into a from public.inventory_items v where v.company_id=c and v.id=x;insert into public.inventory_item_events(company_id,item_id,event_type,quantity_change,before_state,after_state,factual_note,actor_user_id,request_id)values(c,x,'stock_adjusted',p_quantity_change,b,a,trim(p_note),u,p_request_id);return x;end$$;
revoke all on function public.list_verified_inventory_items(),public.save_verified_inventory_item(uuid,text,text,text,text,integer,integer,text,text,text,text),public.adjust_verified_inventory_stock(uuid,integer,text,text)from public,anon;grant execute on function public.list_verified_inventory_items(),public.save_verified_inventory_item(uuid,text,text,text,text,integer,integer,text,text,text,text),public.adjust_verified_inventory_stock(uuid,integer,text,text)to authenticated;
commit;
