import { DEMO_TENANT_ID } from "@/lib/data/tenant";
import type {
  CareerPassport,
  EnterpriseRequest,
  WalletActivityItem,
  WalletAuditEntry,
  WalletBadge,
  WalletDocument,
  WalletIdentity,
  WalletNotification,
  WalletPrivacyControls,
  WalletShareLink,
  WalletTrustScore,
} from "@/lib/wallet/types";
import { TRUST_SCORE_DISCLAIMER } from "@/lib/wallet/types";

const NOW = "2026-07-17T12:00:00.000Z";

export const WALLET_OWNER_ID = "wallet-owner-demo";

export const seedIdentity: WalletIdentity = {
  fullName: "Jordan Reyes",
  preferredName: "Jordan",
  headline: "CDL-A driver · Hazmat & tanker · 11 years safe",
  photoInitials: "JR",
  email: "jordan.reyes@example.com",
  phone: "(210) 555-0142",
  locationCity: "San Antonio",
  locationState: "TX",
  yearsExperience: 11,
  languages: ["English", "Spanish"],
  specialSkills: ["Hazmat", "Team driving", "Reefer", "ELD proficient"],
  equipmentExperience: ["Sleeper", "Day cab", "Automatic", "Manual"],
  trailerExperience: ["Dry van", "Reefer", "Tanker", "Flatbed"],
  statesDriven: ["TX", "OK", "LA", "AR", "NM", "AZ", "CA", "CO", "KS", "MO"],
  countriesDriven: ["United States"],
};

export const seedDocuments: WalletDocument[] = [
  {
    id: "wd-identity",
    title: "Professional identity profile",
    category: "identity",
    status: "valid",
    sensitivity: "standard",
    summary: "Verified name, contact, and career headline for Career Passport.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-06-01T10:00:00.000Z",
  },
  {
    id: "wd-gov-id",
    title: "Texas state ID",
    category: "government_id",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2022-03-12",
    expiresAt: "2030-03-12",
    issuer: "Texas DPS",
    numberMasked: "••••-4821",
    summary: "Government-issued photo ID on file.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "tx-state-id.pdf",
    updatedAt: "2026-05-20T14:00:00.000Z",
  },
  {
    id: "wd-dl",
    title: "Class C driver license",
    category: "drivers_license",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2021-08-01",
    expiresAt: "2029-08-01",
    issuer: "Texas DPS",
    numberMasked: "••••-9910",
    summary: "Personal driver license (non-CDL).",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "tx-dl.pdf",
    updatedAt: "2026-04-11T09:00:00.000Z",
  },
  {
    id: "wd-cdl",
    title: "CDL Class A",
    category: "cdl",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2015-06-18",
    expiresAt: "2027-06-18",
    issuer: "Texas DPS",
    numberMasked: "••••-7742",
    summary: "Commercial Driver License Class A with clean record flags.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "cdl-class-a-jordan-reyes.pdf",
    updatedAt: "2026-06-15T11:00:00.000Z",
  },
  {
    id: "wd-medical",
    title: "DOT medical certificate",
    category: "medical",
    status: "expiring",
    sensitivity: "restricted",
    issuedAt: "2025-09-01",
    expiresAt: "2026-09-01",
    issuer: "San Antonio Occupational Health",
    summary: "Medical examiner certificate — renew within 45 days.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "dot-medical-2025.pdf",
    updatedAt: "2025-09-02T08:00:00.000Z",
  },
  {
    id: "wd-twic",
    title: "TWIC card",
    category: "twic",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2023-01-20",
    expiresAt: "2028-01-20",
    issuer: "TSA",
    numberMasked: "••••-3301",
    summary: "Transportation Worker Identification Credential.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "twic-card.pdf",
    updatedAt: "2026-01-10T12:00:00.000Z",
  },
  {
    id: "wd-passport",
    title: "US passport",
    category: "passport",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2019-11-04",
    expiresAt: "2029-11-04",
    issuer: "US Department of State",
    numberMasked: "••••-1188",
    summary: "Passport book for cross-border and identity verification.",
    requiresConsent: true,
    consentGranted: false,
    verified: true,
    fileName: "us-passport.pdf",
    updatedAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "wd-visa",
    title: "Work visa (N/A — US citizen)",
    category: "visa",
    status: "valid",
    sensitivity: "standard",
    summary: "No visa required — US citizen status on file.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wd-work-auth",
    title: "I-9 employment eligibility",
    category: "work_auth",
    status: "valid",
    sensitivity: "restricted",
    issuedAt: "2024-02-12",
    issuer: "Lone Star Alpha Carrier",
    summary: "Employment eligibility verification completed.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "i9-section.pdf",
    updatedAt: "2024-02-12T16:00:00.000Z",
  },
  {
    id: "wd-end-hazmat",
    title: "Hazmat endorsement",
    category: "endorsement",
    status: "valid",
    sensitivity: "sensitive",
    endorsement: "hazmat",
    issuedAt: "2020-04-01",
    expiresAt: "2027-06-18",
    issuer: "Texas DPS",
    summary: "H endorsement — hazardous materials.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "wd-end-tanker",
    title: "Tanker endorsement",
    category: "endorsement",
    status: "valid",
    sensitivity: "sensitive",
    endorsement: "tanker",
    issuedAt: "2018-09-12",
    expiresAt: "2027-06-18",
    issuer: "Texas DPS",
    summary: "N endorsement — tank vehicles.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "wd-end-doubles",
    title: "Doubles / triples endorsement",
    category: "endorsement",
    status: "valid",
    sensitivity: "sensitive",
    endorsement: "doubles",
    issuedAt: "2017-05-22",
    expiresAt: "2027-06-18",
    issuer: "Texas DPS",
    summary: "T endorsement — double/triple trailers.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "wd-training-defensive",
    title: "Defensive driving certificate",
    category: "safety_training",
    status: "valid",
    sensitivity: "standard",
    issuedAt: "2025-11-10",
    expiresAt: "2027-11-10",
    issuer: "National Safety Council",
    summary: "Completed defensive driving for commercial operators.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    fileName: "defensive-driving-cert.pdf",
    updatedAt: "2025-11-11T08:00:00.000Z",
  },
  {
    id: "wd-training-hazmat",
    title: "Hazmat awareness training",
    category: "safety_training",
    status: "expiring",
    sensitivity: "standard",
    issuedAt: "2024-08-01",
    expiresAt: "2026-08-01",
    issuer: "FMCSA-approved provider",
    summary: "Annual hazmat awareness refresher due soon.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    fileName: "hazmat-awareness-2024.pdf",
    updatedAt: "2024-08-02T10:00:00.000Z",
  },
  {
    id: "wd-contract",
    title: "Driver employment agreement",
    category: "employment_contract",
    status: "valid",
    sensitivity: "sensitive",
    issuedAt: "2024-02-12",
    issuer: "Lone Star Alpha Carrier",
    summary: "Current company employment contract.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "employment-agreement.pdf",
    updatedAt: "2024-02-12T17:00:00.000Z",
  },
  {
    id: "wd-history",
    title: "Employment history packet",
    category: "employment_history",
    status: "valid",
    sensitivity: "standard",
    summary: "Verified work history across 4 carriers (11 years).",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    fileName: "employment-history.pdf",
    updatedAt: "2026-05-01T12:00:00.000Z",
  },
  {
    id: "wd-ref-1",
    title: "Reference — Dispatch manager",
    category: "reference",
    status: "valid",
    sensitivity: "standard",
    issuer: "Horizon Freight Lines",
    summary: "Professional reference from prior dispatch leadership.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-04-20T11:00:00.000Z",
  },
  {
    id: "wd-rec-1",
    title: "Recommendation letter",
    category: "recommendation",
    status: "valid",
    sensitivity: "standard",
    issuedAt: "2023-12-01",
    issuer: "Summit Flatbed Co.",
    summary: "Letter of recommendation for reliability and safety.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    fileName: "recommendation-summit.pdf",
    updatedAt: "2023-12-02T09:00:00.000Z",
  },
  {
    id: "wd-review",
    title: "2025 performance review",
    category: "performance_review",
    status: "valid",
    sensitivity: "standard",
    issuedAt: "2025-12-15",
    issuer: "Lone Star Alpha Carrier",
    summary: "Exceeds expectations — on-time and safety metrics.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "perf-review-2025.pdf",
    updatedAt: "2025-12-16T10:00:00.000Z",
  },
  {
    id: "wd-award",
    title: "Million mile safe driving award",
    category: "safety_award",
    status: "valid",
    sensitivity: "public",
    issuedAt: "2024-06-01",
    issuer: "Lone Star Alpha Carrier",
    summary: "Recognized for one million safe miles.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    updatedAt: "2024-06-02T08:00:00.000Z",
  },
  {
    id: "wd-violations",
    title: "Violation history summary",
    category: "violation_history",
    status: "valid",
    sensitivity: "restricted",
    summary:
      "Authorized viewers only. No serious violations in the last 36 months.",
    requiresConsent: true,
    consentGranted: false,
    verified: true,
    fileName: "violation-history-sealed.pdf",
    updatedAt: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "wd-drug",
    title: "Pre-employment drug screen",
    category: "drug_test",
    status: "valid",
    sensitivity: "restricted",
    issuedAt: "2024-02-10",
    expiresAt: "2027-02-10",
    issuer: "Quest Diagnostics (demo)",
    summary: "Negative result on file. Shared only with permitted parties.",
    requiresConsent: true,
    consentGranted: false,
    verified: true,
    fileName: "drug-screen-2024.pdf",
    updatedAt: "2024-02-11T09:00:00.000Z",
  },
  {
    id: "wd-mvr",
    title: "Background & MVR report",
    category: "background_mvr",
    status: "valid",
    sensitivity: "restricted",
    issuedAt: "2024-02-08",
    expiresAt: "2027-02-08",
    issuer: "Authorized screening partner (demo)",
    summary: "Clear MVR summary. Requires explicit consent to share.",
    requiresConsent: true,
    consentGranted: false,
    verified: true,
    fileName: "mvr-background-2024.pdf",
    updatedAt: "2024-02-09T11:00:00.000Z",
  },
  {
    id: "wd-insurance",
    title: "Occupational accident insurance",
    category: "insurance",
    status: "expiring",
    sensitivity: "sensitive",
    issuedAt: "2025-08-01",
    expiresAt: "2026-08-15",
    issuer: "Progressive Commercial (demo)",
    summary: "Policy certificate — renewal window open.",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    fileName: "occ-accident-coi.pdf",
    updatedAt: "2025-08-02T10:00:00.000Z",
  },
  {
    id: "wd-biz-license",
    title: "Owner-operator authority packet",
    category: "business_license",
    status: "pending_review",
    sensitivity: "sensitive",
    summary: "Optional OO authority docs awaiting verification.",
    requiresConsent: true,
    consentGranted: true,
    verified: false,
    fileName: "oo-authority-draft.pdf",
    updatedAt: "2026-07-10T15:00:00.000Z",
  },
  {
    id: "wd-company-cert",
    title: "Carrier safety certification",
    category: "company_cert",
    status: "valid",
    sensitivity: "standard",
    issuedAt: "2025-01-15",
    expiresAt: "2027-01-15",
    issuer: "Lone Star Alpha Carrier",
    summary: "Company-issued safety program completion.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    updatedAt: "2025-01-16T09:00:00.000Z",
  },
  {
    id: "wd-tax",
    title: "W-4 tax withholding",
    category: "tax",
    status: "valid",
    sensitivity: "restricted",
    issuedAt: "2024-02-12",
    issuer: "IRS / Employer",
    summary: "Tax withholding form — not shared without consent.",
    requiresConsent: true,
    consentGranted: false,
    verified: true,
    fileName: "w4-2024.pdf",
    updatedAt: "2024-02-12T18:00:00.000Z",
  },
  {
    id: "wd-emergency",
    title: "Emergency contacts",
    category: "emergency_contact",
    status: "valid",
    sensitivity: "sensitive",
    summary: "Primary: Maria Reyes · (210) 555-0199",
    requiresConsent: true,
    consentGranted: true,
    verified: true,
    updatedAt: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "wd-photo",
    title: "Profile photo",
    category: "photo",
    status: "valid",
    sensitivity: "public",
    summary: "Career Passport profile image.",
    requiresConsent: false,
    consentGranted: true,
    verified: true,
    fileName: "profile-jordan.jpg",
    updatedAt: "2026-05-01T08:00:00.000Z",
  },
  {
    id: "wd-video",
    title: "Safety orientation video",
    category: "video",
    status: "valid",
    sensitivity: "standard",
    summary: "Uploaded orientation completion clip (demo).",
    requiresConsent: false,
    consentGranted: true,
    verified: false,
    fileName: "orientation-clip.mp4",
    updatedAt: "2026-02-20T14:00:00.000Z",
  },
];

export const seedPassport: CareerPassport = {
  identity: seedIdentity,
  timeline: [
    {
      id: "pt-1",
      date: "2015-06",
      title: "Earned CDL Class A",
      detail: "Completed CDL training and passed skills test in San Antonio.",
      kind: "milestone",
      verified: true,
    },
    {
      id: "pt-2",
      date: "2015-08",
      title: "Joined Horizon Freight Lines",
      detail: "Regional reefer lanes across the Southeast.",
      kind: "employment",
      verified: true,
    },
    {
      id: "pt-3",
      date: "2018-09",
      title: "Tanker endorsement",
      detail: "Added N endorsement; began liquid bulk runs.",
      kind: "certification",
      verified: true,
    },
    {
      id: "pt-4",
      date: "2020-04",
      title: "Hazmat endorsement",
      detail: "H endorsement after TSA threat assessment.",
      kind: "certification",
      verified: true,
    },
    {
      id: "pt-5",
      date: "2021-03",
      title: "Summit Flatbed Co.",
      detail: "Flatbed and step-deck specialist — construction lanes.",
      kind: "employment",
      verified: true,
    },
    {
      id: "pt-6",
      date: "2023-12",
      title: "Recommendation letter",
      detail: "Verified letter from Summit Flatbed leadership.",
      kind: "review",
      verified: true,
    },
    {
      id: "pt-7",
      date: "2024-02",
      title: "Lone Star Alpha Carrier",
      detail: "Current company — hazmat & tanker dedicated.",
      kind: "employment",
      verified: true,
    },
    {
      id: "pt-8",
      date: "2024-06",
      title: "Million mile safe driving",
      detail: "Company safety award for one million safe miles.",
      kind: "award",
      verified: true,
    },
    {
      id: "pt-9",
      date: "2025-11",
      title: "Defensive driving refresh",
      detail: "National Safety Council certificate renewed.",
      kind: "training",
      verified: true,
    },
  ],
  companies: [
    {
      id: "pc-1",
      name: "Lone Star Alpha Carrier",
      role: "CDL-A Driver · Hazmat / Tanker",
      startDate: "2024-02",
      current: true,
      verified: true,
    },
    {
      id: "pc-2",
      name: "Summit Flatbed Co.",
      role: "Flatbed Driver",
      startDate: "2021-03",
      endDate: "2024-01",
      verified: true,
    },
    {
      id: "pc-3",
      name: "Horizon Freight Lines",
      role: "Reefer Driver",
      startDate: "2015-08",
      endDate: "2021-02",
      verified: true,
    },
  ],
  awards: [
    {
      id: "pa-1",
      title: "Million Mile Safe Driver",
      year: "2024",
      issuer: "Lone Star Alpha Carrier",
    },
    {
      id: "pa-2",
      title: "Zero preventable accidents — 5 years",
      year: "2023",
      issuer: "Summit Flatbed Co.",
    },
  ],
  reviews: [
    {
      id: "pr-1",
      author: "Alex Chen",
      role: "Fleet Manager",
      rating: 5,
      body: "Reliable, communicates early, and treats equipment like their own.",
      verified: true,
      createdAt: "2026-01-14T12:00:00.000Z",
    },
    {
      id: "pr-2",
      author: "Sam Ortiz",
      role: "Dispatcher",
      rating: 5,
      body: "Always on time for appointments. Easy to plan around.",
      verified: true,
      createdAt: "2025-08-22T12:00:00.000Z",
    },
  ],
  trainingHighlights: [
    "Defensive driving (NSC)",
    "Hazmat awareness",
    "ELD hours-of-service mastery",
    "Cold-chain handling",
  ],
  achievements: [
    "11 years commercial experience",
    "Million safe miles",
    "Hazmat + tanker + doubles endorsements",
    "Bilingual (English / Spanish)",
  ],
};

export const seedShareLinks: WalletShareLink[] = [
  {
    id: "ws-1",
    token: "share-demo-cdl-medical",
    label: "Horizon hiring packet",
    scopes: ["cdl_only", "medical", "read_only"],
    createdAt: "2026-07-10T10:00:00.000Z",
    expiresAt: "2026-08-10T10:00:00.000Z",
    viewCount: 3,
    recipientHint: "Horizon Freight recruiting",
  },
  {
    id: "ws-2",
    token: "share-demo-certs",
    label: "Certifications for broker audit",
    scopes: ["certifications", "read_only"],
    createdAt: "2026-07-01T09:00:00.000Z",
    expiresAt: "2026-07-20T09:00:00.000Z",
    viewCount: 1,
    recipientHint: "Broker compliance desk",
  },
  {
    id: "ws-3",
    token: "share-demo-revoked",
    label: "Old full-wallet share",
    scopes: ["entire_wallet"],
    createdAt: "2026-05-01T09:00:00.000Z",
    expiresAt: "2026-06-01T09:00:00.000Z",
    revokedAt: "2026-05-15T14:00:00.000Z",
    viewCount: 5,
    recipientHint: "Former recruiter",
  },
];

export const seedBadges: WalletBadge[] = [
  {
    id: "verified_driver",
    earnedAt: "2024-02-20T12:00:00.000Z",
    verified: true,
    description: "Identity and CDL verified on Transpo.ai",
  },
  {
    id: "safe_driver_5yr",
    earnedAt: "2023-06-01T12:00:00.000Z",
    verified: true,
    description: "Five consecutive years without preventable accidents",
  },
  {
    id: "safe_driver_10yr",
    earnedAt: "2025-06-01T12:00:00.000Z",
    verified: true,
    description: "Ten years of verified safe driving history",
  },
  {
    id: "million_mile",
    earnedAt: "2024-06-01T12:00:00.000Z",
    verified: true,
    description: "One million safe miles documented",
  },
  {
    id: "top_rated",
    earnedAt: "2026-01-01T12:00:00.000Z",
    verified: true,
    description: "Consistently high verified peer and employer ratings",
  },
];

export const seedTrustScore: WalletTrustScore = {
  score: 92,
  updatedAt: NOW,
  disclaimer: TRUST_SCORE_DISCLAIMER,
  factors: [
    {
      id: "f-identity",
      label: "Identity & license verification",
      score: 98,
      weight: 0.25,
      hint: "CDL and identity documents verified",
    },
    {
      id: "f-safety",
      label: "Safety history",
      score: 96,
      weight: 0.25,
      hint: "Awards and clean operational record signals",
    },
    {
      id: "f-completeness",
      label: "Wallet completeness",
      score: 88,
      weight: 0.2,
      hint: "Most career documents on file",
    },
    {
      id: "f-tenure",
      label: "Experience & tenure",
      score: 94,
      weight: 0.15,
      hint: "11 years verified employment",
    },
    {
      id: "f-reviews",
      label: "Verified reviews",
      score: 90,
      weight: 0.15,
      hint: "Employer reviews corroborate reliability",
    },
  ],
};

export const seedNotifications: WalletNotification[] = [
  {
    id: "wn-1",
    kind: "medical_expiry",
    title: "Medical card renews soon",
    body: "DOT medical certificate expires Sep 1, 2026. Upload a replacement when ready.",
    createdAt: "2026-07-16T08:00:00.000Z",
    read: false,
    href: "/wallet/documents/wd-medical",
  },
  {
    id: "wn-2",
    kind: "insurance_expiry",
    title: "Insurance certificate expiring",
    body: "Occupational accident certificate renews Aug 15, 2026.",
    createdAt: "2026-07-15T09:00:00.000Z",
    read: false,
    href: "/wallet/documents/wd-insurance",
  },
  {
    id: "wn-3",
    kind: "cert_expiry",
    title: "Hazmat training refresher",
    body: "Hazmat awareness training expires Aug 1, 2026.",
    createdAt: "2026-07-14T10:00:00.000Z",
    read: true,
    href: "/wallet/documents/wd-training-hazmat",
  },
  {
    id: "wn-4",
    kind: "job_match",
    title: "New hazmat job match",
    body: "Alph found a regional hazmat role that matches your endorsements.",
    createdAt: "2026-07-13T14:00:00.000Z",
    read: false,
    href: "/workforce/jobs",
  },
  {
    id: "wn-5",
    kind: "enterprise_request",
    title: "Document request from Horizon",
    body: "Horizon Freight Lines requested CDL and medical for hiring review.",
    createdAt: "2026-07-12T11:00:00.000Z",
    read: false,
    href: "/wallet/enterprise",
  },
  {
    id: "wn-6",
    kind: "reference_request",
    title: "Reference check requested",
    body: "A recruiter asked to contact your listed dispatch reference.",
    createdAt: "2026-07-11T16:00:00.000Z",
    read: true,
    href: "/wallet/sharing",
  },
];

export const seedEnterpriseRequests: EnterpriseRequest[] = [
  {
    id: "er-1",
    companyName: "Horizon Freight Lines",
    requestedBy: "Maya Brooks · Recruiting",
    documentCategories: ["cdl", "medical", "safety_training"],
    message: "Please share CDL, medical, and current safety certs for offer packet.",
    status: "pending",
    createdAt: "2026-07-12T11:00:00.000Z",
    dueAt: "2026-07-22",
    requiredCerts: ["Defensive driving", "Hazmat awareness"],
  },
  {
    id: "er-2",
    companyName: "Lone Star Alpha Carrier",
    requestedBy: "Safety desk",
    documentCategories: ["insurance", "company_cert"],
    message: "Annual compliance refresh — insurance COI and company safety cert.",
    status: "approved",
    createdAt: "2026-07-05T09:00:00.000Z",
    dueAt: "2026-07-30",
  },
  {
    id: "er-3",
    companyName: "Summit Flatbed Co.",
    requestedBy: "HR Onboarding",
    documentCategories: ["background_mvr", "drug_test"],
    message: "Background/MVR and drug screen for rehire consideration.",
    status: "denied",
    createdAt: "2026-06-20T10:00:00.000Z",
  },
];

export const seedAuditLog: WalletAuditEntry[] = [
  {
    id: "wa-1",
    at: "2026-07-16T08:05:00.000Z",
    actor: "System",
    action: "viewed",
    summary: "Expiration monitor flagged medical card",
    entityType: "document",
    entityId: "wd-medical",
  },
  {
    id: "wa-2",
    at: "2026-07-12T11:10:00.000Z",
    actor: "Jordan Reyes",
    action: "shared",
    summary: "Created share link for Horizon hiring packet",
    entityType: "share",
    entityId: "ws-1",
  },
  {
    id: "wa-3",
    at: "2026-07-05T09:30:00.000Z",
    actor: "Jordan Reyes",
    action: "enterprise_approved",
    summary: "Approved Lone Star compliance document request",
    entityType: "enterprise_request",
    entityId: "er-2",
  },
  {
    id: "wa-4",
    at: "2026-06-20T10:15:00.000Z",
    actor: "Jordan Reyes",
    action: "enterprise_denied",
    summary: "Denied Summit background/MVR request (consent not granted)",
    entityType: "enterprise_request",
    entityId: "er-3",
  },
  {
    id: "wa-5",
    at: "2026-05-15T14:00:00.000Z",
    actor: "Jordan Reyes",
    action: "revoked_share",
    summary: "Revoked old full-wallet share link",
    entityType: "share",
    entityId: "ws-3",
  },
];

export const seedPrivacy: WalletPrivacyControls = {
  consents: {
    share_identity: true,
    share_medical: true,
    share_violations: false,
    share_drug_tests: false,
    share_background_mvr: false,
    enterprise_requests: true,
    job_match_alerts: true,
  },
  showTrustScorePublicly: true,
  allowEnterpriseRequests: true,
  mfaEnabled: true,
  biometricPreferred: false,
};

export const seedActivity: WalletActivityItem[] = [
  {
    id: "act-1",
    at: "2026-07-16T08:05:00.000Z",
    summary: "Medical card flagged as expiring soon",
    href: "/wallet/documents/wd-medical",
  },
  {
    id: "act-2",
    at: "2026-07-12T11:10:00.000Z",
    summary: "Shared CDL + medical with Horizon recruiting",
    href: "/wallet/sharing",
  },
  {
    id: "act-3",
    at: "2026-07-10T15:00:00.000Z",
    summary: "Uploaded owner-operator authority draft",
    href: "/wallet/documents/wd-biz-license",
  },
  {
    id: "act-4",
    at: "2026-07-05T09:30:00.000Z",
    summary: "Approved company compliance document request",
    href: "/wallet/enterprise",
  },
];

export const WALLET_TENANT_ID = DEMO_TENANT_ID;
