import type { EldCatalogProvider, EldDataType } from "./types";

const FULL_FLEET: EldDataType[] = [
  "live_gps",
  "vehicle_mileage",
  "state_mileage",
  "driver_hos",
  "driver_status",
  "engine_hours",
  "fuel_data",
  "fault_codes",
  "truck_information",
  "trailer_information",
  "dash_camera_events",
];

const CORE_HOS: EldDataType[] = [
  "live_gps",
  "vehicle_mileage",
  "state_mileage",
  "driver_hos",
  "driver_status",
  "engine_hours",
  "truck_information",
];

const MILEAGE_FOCUS: EldDataType[] = [
  "vehicle_mileage",
  "state_mileage",
  "fuel_data",
  "truck_information",
];

/**
 * Static ELD provider directory.
 * Connection overrides live in the store; Samsara stays in sync with Integration Center.
 */
export const ELD_CATALOG: EldCatalogProvider[] = [
  {
    id: "samsara",
    name: "Samsara",
    initials: "SA",
    description: "Fleet GPS, HOS, fault codes, and dashcam streams.",
    status: "connected",
    supportCategory: "technically_supported",
    dataTypes: FULL_FLEET,
    lastVerificationDate: "2026-07-10",
    integrationProviderId: "samsara",
    docsUrl: "https://developers.samsara.com/",
    contactEmail: "partners@samsara.com",
    apiDifficulty: 2,
    businessValue: 5,
    apiAvailabilityScore: 1,
  },
  {
    id: "motive",
    name: "Motive",
    initials: "MO",
    description: "ELD hours, GPS, and camera events from Motive vehicles.",
    status: "available",
    supportCategory: "technically_supported",
    dataTypes: FULL_FLEET,
    lastVerificationDate: "2026-07-08",
    integrationProviderId: "motive",
    docsUrl: "https://developer.gomotive.com/",
    contactEmail: "api@gomotive.com",
    apiDifficulty: 2,
    businessValue: 5,
    apiAvailabilityScore: 1,
  },
  {
    id: "geotab",
    name: "Geotab",
    initials: "GT",
    description: "Telematics, engine diagnostics, and maintenance signals.",
    status: "available",
    supportCategory: "technically_supported",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "state_mileage",
      "driver_hos",
      "driver_status",
      "engine_hours",
      "fuel_data",
      "fault_codes",
      "truck_information",
      "trailer_information",
    ],
    lastVerificationDate: "2026-07-05",
    integrationProviderId: "geotab",
    docsUrl: "https://developers.geotab.com/",
    contactEmail: "partners@geotab.com",
    apiDifficulty: 3,
    businessValue: 5,
    apiAvailabilityScore: 1,
  },
  {
    id: "omnitracs",
    name: "Omnitracs",
    initials: "OM",
    description: "Enterprise ELD and fleet operations platform.",
    status: "partnership_required",
    supportCategory: "waiting_eld_approval",
    dataTypes: CORE_HOS,
    unavailableReason:
      "Omnitracs requires an approved partner agreement before API credentials can be issued.",
    lastVerificationDate: "2026-06-20",
    integrationProviderId: "omnitracs",
    docsUrl: "https://www.omnitracs.com/",
    contactEmail: "alliances@omnitracs.com",
    apiDifficulty: 4,
    businessValue: 4,
    apiAvailabilityScore: 0.5,
  },
  {
    id: "keeptruckin_legacy",
    name: "KeepTruckin (Legacy)",
    initials: "KT",
    description:
      "Legacy KeepTruckin ELD accounts — migrated brands may still use older APIs.",
    status: "api_restricted",
    supportCategory: "waiting_eld_approval",
    dataTypes: CORE_HOS,
    unavailableReason:
      "Legacy KeepTruckin API access is restricted to Motive-managed partner programs.",
    lastVerificationDate: "2026-05-28",
    contactEmail: "api@gomotive.com",
    apiDifficulty: 4,
    businessValue: 3,
    apiAvailabilityScore: 0.5,
  },
  {
    id: "peoplenet",
    name: "PeopleNet",
    initials: "PN",
    description: "Trimble PeopleNet ELD and onboard computing.",
    status: "partnership_required",
    supportCategory: "waiting_eld_approval",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "driver_hos",
      "driver_status",
      "engine_hours",
      "truck_information",
      "fault_codes",
    ],
    unavailableReason:
      "PeopleNet / Trimble partner onboarding is required before live data access.",
    lastVerificationDate: "2026-06-02",
    contactEmail: "partners@trimble.com",
    apiDifficulty: 4,
    businessValue: 4,
    apiAvailabilityScore: 0.5,
  },
  {
    id: "orbcomm",
    name: "Orbcomm",
    initials: "OR",
    description: "Satellite and cellular telematics for long-haul fleets.",
    status: "under_review",
    supportCategory: "requested_by_carriers",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "engine_hours",
      "fuel_data",
      "truck_information",
      "trailer_information",
    ],
    unavailableReason:
      "CarrierOS is reviewing Orbcomm API docs and carrier demand before scheduling development.",
    lastVerificationDate: "2026-06-15",
    contactEmail: "partners@orbcomm.com",
    apiDifficulty: 3,
    businessValue: 3,
    apiAvailabilityScore: 1,
  },
  {
    id: "xirgo",
    name: "Xirgo",
    initials: "XI",
    description: "Asset tracking and trailer telematics hardware.",
    status: "api_restricted",
    supportCategory: "waiting_eld_approval",
    dataTypes: [
      "live_gps",
      "trailer_information",
      "truck_information",
      "engine_hours",
    ],
    unavailableReason:
      "Xirgo APIs are available only to approved OEM / integrator accounts.",
    lastVerificationDate: "2026-05-12",
    contactEmail: "integrations@xirgo.com",
    apiDifficulty: 3,
    businessValue: 2,
    apiAvailabilityScore: 0.5,
  },
  {
    id: "verizon_connect",
    name: "Verizon Connect",
    initials: "VC",
    description: "Fleet tracking, compliance, and workforce apps.",
    status: "partnership_required",
    supportCategory: "waiting_eld_approval",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "state_mileage",
      "driver_hos",
      "driver_status",
      "fuel_data",
      "truck_information",
      "dash_camera_events",
    ],
    unavailableReason:
      "Verizon Connect requires a signed integration partnership before OAuth apps are approved.",
    lastVerificationDate: "2026-06-28",
    docsUrl: "https://www.verizonconnect.com/",
    contactEmail: "partners@verizonconnect.com",
    apiDifficulty: 4,
    businessValue: 4,
    apiAvailabilityScore: 0.5,
  },
  {
    id: "fleet_complete",
    name: "Fleet Complete",
    initials: "FC",
    description: "Canadian-rooted telematics with North American coverage.",
    status: "available",
    supportCategory: "technically_supported",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "state_mileage",
      "driver_hos",
      "driver_status",
      "fuel_data",
      "truck_information",
    ],
    lastVerificationDate: "2026-07-01",
    docsUrl: "https://www.fleetcomplete.com/",
    contactEmail: "api@fleetcomplete.com",
    apiDifficulty: 3,
    businessValue: 3,
    apiAvailabilityScore: 1,
  },
  {
    id: "azuga",
    name: "Azuga",
    initials: "AZ",
    description: "GPS fleet tracking and driver safety scoring.",
    status: "available",
    supportCategory: "technically_supported",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "fuel_data",
      "engine_hours",
      "truck_information",
      "dash_camera_events",
    ],
    lastVerificationDate: "2026-06-22",
    contactEmail: "integrations@azuga.com",
    apiDifficulty: 2,
    businessValue: 3,
    apiAvailabilityScore: 1,
  },
  {
    id: "abc_eld",
    name: "ABC ELD",
    initials: "AB",
    description: "Budget ELD hardware with closed portal — no public developer API.",
    status: "no_public_api",
    supportCategory: "unsupported_no_api",
    dataTypes: MILEAGE_FOCUS,
    unavailableReason:
      "ABC ELD does not publish a public API. Carriers can still request integration and use fallback imports.",
    lastVerificationDate: "2026-04-18",
    contactEmail: "support@abc-eld.example",
    apiDifficulty: 5,
    businessValue: 2,
    apiAvailabilityScore: 0,
    fictional: true,
  },
  {
    id: "midwest_elog",
    name: "Midwest eLog",
    initials: "ME",
    description: "Regional ELD popular with Midwestern owner-operators.",
    status: "no_public_api",
    supportCategory: "unsupported_no_api",
    dataTypes: ["driver_hos", "driver_status", "vehicle_mileage"],
    unavailableReason:
      "Midwest eLog only offers CSV exports from their portal — no partner API exists today.",
    lastVerificationDate: "2026-03-30",
    contactEmail: "help@midwestelog.example",
    apiDifficulty: 5,
    businessValue: 2,
    apiAvailabilityScore: 0,
    fictional: true,
  },
  {
    id: "trailblazer_eld",
    name: "Trailblazer ELD",
    initials: "TB",
    description: "Niche ELD bundled with fuel cards — partnership-only data access.",
    status: "partnership_required",
    supportCategory: "waiting_eld_approval",
    dataTypes: [
      "live_gps",
      "vehicle_mileage",
      "state_mileage",
      "fuel_data",
      "driver_hos",
    ],
    unavailableReason:
      "Trailblazer shares data only after a carrier-sponsored partnership request is approved.",
    lastVerificationDate: "2026-05-05",
    contactEmail: "partners@trailblazereld.example",
    apiDifficulty: 4,
    businessValue: 2,
    apiAvailabilityScore: 0.5,
    fictional: true,
  },
  {
    id: "horizon_telematics",
    name: "Horizon Telematics",
    initials: "HT",
    description: "Specialty hazmat telematics with limited third-party access.",
    status: "not_yet_supported",
    supportCategory: "requested_by_carriers",
    dataTypes: [
      "live_gps",
      "fault_codes",
      "truck_information",
      "engine_hours",
    ],
    unavailableReason:
      "Not yet in the CarrierOS roadmap. Submitting a request helps us prioritize.",
    lastVerificationDate: "2026-04-02",
    contactEmail: "sales@horizontelematics.example",
    apiDifficulty: 4,
    businessValue: 2,
    apiAvailabilityScore: 0.5,
    fictional: true,
  },
  {
    id: "quartz_eld",
    name: "Quartz ELD",
    initials: "QZ",
    description: "Lightweight ELD app with opaque data exports.",
    status: "no_public_api",
    supportCategory: "unsupported_no_api",
    dataTypes: ["driver_hos", "vehicle_mileage"],
    unavailableReason:
      "Quartz ELD has no public or partner API. Use report uploads or ask them to open access.",
    lastVerificationDate: "2026-02-14",
    contactEmail: "support@quartzeld.example",
    apiDifficulty: 5,
    businessValue: 1,
    apiAvailabilityScore: 0,
    fictional: true,
  },
  {
    id: "atlas_fleet",
    name: "Atlas Fleet ELD",
    initials: "AF",
    description: "Growing ELD with developer beta — under CarrierOS review.",
    status: "under_review",
    supportCategory: "requested_by_carriers",
    dataTypes: CORE_HOS.concat(["fuel_data", "fault_codes"]),
    unavailableReason:
      "Atlas Fleet opened a developer beta. CarrierOS is validating scopes and rate limits.",
    lastVerificationDate: "2026-07-12",
    contactEmail: "developers@atlasfleet.example",
    apiDifficulty: 3,
    businessValue: 3,
    apiAvailabilityScore: 1,
    fictional: true,
  },
  {
    id: "riglink_eld",
    name: "RigLink ELD",
    initials: "RL",
    description: "Owner-operator focused ELD with email-only support.",
    status: "not_yet_supported",
    supportCategory: "requested_by_carriers",
    dataTypes: ["live_gps", "driver_hos", "vehicle_mileage"],
    unavailableReason:
      "Carrier requests are accumulating. No technical connection is available yet.",
    lastVerificationDate: "2026-05-20",
    contactEmail: "hello@riglinkeld.example",
    apiDifficulty: 4,
    businessValue: 2,
    apiAvailabilityScore: 0,
    fictional: true,
  },
];

export function getEldCatalogProvider(
  id: string,
): EldCatalogProvider | undefined {
  return ELD_CATALOG.find((p) => p.id === id);
}

export function listEldCatalog(): EldCatalogProvider[] {
  return ELD_CATALOG;
}

export function searchEldCatalog(query: string): EldCatalogProvider[] {
  const q = query.trim().toLowerCase();
  if (!q) return ELD_CATALOG;
  return ELD_CATALOG.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.id.includes(q),
  );
}
