"use client";
import { useEffect,useMemo,useState } from "react";
import { getDriverProfilesAction,saveVerifiedDriverProfileAction } from "@/app/actions/drivers";
import Sidebar from "@/components/Sidebar";
import type { DriverAccountOption,DriverProfile } from "@/lib/drivers/profiles";

export default function DriversPage(){
  const[profiles,setProfiles]=useState<DriverProfile[]>([]);const[accounts,setAccounts]=useState<DriverAccountOption[]>([]);const[canManage,setCanManage]=useState(false);const[state,setState]=useState<"loading"|"ready"|"denied">("loading");const[editing,setEditing]=useState<DriverProfile|null|"new">(null);
  useEffect(()=>{getDriverProfilesAction().then((result)=>{if(result.ok){setProfiles(result.profiles);setAccounts(result.accounts);setCanManage(result.canManage);setState("ready")}else setState("denied")}).catch(()=>setState("denied"))},[]);
  const metrics=useMemo(()=>({eligible:profiles.filter(eligible).length,attention:profiles.filter((profile)=>!eligible(profile)).length,active:profiles.filter((profile)=>profile.status==="active").length,total:profiles.length}),[profiles]);
  return <main className="min-h-screen bg-[#F5F7FB] text-[#0B1220]"><Sidebar/><section className="min-h-screen px-4 pb-8 pt-20 lg:ml-72 lg:px-8 lg:py-7 xl:px-10"><div className="mx-auto max-w-[1450px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2563EB]">Verified workforce</p><h1 className="mt-2 text-[34px] font-semibold">Driver compliance</h1><p className="mt-2 text-sm text-[#64748B]">Human-verified status, CDL, and medical-card dates.</p></div>{canManage&&<button disabled={!accounts.length} onClick={()=>setEditing("new")} className="rounded-xl bg-[#0F172A] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">Add driver profile</button>}</header>
    {state!=="ready"?<Empty text={state==="loading"?"Loading authorized driver records…":"Driver compliance is restricted to authorized operational and safety roles."}/>:<><section className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric label="Assignment eligible" value={metrics.eligible}/><Metric label="Needs attention" value={metrics.attention} alert={metrics.attention>0}/><Metric label="Active profiles" value={metrics.active}/><Metric label="Total profiles" value={metrics.total}/></section><section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{profiles.length?profiles.map((profile)=><button key={profile.id} onClick={()=>canManage&&setEditing(profile)} className="rounded-[22px] border border-[#DDE5F0] bg-white p-5 text-left hover:border-[#93C5FD]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#2563EB]">Verified driver</p><h2 className="mt-2 text-lg font-semibold">{profile.displayName}</h2><p className="mt-1 text-xs text-[#64748B]">CDL {profile.cdlState} · ending {profile.cdlLastFour}</p></div><Status profile={profile}/></div><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="CDL expires" value={date(profile.cdlExpiresOn)} alert={past(profile.cdlExpiresOn)}/><Fact label="Medical expires" value={date(profile.medicalCardExpiresOn)} alert={past(profile.medicalCardExpiresOn)}/></div><p className="mt-4 text-[11px] text-[#94A3B8]">Verified {date(profile.verifiedAt)}</p></button>):<Empty text={accounts.length?"Create verified compliance profiles for available driver accounts.":"No verified driver accounts are available for compliance setup."}/>}</section></>}
  </div></section>{editing&&<ProfileEditor profile={editing==="new"?null:editing} accounts={accounts} onClose={()=>setEditing(null)} onSaved={(nextProfiles,nextAccounts)=>{setProfiles(nextProfiles);setAccounts(nextAccounts);setEditing(null)}}/>}</main>
}

function ProfileEditor({profile,accounts,onClose,onSaved}:{profile:DriverProfile|null;accounts:DriverAccountOption[];onClose:()=>void;onSaved:(profiles:DriverProfile[],accounts:DriverAccountOption[])=>void}){
  const[driverUserId,setDriverUserId]=useState(profile?.driverUserId??accounts[0]?.userId??"");const[cdlState,setCdlState]=useState(profile?.cdlState??"");const[lastFour,setLastFour]=useState(profile?.cdlLastFour??"");const[cdlDate,setCdlDate]=useState(profile?.cdlExpiresOn??"");const[medicalDate,setMedicalDate]=useState(profile?.medicalCardExpiresOn??"");const[hiredOn,setHiredOn]=useState(profile?.hiredOn??"");const[status,setStatus]=useState<DriverProfile["status"]>(profile?.status??"active");const[note,setNote]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function save(){setBusy(true);setMessage("");const result=await saveVerifiedDriverProfileAction({profileId:profile?.id,driverUserId,cdlState,cdlLastFour:lastFour,cdlExpiresOn:cdlDate,medicalCardExpiresOn:medicalDate,hiredOn,status,note,requestId:crypto.randomUUID()});if(result.ok)onSaved(result.profiles,result.accounts);else setMessage(result.error);setBusy(false)}
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#0F172A]/45 p-5"><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[24px] bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#2563EB]">Human verification</p><h2 className="mt-2 text-xl font-semibold">{profile?profile.displayName:"Add driver profile"}</h2></div><button onClick={onClose} className="h-9 rounded-lg border px-3 text-xs font-semibold">Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{profile?<div className="sm:col-span-2 rounded-xl bg-[#F8FAFC] p-3 text-xs font-semibold">{profile.displayName}</div>:<Select label="Verified same-company driver" value={driverUserId} onChange={setDriverUserId} options={accounts.map((account)=>[account.userId,account.displayName])}/>}<Input label="CDL state" value={cdlState} onChange={(value)=>setCdlState(value.toUpperCase().slice(0,2))}/><Input label="CDL last four only" value={lastFour} onChange={(value)=>setLastFour(value.toUpperCase().slice(0,4))}/><Input label="CDL expires" type="date" value={cdlDate} onChange={setCdlDate}/><Input label="Medical card expires" type="date" value={medicalDate} onChange={setMedicalDate}/><Input label="Hired on" type="date" value={hiredOn} onChange={setHiredOn}/><Select label="Verified status" value={status} onChange={(value)=>setStatus(value as DriverProfile["status"])} options={[["active","Active"],["leave","Leave"],["suspended","Suspended"],["terminated","Terminated"]]}/><div className="sm:col-span-2"><Input label="Factual compliance note" value={note} onChange={setNote}/></div></div><p className="mt-4 rounded-xl bg-[#FFF7ED] p-3 text-[11px] leading-5 text-[#9A3412]">Active status and current dates are necessary system checks, not a substitute for the carrier’s full qualification and safety decision.</p>{message&&<p className="mt-3 rounded-xl bg-[#F8FAFC] p-3 text-xs text-[#475569]">{message}</p>}<button disabled={busy||!driverUserId||cdlState.length!==2||lastFour.length!==4||!cdlDate||!medicalDate} onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-[#0F172A] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{busy?"Saving verified profile…":"Approve & save profile"}</button></section></div>
}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="block text-[10px] font-semibold uppercase tracking-[.12em] text-[#64748B]"><span className="mb-1.5 block">{label}</span><input type={type} value={value} onChange={(event)=>onChange(event.target.value)} className="w-full rounded-xl border border-[#CBD5E1] px-3 py-2.5 text-xs"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="block text-[10px] font-semibold uppercase tracking-[.12em] text-[#64748B]"><span className="mb-1.5 block">{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)} className="w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs">{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-[20px] border p-5 ${alert?"border-[#FCA5A5] bg-[#FEF2F2]":"border-[#DDE5F0] bg-white"}`}><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#64748B]">{label}</p><p className={`mt-3 text-2xl font-semibold ${alert?"text-[#B91C1C]":""}`}>{value}</p></div>}
function Status({profile}:{profile:DriverProfile}){const good=eligible(profile);return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${good?"bg-[#ECFDF5] text-[#047857]":"bg-[#FEE2E2] text-[#B91C1C]"}`}>{good?"eligible":past(profile.cdlExpiresOn)||past(profile.medicalCardExpiresOn)?"expired":profile.status}</span>}
function Fact({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#94A3B8]">{label}</p><p className={`mt-1 text-xs font-semibold ${alert?"text-[#B91C1C]":"text-[#334155]"}`}>{value}</p></div>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-[22px] border border-[#DDE5F0] bg-white p-10 text-center text-sm text-[#64748B]">{text}</div>}
function past(value:string){const parsed=new Date(`${value.slice(0,10)}T23:59:59Z`).getTime();return Number.isNaN(parsed)||parsed<Date.now()}
function eligible(profile:DriverProfile){return profile.status==="active"&&!past(profile.cdlExpiresOn)&&!past(profile.medicalCardExpiresOn)}
function date(value:string){const parsed=new Date(value.length===10?`${value}T00:00:00Z`:value);return Number.isNaN(parsed.getTime())?"Not verified":new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"}).format(parsed)}
