"use client";
import { useEffect, useMemo, useState } from "react";
import { getFleetAssetsAction, saveVerifiedFleetAssetAction } from "@/app/actions/fleet";
import Sidebar from "@/components/Sidebar";
import type { FleetAsset } from "@/lib/fleet/assets";

const EMPTY = { assetType: "truck" as const, unitNumber: "", vin: "", year: "", make: "", model: "", status: "active" as FleetAsset["status"], annualInspectionExpiresOn: "", registrationExpiresOn: "", isReefer: false, note: "" };
export default function FleetPage() {
  const [assets,setAssets]=useState<FleetAsset[]>([]); const [canManage,setCanManage]=useState(false); const [state,setState]=useState<"loading"|"ready"|"denied">("loading"); const [editing,setEditing]=useState<FleetAsset|null|"new">(null);
  useEffect(()=>{getFleetAssetsAction().then((result)=>{if(result.ok){setAssets(result.assets);setCanManage(result.canManage);setState("ready");}else setState("denied");}).catch(()=>setState("denied"));},[]);
  const metrics=useMemo(()=>({active:assets.filter((asset)=>asset.status==="active"&&!expired(asset)).length, attention:assets.filter((asset)=>asset.status!=="active"||expired(asset)).length, trucks:assets.filter((asset)=>asset.assetType==="truck").length, trailers:assets.filter((asset)=>asset.assetType==="trailer").length}),[assets]);
  return <main className="min-h-screen bg-[#F5F7FB] text-[#0B1220]"><Sidebar/><section className="ml-72 min-h-screen px-8 py-7 xl:px-10"><div className="mx-auto max-w-[1450px]">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2563EB]">Verified equipment</p><h1 className="mt-2 text-[34px] font-semibold">Fleet registry</h1><p className="mt-2 text-sm text-[#64748B]">Current human-verified equipment and compliance dates.</p></div>{canManage&&<button onClick={()=>setEditing("new")} className="rounded-xl bg-[#0F172A] px-4 py-2.5 text-xs font-semibold text-white">Add verified asset</button>}</header>
    {state!=="ready"?<Empty text={state==="loading"?"Loading authorized fleet…":"Fleet is restricted to authorized operational and safety roles."}/>:<><section className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric label="Active & current" value={metrics.active}/><Metric label="Needs attention" value={metrics.attention} alert={metrics.attention>0}/><Metric label="Trucks" value={metrics.trucks}/><Metric label="Trailers" value={metrics.trailers}/></section>
      <section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.length?assets.map((asset)=><button key={asset.id} onClick={()=>canManage&&setEditing(asset)} className="rounded-[22px] border border-[#DDE5F0] bg-white p-5 text-left hover:border-[#93C5FD]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#2563EB]">{asset.assetType}{asset.isReefer?" · Reefer":""}</p><h2 className="mt-2 text-xl font-semibold">Unit {asset.unitNumber}</h2><p className="mt-1 text-xs text-[#64748B]">{[asset.year,asset.make,asset.model].filter(Boolean).join(" ")||"Equipment details not recorded"}</p></div><Status asset={asset}/></div><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="Annual inspection" value={date(asset.annualInspectionExpiresOn)} alert={past(asset.annualInspectionExpiresOn)}/><Fact label="Registration" value={date(asset.registrationExpiresOn)} alert={past(asset.registrationExpiresOn)}/></div><p className="mt-4 text-[11px] text-[#94A3B8]">VIN ending {asset.vin.slice(-6)} · Verified {date(asset.verifiedAt)}</p></button>):<Empty text="No verified fleet assets recorded yet."/>}</section></>}
  </div></section>{editing&&<AssetEditor asset={editing==="new"?null:editing} onClose={()=>setEditing(null)} onSaved={(next)=>{setAssets(next);setEditing(null);}}/>}</main>;
}

function AssetEditor({asset,onClose,onSaved}:{asset:FleetAsset|null;onClose:()=>void;onSaved:(assets:FleetAsset[])=>void}){
  const [form,setForm]=useState(()=>asset?{assetType:asset.assetType,unitNumber:asset.unitNumber,vin:asset.vin,year:String(asset.year??""),make:asset.make??"",model:asset.model??"",status:asset.status,annualInspectionExpiresOn:asset.annualInspectionExpiresOn,registrationExpiresOn:asset.registrationExpiresOn,isReefer:asset.isReefer,note:""}:EMPTY); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const field=(key:keyof typeof form,value:string|boolean)=>setForm((current)=>({...current,[key]:value}));
  async function save(){setBusy(true);setMessage("");const result=await saveVerifiedFleetAssetAction({assetId:asset?.id,assetType:form.assetType,unitNumber:form.unitNumber,vin:form.vin,year:form.year?Number(form.year):null,make:form.make,model:form.model,status:form.status,annualInspectionExpiresOn:form.annualInspectionExpiresOn,registrationExpiresOn:form.registrationExpiresOn,isReefer:form.isReefer,note:form.note,requestId:crypto.randomUUID()});if(result.ok)onSaved(result.assets);else setMessage(result.error);setBusy(false);}
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#0F172A]/45 p-5"><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[24px] bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#2563EB]">Human verification</p><h2 className="mt-2 text-xl font-semibold">{asset?`Unit ${asset.unitNumber}`:"Add fleet asset"}</h2></div><button onClick={onClose} className="h-9 rounded-lg border px-3 text-xs font-semibold">Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Select label="Asset type" value={form.assetType} onChange={(v)=>field("assetType",v)} options={[["truck","Truck"],["trailer","Trailer"]]}/><Input label="Unit number" value={form.unitNumber} onChange={(v)=>field("unitNumber",v)}/><Input label="17-character VIN" value={form.vin} onChange={(v)=>field("vin",v.toUpperCase())}/><Input label="Model year" type="number" value={form.year} onChange={(v)=>field("year",v)}/><Input label="Make" value={form.make} onChange={(v)=>field("make",v)}/><Input label="Model" value={form.model} onChange={(v)=>field("model",v)}/><Select label="Verified status" value={form.status} onChange={(v)=>field("status",v)} options={[["active","Active"],["maintenance","Maintenance"],["out_of_service","Out of service"],["retired","Retired"]]}/><Input label="Annual inspection expires" type="date" value={form.annualInspectionExpiresOn} onChange={(v)=>field("annualInspectionExpiresOn",v)}/><Input label="Registration expires" type="date" value={form.registrationExpiresOn} onChange={(v)=>field("registrationExpiresOn",v)}/>{form.assetType==="trailer"&&<label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.isReefer} onChange={(event)=>field("isReefer",event.target.checked)}/> Reefer trailer</label>}<div className="sm:col-span-2"><Input label="Factual verification note" value={form.note} onChange={(v)=>field("note",v)}/></div></div><p className="mt-4 rounded-xl bg-[#FFF7ED] p-3 text-[11px] leading-5 text-[#9A3412]">Only active equipment with current registration and annual inspection can be assigned. Carrier and driver retain all equipment and safety decisions.</p>{message&&<p className="mt-3 rounded-xl bg-[#F8FAFC] p-3 text-xs text-[#475569]">{message}</p>}<button disabled={busy||!form.unitNumber||form.vin.length!==17||!form.annualInspectionExpiresOn||!form.registrationExpiresOn} onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-[#0F172A] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{busy?"Saving verified asset…":"Approve & save asset"}</button></section></div>;
}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="block text-[10px] font-semibold uppercase tracking-[.12em] text-[#64748B]"><span className="mb-1.5 block">{label}</span><input type={type} value={value} onChange={(event)=>onChange(event.target.value)} className="w-full rounded-xl border border-[#CBD5E1] px-3 py-2.5 text-xs"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="block text-[10px] font-semibold uppercase tracking-[.12em] text-[#64748B]"><span className="mb-1.5 block">{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)} className="w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs">{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-[20px] border p-5 ${alert?"border-[#FCA5A5] bg-[#FEF2F2]":"border-[#DDE5F0] bg-white"}`}><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#64748B]">{label}</p><p className={`mt-3 text-2xl font-semibold ${alert?"text-[#B91C1C]":""}`}>{value}</p></div>}
function Status({asset}:{asset:FleetAsset}){const bad=asset.status!=="active"||expired(asset);return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${bad?"bg-[#FEE2E2] text-[#B91C1C]":"bg-[#ECFDF5] text-[#047857]"}`}>{expired(asset)?"expired":asset.status.replaceAll("_"," ")}</span>}
function Fact({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#94A3B8]">{label}</p><p className={`mt-1 text-xs font-semibold ${alert?"text-[#B91C1C]":"text-[#334155]"}`}>{value}</p></div>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-[22px] border border-[#DDE5F0] bg-white p-10 text-center text-sm text-[#64748B]">{text}</div>}
function past(value:string){const time=new Date(`${value.slice(0,10)}T23:59:59Z`).getTime();return Number.isNaN(time)||time<Date.now()}
function expired(asset:FleetAsset){return past(asset.annualInspectionExpiresOn)||past(asset.registrationExpiresOn)}
function date(value:string){const parsed=new Date(value.length===10?`${value}T00:00:00Z`:value);return Number.isNaN(parsed.getTime())?"Not verified":new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"}).format(parsed)}
