"use server";
import { revalidatePath } from "next/cache";
import { requireDocumentAuth } from "@/lib/auth/supabase-server";
import { TelematicsRepository,type TelematicsConnection } from "@/lib/integrations/telematics";
import { getSupabaseAuthenticatedUserClient } from "@/lib/supabase/server";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,T=new Set(["eld","dashcam","eld_dashcam"]),S=new Set(["planned","active","paused","disconnected"]);
type Result={ok:true;connections:TelematicsConnection[];canManage:boolean}|{ok:false;error:string};
async function authorized(){const auth=await requireDocumentAuth();if(!["super_admin","owner","dispatcher","safety"].includes(auth.businessRole))throw new Error("Not authorized");return auth}
export async function getTelematicsConnectionsAction():Promise<Result>{try{const auth=await authorized();return{ok:true,connections:await new TelematicsRepository().list(auth.accessToken),canManage:["super_admin","owner"].includes(auth.businessRole)}}catch{return{ok:false,error:"ELD and dashcam registry is restricted or unavailable."}}}
export async function saveTelematicsConnectionAction(input:{id?:string;vendorName:string;connectionType:string;accountLabel:string;portalUrl?:string;supportPhone?:string;status:string;verifiedAt:string;note:string;requestId:string}):Promise<Result>{if((input.id&&!UUID.test(input.id))||!UUID.test(input.requestId)||!T.has(input.connectionType)||!S.has(input.status)||input.vendorName.trim().length<2||input.accountLabel.trim().length<2||!input.verifiedAt||input.note.trim().length<3||(input.portalUrl&&!/^https:\/\//i.test(input.portalUrl.trim())))return{ok:false,error:"Enter valid human-verified connection facts. Never enter credentials or tokens."};try{const auth=await authorized();if(!["super_admin","owner"].includes(auth.businessRole))return{ok:false,error:"Only an owner can manage connection records."};const db=getSupabaseAuthenticatedUserClient(auth.accessToken),result=await db.rpc("save_verified_telematics_connection",{p_connection_id:input.id||null,p_vendor_name:input.vendorName.trim(),p_connection_type:input.connectionType,p_account_label:input.accountLabel.trim(),p_portal_url:input.portalUrl?.trim()||null,p_support_phone:input.supportPhone?.trim()||null,p_status:input.status,p_verified_at:input.verifiedAt,p_note:input.note.trim(),p_request_id:input.requestId});if(result.error)return{ok:false,error:"Connection record was not saved. Verify the factual fields."};revalidatePath("/integrations");return{ok:true,connections:await new TelematicsRepository().list(auth.accessToken),canManage:true}}catch{return{ok:false,error:"Connection record was not saved. No vendor or device action occurred."}}}
