"use server";
import{revalidatePath}from"next/cache";import{requireDocumentAuth}from"@/lib/auth/supabase-server";import type{BusinessRole}from"@/lib/auth/roles";import{PayrollRepository,type PayrollWorkspace}from"@/lib/payroll/settlements";import{getSupabaseAuthenticatedUserClient}from"@/lib/supabase/server";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,READ=new Set<BusinessRole>(["super_admin","owner","accounting","driver"]),WRITE=new Set<BusinessRole>(["super_admin","owner","accounting"]);
type Result={ok:true;workspace:PayrollWorkspace;canManage:boolean}|{ok:false;error:string};async function auth(write=false){const value=await requireDocumentAuth();if(!(write?WRITE:READ).has(value.businessRole))throw new Error("unauthorized");return value}async function done(accessToken:string):Promise<Result>{return{ok:true,workspace:await new PayrollRepository().workspace(accessToken),canManage:true}}
export async function getPayrollWorkspaceAction():Promise<Result>{try{const value=await auth();return{ok:true,workspace:await new PayrollRepository().workspace(value.accessToken),canManage:WRITE.has(value.businessRole)}}catch{return{ok:false,error:"Payroll is restricted to authorized finance users and each driver's own statements."}}}
export async function saveVerifiedPayRateAction(input:{driverUserId:string;centsPerMile:number;effectiveOn:string;note?:string;requestId:string}):Promise<Result>{if(!UUID.test(input.driverUserId)||!UUID.test(input.requestId)||!Number.isInteger(input.centsPerMile)||input.centsPerMile<1||input.centsPerMile>1000||!date(input.effectiveOn))return{ok:false,error:"Enter a verified driver, mileage rate, and effective date."};try{const value=await auth(true),db=getSupabaseAuthenticatedUserClient(value.accessToken),result=await db.rpc("save_verified_driver_pay_rate",{p_driver_user_id:input.driverUserId,p_cents_per_mile:input.centsPerMile,p_effective_on:input.effectiveOn,p_note:input.note?.trim().slice(0,2000)||null,p_request_id:input.requestId});if(result.error)return{ok:false,error:"Pay rate was not saved. Verify the driver profile and effective date."};revalidatePath("/payroll");return done(value.accessToken)}catch{return{ok:false,error:"Pay rate was not saved. No payroll state changed."}}}
export async function approveVerifiedSettlementAction(input:{driverUserId:string;periodStart:string;periodEnd:string;loadIds:string[];extrasCents:number;deductionsCents:number;adjustmentNote?:string;requestId:string}):Promise<Result>{const ids=[...new Set(input.loadIds)];if(!UUID.test(input.driverUserId)||!UUID.test(input.requestId)||!date(input.periodStart)||!date(input.periodEnd)||input.periodEnd<input.periodStart||!ids.length||ids.length>100||ids.some(id=>!UUID.test(id))||ids.length!==input.loadIds.length||![input.extrasCents,input.deductionsCents].every(v=>Number.isSafeInteger(v)&&v>=0)||((input.extrasCents>0||input.deductionsCents>0)&&!input.adjustmentNote?.trim()))return{ok:false,error:"Select valid closed loads, payroll dates, and documented adjustments."};try{const value=await auth(true),db=getSupabaseAuthenticatedUserClient(value.accessToken),result=await db.rpc("approve_verified_driver_settlement",{p_driver_user_id:input.driverUserId,p_period_start:input.periodStart,p_period_end:input.periodEnd,p_load_ids:ids,p_extras_cents:input.extrasCents,p_deductions_cents:input.deductionsCents,p_adjustment_note:input.adjustmentNote?.trim().slice(0,2000)||null,p_request_id:input.requestId});if(result.error)return{ok:false,error:"Settlement requires verified closed loads, driver assignment, period, mileage, and effective pay rate."};revalidatePath("/payroll");return done(value.accessToken)}catch{return{ok:false,error:"Settlement was not approved. No payroll state changed."}}}
export async function recordVerifiedSettlementPaymentAction(input:{settlementId:string;paidAt:string;paymentReference:string;requestId:string}):Promise<Result>{if(!UUID.test(input.settlementId)||!UUID.test(input.requestId)||!input.paymentReference.trim()||Number.isNaN(new Date(input.paidAt).getTime()))return{ok:false,error:"Enter a confirmed payment date and reference."};try{const value=await auth(true),db=getSupabaseAuthenticatedUserClient(value.accessToken),result=await db.rpc("record_verified_driver_settlement_payment",{p_settlement_id:input.settlementId,p_paid_at:new Date(input.paidAt).toISOString(),p_payment_reference:input.paymentReference.trim().slice(0,200),p_request_id:input.requestId});if(result.error)return{ok:false,error:"Payment could not be recorded. Verify the approved unpaid settlement."};revalidatePath("/payroll");return done(value.accessToken)}catch{return{ok:false,error:"Payment was not recorded. No payroll state changed."}}}
function date(value:string){return/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(new Date(`${value}T00:00:00Z`).getTime())}
