"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getLoadDetailAction } from "@/app/actions/dispatch";
import Sidebar from "@/components/Sidebar";
import type { LoadDetail, LoadStopDetail } from "@/lib/operations/load-types";

export default function LoadDetailWorkspace({loadId}:{loadId:string}) {
  const [detail,setDetail]=useState<LoadDetail|null>(null); const [state,setState]=useState<"loading"|"ready"|"not-found"|"unavailable">("loading");
  useEffect(()=>{let active=true;getLoadDetailAction(loadId).then((result)=>{if(!active)return;if(!result.ok)setState("unavailable");else if(!result.load)setState("not-found");else{setDetail(result.load);setState("ready");}}).catch(()=>{if(active)setState("unavailable");});return()=>{active=false;};},[loadId]);
  return <main className="min-h-screen bg-[#F5F7FB] text-[#0B1220]"><Sidebar/><section className="ml-72 min-h-screen px-8 py-7 xl:px-10"><div className="mx-auto max-w-[1400px]"><Link href="/dispatch" className="text-xs font-semibold text-[#2563EB]">← Dispatch board</Link>{state!=="ready"||!detail?<Empty state={state}/>:<Detail detail={detail}/>}</div></section></main>;
}
function Detail({detail}:{detail:LoadDetail}) { return <><header className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2563EB]">Verified load detail</p><h1 className="mt-2 text-[34px] font-semibold">{detail.loadNumber||"Load number pending"}</h1><p className="mt-2 text-sm text-[#64748B]">{detail.origin||"Origin not recorded"} → {detail.destination||"Destination not recorded"}</p></div><div className="flex gap-2"><Disabled label="Call driver"/><Disabled label="Message driver"/></div></header>
  <section className="mt-6 grid gap-4 lg:grid-cols-4"><Card label="Pickup number" value={detail.pickupNumber||"Not recorded"} prominent/><Card label="Status" value={detail.status.replaceAll("_"," ")}/><Card label="Driver / truck / trailer" value={[detail.driverUserId?"Assigned driver":"Unassigned",detail.truckUnit,detail.trailerUnit].filter(Boolean).join(" · ")}/><Card label="Rate" value={detail.rateCents===undefined?"Restricted or not recorded":money(detail.rateCents,detail.currency)}/></section>
  <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,.8fr)]"><div className="space-y-4"><Panel title="Stops and appointments"><div className="space-y-3">{detail.stops.length?detail.stops.map((s)=><Stop key={s.id} stop={s}/>):<Missing text="No verified stops recorded."/>}</div></Panel><Panel title="Freight and equipment"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Fact label="Commodity" value={detail.commodity}/><Fact label="Weight" value={detail.weightLbs===undefined?undefined:`${detail.weightLbs.toLocaleString()} lb`}/><Fact label="Equipment" value={detail.equipmentType}/><Fact label="Temperature" value={detail.temperatureRequirement}/><Fact label="Seal number" value={detail.sealNumber}/><Fact label="Delivery number" value={detail.deliveryNumber}/></div></Panel><Panel title="Operational timeline"><div className="space-y-3">{detail.timeline.length?detail.timeline.map((e)=><div key={e.id} className="rounded-xl border border-[#E2E8F0] p-3"><div className="flex justify-between gap-2"><b className="text-xs capitalize">{e.type.replaceAll("_"," ")}</b><span className="text-[11px] text-[#64748B]">{dateTime(e.eventAt)}</span></div><p className="mt-1 text-xs text-[#64748B]">{[e.location,e.eta?`ETA ${dateTime(e.eta)}`:undefined,e.note,`Source: ${e.source}`].filter(Boolean).join(" · ")}</p></div>):<Missing text="No verified timeline events recorded."/>}</div></Panel></div>
  <aside className="space-y-4"><Panel title="Current position"><Fact label="Verified location" value={detail.currentLocation}/><div className="mt-3"><Fact label="ETA" value={detail.eta?dateTime(detail.eta):undefined}/></div><p className="mt-3 text-[11px] text-[#64748B]">Tracking is integration-ready. Location and ETA are never guessed.</p></Panel><Panel title="Instructions and safety"><Fact label="Special instructions" value={detail.specialInstructions}/><div className="mt-3"><Fact label="Emergency requirements" value={detail.emergencyRequirements}/></div><p className="mt-3 rounded-xl bg-[#0F172A] p-3 text-[11px] leading-5 text-[#CBD5E1]">Driver and carrier retain every safety, movement, and equipment decision.</p></Panel><Panel title="Contacts"><Fact label="Broker" value={detail.brokerName}/><div className="mt-3"><Fact label="Broker contact" value={detail.brokerContact}/></div><div className="mt-3"><Fact label="Emergency contact" value={detail.emergencyRequirements?"See emergency requirements":undefined}/></div></Panel><Panel title="Documents"><p className="text-xs text-[#64748B]">Open Document Center for the verified rate confirmation, BOL, POD, and supporting files.</p><Link href="/documents" className="mt-3 inline-flex rounded-lg border border-[#CBD5E1] px-3 py-2 text-xs font-semibold">Open documents</Link></Panel><Panel title="Nova helper"><p className="text-xs leading-5 text-[#64748B]">Suggestions are coming soon. Nova organizes facts; a human approves operational or financial changes.</p></Panel></aside></div></>; }
function Empty({state}:{state:string}){return <section className="mt-6 grid min-h-[420px] place-items-center rounded-[24px] border border-[#DDE5F0] bg-white p-8 text-center"><div><h1 className="text-xl font-semibold">{state==="loading"?"Loading authorized load data":state==="not-found"?"Load not found or not authorized":"Load operations unavailable"}</h1><p className="mt-2 text-sm text-[#64748B]">No unverified operational data will be displayed.</p></div></section>;}
function Stop({stop}:{stop:LoadStopDetail}){return <div className="rounded-2xl border border-[#E2E8F0] p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#2563EB]">{stop.sequence}. {stop.type}</p><h3 className="mt-2 text-sm font-semibold">{stop.facilityName||"Facility not recorded"}</h3><p className="mt-1 text-xs text-[#64748B]">{[stop.address,stop.city,stop.state].filter(Boolean).join(", ")||"Address not recorded"}</p></div><div className="text-right"><b className="text-xs">{dateTime(stop.appointmentAt)}</b><p className="mt-1 text-[11px] text-[#64748B]">{stop.appointmentTimezone||"Time zone not recorded"}</p></div></div>{stop.referenceNumber&&<p className="mt-3 rounded-lg bg-[#EFF6FF] px-3 py-2 text-xs font-semibold text-[#1D4ED8]">Reference / pickup # {stop.referenceNumber}</p>}</div>;}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[22px] border border-[#DDE5F0] bg-white p-5"><h2 className="mb-4 text-sm font-semibold">{title}</h2>{children}</section>;}
function Card({label,value,prominent=false}:{label:string;value:string;prominent?:boolean}){return <section className={`rounded-[20px] border p-4 ${prominent?"border-[#93C5FD] bg-[#EFF6FF]":"border-[#DDE5F0] bg-white"}`}><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#64748B]">{label}</p><p className={`mt-3 font-semibold capitalize ${prominent?"text-xl text-[#1D4ED8]":"text-sm"}`}>{value||"Not recorded"}</p></section>;}
function Fact({label,value}:{label:string;value?:string}){return <div><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#94A3B8]">{label}</p><p className="mt-1 text-xs font-medium text-[#334155]">{value||"Not recorded"}</p></div>;}
function Missing({text}:{text:string}){return <p className="rounded-xl bg-[#F8FAFC] p-4 text-xs text-[#64748B]">{text}</p>;}
function Disabled({label}:{label:string}){return <button disabled title="Communication provider coming soon" className="cursor-not-allowed rounded-xl border border-[#CBD5E1] bg-white px-4 py-2.5 text-sm font-semibold text-[#94A3B8]">{label} · Coming soon</button>;}
function dateTime(value?:string){if(!value)return"Not recorded";const d=new Date(value);return Number.isNaN(d.getTime())?"Not recorded":new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(d);} function money(cents:number,currency="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(cents/100);}
