import type {
  CopilotActivityItem,
  CopilotAlert,
  CopilotLearningInsight,
  CopilotMemoryItem,
} from "@/lib/alph-copilot/types";

const NOW = "2026-07-17T14:30:00.000Z";
const HOUR_AGO = "2026-07-17T13:30:00.000Z";
const TWO_HOURS = "2026-07-17T12:15:00.000Z";
const MORNING = "2026-07-17T08:05:00.000Z";

export const SEED_MEMORY: CopilotMemoryItem[] = [
  {
    id: "mem-d-truck",
    role: "driver",
    kind: "preferred_truck",
    label: "Preferred truck",
    value: "Unit 105 — Cascadia, prefers this for long hauls",
    updatedAt: MORNING,
  },
  {
    id: "mem-d-route",
    role: "driver",
    kind: "preferred_route",
    label: "Preferred lane",
    value: "Dallas ↔ Atlanta overnight",
    updatedAt: MORNING,
  },
  {
    id: "mem-d-fuel",
    role: "driver",
    kind: "favorite_fuel_stop",
    label: "Favorite fuel",
    value: "TA Dallas South — Pilot Rewards",
    updatedAt: HOUR_AGO,
  },
  {
    id: "mem-d-contact",
    role: "driver",
    kind: "frequent_contact",
    label: "Dispatch contact",
    value: "Maya Chen — always text first",
    updatedAt: TWO_HOURS,
  },
  {
    id: "mem-dp-habit",
    role: "dispatcher",
    kind: "dispatch_habit",
    label: "Assign habit",
    value: "Prefer drivers with 4+ hrs remaining for TX loads",
    updatedAt: MORNING,
  },
  {
    id: "mem-dp-contact",
    role: "dispatcher",
    kind: "frequent_contact",
    label: "Top broker",
    value: "TQL — morning freight desk",
    updatedAt: HOUR_AGO,
  },
  {
    id: "mem-dp-customer",
    role: "dispatcher",
    kind: "customer_pref",
    label: "Customer preference",
    value: "Walmart DC prefers early morning appointments",
    updatedAt: TWO_HOURS,
  },
  {
    id: "mem-s-issue",
    role: "safety",
    kind: "previous_issue",
    label: "Recent issue",
    value: "Unit 102 hard-braking cluster — coaching scheduled",
    updatedAt: MORNING,
  },
  {
    id: "mem-s-doc",
    role: "safety",
    kind: "frequent_doc",
    label: "Watch list",
    value: "Medical cards for 3 drivers expire this month",
    updatedAt: HOUR_AGO,
  },
  {
    id: "mem-m-truck",
    role: "maintenance",
    kind: "preferred_truck",
    label: "Shop priority",
    value: "Unit 108 — PM overdue, hold for Tuesday bay",
    updatedAt: MORNING,
  },
  {
    id: "mem-m-parts",
    role: "maintenance",
    kind: "frequent_doc",
    label: "Parts vendor",
    value: "Prefer OEM turbo from Exchange sellers with 4.8+",
    updatedAt: TWO_HOURS,
  },
  {
    id: "mem-a-customer",
    role: "accounting",
    kind: "customer_pref",
    label: "Billing preference",
    value: "ABC Logistics wants POD + lumper on every invoice",
    updatedAt: MORNING,
  },
  {
    id: "mem-a-habit",
    role: "accounting",
    kind: "company_pref",
    label: "Payroll cadence",
    value: "Settlements every Friday; owner-ops paid Monday",
    updatedAt: HOUR_AGO,
  },
  {
    id: "mem-o-company",
    role: "owner",
    kind: "company_pref",
    label: "Focus metrics",
    value: "Cash flow + fleet health before revenue vanity",
    updatedAt: MORNING,
  },
  {
    id: "mem-o-conv",
    role: "owner",
    kind: "conversation",
    label: "Last brief",
    value: "Asked about empty miles on Midwest lanes yesterday",
    updatedAt: TWO_HOURS,
  },
];

export const SEED_ALERTS: CopilotAlert[] = [
  {
    id: "alert-fuel-discount",
    role: "driver",
    title: "Fuel discount nearby",
    body: "Love's on I-35 is $0.18/gal below your average — 12 miles ahead.",
    severity: "success",
    category: "fuel",
    createdAt: NOW,
    status: "active",
    actions: [
      { label: "Navigate", href: "/driver/services", primary: true },
      { label: "Snooze 1h", commandId: "snooze" },
    ],
  },
  {
    id: "alert-weather",
    role: "driver",
    title: "Dangerous weather ahead",
    body: "Severe thunderstorms on your delivery corridor after 6pm. Consider earlier arrival.",
    severity: "warning",
    category: "weather",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [
      { label: "View safety", href: "/driver/safety", primary: true },
      { label: "Notify dispatch", href: "/driver/messages" },
    ],
  },
  {
    id: "alert-pod-missing",
    role: "driver",
    title: "Document missing",
    body: "Load LD-24019 delivered — POD not uploaded yet.",
    severity: "critical",
    category: "documents",
    createdAt: TWO_HOURS,
    status: "active",
    actions: [
      { label: "Upload POD", href: "/driver/documents", primary: true },
    ],
  },
  {
    id: "alert-driver-delayed",
    role: "dispatcher",
    title: "Driver delayed",
    body: "John Smith is 47 min behind ETA on LD-24012. Broker window closes at 4pm.",
    severity: "critical",
    category: "delay",
    createdAt: NOW,
    status: "active",
    actions: [
      { label: "Open load", href: "/loads", primary: true },
      { label: "Find reload", commandId: "find_reload" },
    ],
  },
  {
    id: "alert-high-pay",
    role: "dispatcher",
    title: "Load above average pay",
    body: "Dallas → Chicago reefer posted at $3.42/mi — 22% above your 30-day average.",
    severity: "success",
    category: "opportunity",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [
      { label: "Open loads", href: "/loads", primary: true },
      { label: "Assign best", commandId: "assign_best_driver" },
    ],
  },
  {
    id: "alert-detention",
    role: "dispatcher",
    title: "Detention risk",
    body: "Unit 104 has been at shipper 2h 10m — detention clock starts soon.",
    severity: "warning",
    category: "detention",
    createdAt: TWO_HOURS,
    status: "active",
    actions: [{ label: "Open Dispatch", href: "/loads", primary: true }],
  },
  {
    id: "alert-insurance",
    role: "safety",
    title: "Insurance expires soon",
    body: "Cargo policy renews in 12 days. Binder request should go out today.",
    severity: "warning",
    category: "compliance",
    createdAt: MORNING,
    status: "active",
    actions: [
      { label: "Open compliance", href: "/compliance", primary: true },
    ],
  },
  {
    id: "alert-speeding",
    role: "safety",
    title: "Speeding cluster",
    body: "3 speeding events on Unit 102 this morning. Risk score trending up.",
    severity: "critical",
    category: "events",
    createdAt: NOW,
    status: "active",
    actions: [
      { label: "Review", href: "/compliance", primary: true },
    ],
  },
  {
    id: "alert-medical",
    role: "safety",
    title: "Medical card expiring",
    body: "Two drivers have medical cards expiring within 21 days.",
    severity: "warning",
    category: "expiry",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [
      { label: "Show expiring", commandId: "show_expiring_docs", primary: true },
      { label: "Compliance", href: "/compliance" },
    ],
  },
  {
    id: "alert-pm-due",
    role: "maintenance",
    title: "Maintenance due",
    body: "Unit 108 PM is 180 miles overdue. Shop bay open Tuesday 9am.",
    severity: "warning",
    category: "pm",
    createdAt: NOW,
    status: "active",
    actions: [
      {
        label: "Schedule",
        commandId: "schedule_maintenance",
        primary: true,
      },
      { label: "Open board", href: "/fleet/maintenance" },
    ],
  },
  {
    id: "alert-idle",
    role: "maintenance",
    title: "High idle time",
    body: "Unit 106 idled 3.2 hours yesterday — ~$48 fuel waste estimated.",
    severity: "info",
    category: "fuel",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [{ label: "View truck", href: "/fleet/trucks", primary: true }],
  },
  {
    id: "alert-fuel-theft",
    role: "maintenance",
    title: "Fuel theft suspected",
    body: "Unit 103 dropped 48 gallons overnight with no movement. Review recommended.",
    severity: "critical",
    category: "fuel",
    createdAt: TWO_HOURS,
    status: "active",
    actions: [
      { label: "Investigate", href: "/fleet/trucks", primary: true },
    ],
  },
  {
    id: "alert-payment",
    role: "accounting",
    title: "Payment overdue",
    body: "ABC Logistics invoice INV-8841 is 34 days past due ($12,400).",
    severity: "critical",
    category: "receivables",
    createdAt: NOW,
    status: "active",
    actions: [
      { label: "Open finance", href: "/finance", primary: true },
    ],
  },
  {
    id: "alert-missing-docs",
    role: "accounting",
    title: "Missing documents",
    body: "4 delivered loads are blocked from invoicing — POD or lumper missing.",
    severity: "warning",
    category: "documents",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [
      { label: "Documents", href: "/documents", primary: true },
      { label: "Create invoices", commandId: "create_invoices" },
    ],
  },
  {
    id: "alert-owner-cash",
    role: "owner",
    title: "Cash flow attention",
    body: "Projected cash dips below your comfort band next Wednesday without collections.",
    severity: "warning",
    category: "cash",
    createdAt: MORNING,
    status: "active",
    actions: [
      { label: "Finance", href: "/finance", primary: true },
      { label: "Today's profit", commandId: "show_todays_profit" },
    ],
  },
  {
    id: "alert-owner-fleet",
    role: "owner",
    title: "Fleet health soft",
    body: "2 trucks in shop, 1 PM overdue — utilization at 78% vs 86% target.",
    severity: "info",
    category: "fleet",
    createdAt: HOUR_AGO,
    status: "active",
    actions: [
      { label: "Dashboard", href: "/dashboard", primary: true },
      { label: "Maintenance", href: "/fleet/maintenance" },
    ],
  },
];

export const SEED_LEARNING: CopilotLearningInsight[] = [
  {
    id: "learn-1",
    role: "dispatcher",
    title: "Alph improved driver suggestions",
    detail:
      "Now prefers drivers with 4+ hours remaining on Texas loads based on your last 28 assignments.",
    basedOn: "Dispatch habit: TX loads need buffer hours",
    improved: "Best-driver ranking",
    automationHref: "/platform/automation",
    automationLabel: "Automate assign suggestions",
  },
  {
    id: "learn-2",
    role: "accounting",
    title: "Alph improved invoice packets",
    detail:
      "Always attaches POD + lumper for ABC Logistics before drafting.",
    basedOn: "Customer billing preference",
    improved: "Invoice completeness",
    automationHref: "/workflows",
    automationLabel: "Invoice workflow",
  },
  {
    id: "learn-3",
    role: "driver",
    title: "Alph improved fuel stops",
    detail: "Surfaces TA Dallas South first when you're southbound on I-35.",
    basedOn: "Favorite fuel stop + route memory",
    improved: "Fuel discount ranking",
  },
  {
    id: "learn-4",
    role: "owner",
    title: "Alph improved morning brief",
    detail: "Leads with cash flow and fleet health before revenue totals.",
    basedOn: "Company focus metrics",
    improved: "Briefing order",
    automationHref: "/platform/automation",
    automationLabel: "Daily brief recipe",
  },
  {
    id: "learn-5",
    role: "safety",
    title: "Alph improved expiry watch",
    detail: "Flags medical cards 21 days out instead of 14 — matching your review cadence.",
    basedOn: "Safety review habit",
    improved: "Expiry lead time",
    automationHref: "/workflows",
    automationLabel: "Expiry reminders",
  },
  {
    id: "learn-6",
    role: "maintenance",
    title: "Alph improved parts sourcing",
    detail: "Prefers Exchange sellers rated 4.8+ for OEM turbo searches.",
    basedOn: "Parts vendor preference",
    improved: "Exchange recommendations",
    automationHref: "/exchange/parts",
    automationLabel: "Browse parts",
  },
  {
    id: "learn-7",
    role: "all",
    title: "Suggested automation",
    detail:
      "When a load is delivered and POD is uploaded, draft the invoice automatically.",
    basedOn: "Accounting + document patterns",
    improved: "End-to-end billing speed",
    automationHref: "/platform/automation",
    automationLabel: "Open Automation",
  },
];

export const SEED_ACTIVITY: CopilotActivityItem[] = [
  {
    id: "act-1",
    role: "dispatcher",
    title: "Suggested Maria Lopez for LD-24022",
    detail: "Best fit — 6.2 hrs left, already near Dallas",
    at: NOW,
    href: "/loads",
  },
  {
    id: "act-2",
    role: "accounting",
    title: "Drafted 3 invoices",
    detail: "Ready for review — POD attached",
    at: HOUR_AGO,
    href: "/finance",
  },
  {
    id: "act-3",
    role: "safety",
    title: "Flagged Unit 102 speeding cluster",
    detail: "Risk score +8 this morning",
    at: TWO_HOURS,
    href: "/compliance",
  },
  {
    id: "act-4",
    role: "maintenance",
    title: "Queued PM for Unit 108",
    detail: "Tuesday 9am bay reserved",
    at: MORNING,
    href: "/fleet/maintenance",
  },
  {
    id: "act-5",
    role: "driver",
    title: "Reminded about break window",
    detail: "30-min break due in 45 minutes",
    at: HOUR_AGO,
    href: "/driver",
  },
  {
    id: "act-6",
    role: "owner",
    title: "Morning brief delivered",
    detail: "3 priorities, 2 cash risks, 1 opportunity",
    at: MORNING,
    href: "/dashboard",
  },
];

export const DEFAULT_LEARNING_PREFS: Record<string, string | number | boolean> =
  {
    preferCashBeforeRevenue: true,
    txLoadHourBuffer: 4,
    medicalExpiryLeadDays: 21,
    fuelStopPreference: "rewards",
    autoAttachPodLumper: true,
    exchangeMinSellerRating: 4.8,
  };
